"""Independent conduction and when metadata for localize_execution."""
from __future__ import annotations
import json

_PATH_ID = 'localize_execution'
_NODES = {'build_deterministic_localization': {'atom': 'build_deterministic_localization',
                                      'conduction': ['prepare_localization_request'],
                                      'when': None},
 'build_explicit_localization': {'atom': 'build_explicit_localization',
                                 'conduction': ['prepare_localization_request',
                                                'inspect_existing_localization',
                                                'classify_localization_route'],
                                 'when': None},
 'build_localization_agent_request': {'atom': 'build_localization_agent_request',
                                      'conduction': ['prepare_localization_request',
                                                     'inspect_existing_localization',
                                                     'classify_localization_route'],
                                      'when': None},
 'build_localization_retry': {'atom': 'build_localization_retry',
                              'conduction': ['validate_localization_agent_json'],
                              'when': None},
 'classify_localization_route': {'atom': 'classify_localization_route',
                                 'conduction': ['prepare_localization_request',
                                                'inspect_existing_localization'],
                                 'when': None},
 'inspect_existing_localization': {'atom': 'inspect_existing_localization',
                                   'conduction': ['prepare_localization_request'],
                                   'when': None},
 'localization_terminal': {'atom': 'localization_terminal',
                           'conduction': ['select_localization_candidate', 'write_localization_evidence'],
                           'when': None},
 'prepare_localization_request': {'atom': 'prepare_localization_request', 'conduction': [], 'when': None},
 'retry_localization_agent': {'atom': 'retry_localization_agent',
                              'conduction': ['prepare_localization_request',
                                             'build_localization_agent_request',
                                             'build_localization_retry'],
                              'when': {'equals': 'retry',
                                       'path': 'route',
                                       'upstream': 'build_localization_retry'}},
 'run_localization_agent': {'atom': 'run_localization_agent',
                            'conduction': ['prepare_localization_request',
                                           'build_localization_agent_request'],
                            'when': {'equals': 'agent',
                                     'path': 'route',
                                     'upstream': 'build_localization_agent_request'}},
 'select_localization_candidate': {'atom': 'select_localization_candidate',
                                   'conduction': ['classify_localization_route',
                                                  'build_explicit_localization',
                                                  'build_deterministic_localization',
                                                  'run_localization_agent',
                                                  'validate_localization_agent_json',
                                                  'retry_localization_agent',
                                                  'validate_localization_retry_json'],
                                   'when': None},
 'validate_localization_agent_json': {'atom': 'validate_localization_agent_json',
                                      'conduction': ['run_localization_agent'],
                                      'when': None},
 'validate_localization_paths': {'atom': 'validate_localization_paths',
                                 'conduction': ['prepare_localization_request',
                                                'inspect_existing_localization',
                                                'build_localization_agent_request',
                                                'select_localization_candidate'],
                                 'when': None},
 'validate_localization_retry_json': {'atom': 'validate_localization_retry_json',
                                      'conduction': ['retry_localization_agent'],
                                      'when': None},
 'write_localization_evidence': {'atom': 'write_localization_evidence',
                                 'conduction': ['prepare_localization_request',
                                                'validate_localization_paths'],
                                 'when': None}}
_COND_EDGES = [('prepare_localization_request', 'inspect_existing_localization'),
 ('prepare_localization_request', 'classify_localization_route'),
 ('inspect_existing_localization', 'classify_localization_route'),
 ('prepare_localization_request', 'build_explicit_localization'),
 ('inspect_existing_localization', 'build_explicit_localization'),
 ('classify_localization_route', 'build_explicit_localization'),
 ('prepare_localization_request', 'build_deterministic_localization'),
 ('prepare_localization_request', 'build_localization_agent_request'),
 ('inspect_existing_localization', 'build_localization_agent_request'),
 ('classify_localization_route', 'build_localization_agent_request'),
 ('prepare_localization_request', 'run_localization_agent'),
 ('build_localization_agent_request', 'run_localization_agent'),
 ('run_localization_agent', 'validate_localization_agent_json'),
 ('validate_localization_agent_json', 'build_localization_retry'),
 ('prepare_localization_request', 'retry_localization_agent'),
 ('build_localization_agent_request', 'retry_localization_agent'),
 ('build_localization_retry', 'retry_localization_agent'),
 ('retry_localization_agent', 'validate_localization_retry_json'),
 ('classify_localization_route', 'select_localization_candidate'),
 ('build_explicit_localization', 'select_localization_candidate'),
 ('build_deterministic_localization', 'select_localization_candidate'),
 ('run_localization_agent', 'select_localization_candidate'),
 ('validate_localization_agent_json', 'select_localization_candidate'),
 ('retry_localization_agent', 'select_localization_candidate'),
 ('validate_localization_retry_json', 'select_localization_candidate'),
 ('prepare_localization_request', 'validate_localization_paths'),
 ('inspect_existing_localization', 'validate_localization_paths'),
 ('build_localization_agent_request', 'validate_localization_paths'),
 ('select_localization_candidate', 'validate_localization_paths'),
 ('prepare_localization_request', 'write_localization_evidence'),
 ('validate_localization_paths', 'write_localization_evidence'),
 ('select_localization_candidate', 'localization_terminal'),
 ('write_localization_evidence', 'localization_terminal')]
_WHEN_BRANCHES = [('run_localization_agent',
  {'equals': 'agent', 'path': 'route', 'upstream': 'build_localization_agent_request'}),
 ('retry_localization_agent', {'equals': 'retry', 'path': 'route', 'upstream': 'build_localization_retry'})]
_EFFECTORS = [{'conduction': [], 'id': 'prepare_localization_request', 'when': None},
 {'conduction': ['prepare_localization_request'], 'id': 'inspect_existing_localization', 'when': None},
 {'conduction': ['prepare_localization_request', 'inspect_existing_localization'],
  'id': 'classify_localization_route',
  'when': None},
 {'conduction': ['prepare_localization_request',
                 'inspect_existing_localization',
                 'classify_localization_route'],
  'id': 'build_explicit_localization',
  'when': None},
 {'conduction': ['prepare_localization_request'], 'id': 'build_deterministic_localization', 'when': None},
 {'conduction': ['prepare_localization_request',
                 'inspect_existing_localization',
                 'classify_localization_route'],
  'id': 'build_localization_agent_request',
  'when': None},
 {'conduction': ['prepare_localization_request', 'build_localization_agent_request'],
  'id': 'run_localization_agent',
  'when': {'equals': 'agent', 'path': 'route', 'upstream': 'build_localization_agent_request'}},
 {'conduction': ['run_localization_agent'], 'id': 'validate_localization_agent_json', 'when': None},
 {'conduction': ['validate_localization_agent_json'], 'id': 'build_localization_retry', 'when': None},
 {'conduction': ['prepare_localization_request',
                 'build_localization_agent_request',
                 'build_localization_retry'],
  'id': 'retry_localization_agent',
  'when': {'equals': 'retry', 'path': 'route', 'upstream': 'build_localization_retry'}},
 {'conduction': ['retry_localization_agent'], 'id': 'validate_localization_retry_json', 'when': None},
 {'conduction': ['classify_localization_route',
                 'build_explicit_localization',
                 'build_deterministic_localization',
                 'run_localization_agent',
                 'validate_localization_agent_json',
                 'retry_localization_agent',
                 'validate_localization_retry_json'],
  'id': 'select_localization_candidate',
  'when': None},
 {'conduction': ['prepare_localization_request',
                 'inspect_existing_localization',
                 'build_localization_agent_request',
                 'select_localization_candidate'],
  'id': 'validate_localization_paths',
  'when': None},
 {'conduction': ['prepare_localization_request', 'validate_localization_paths'],
  'id': 'write_localization_evidence',
  'when': None},
 {'conduction': ['select_localization_candidate', 'write_localization_evidence'],
  'id': 'localization_terminal',
  'when': None}]

def test_every_conduction_edge_is_declared():
    got = {(str(up), nid) for nid, meta in _NODES.items() for up in meta["conduction"]}
    assert got == set(tuple(edge) for edge in _COND_EDGES)

def test_every_when_branch_is_declared():
    got = {(nid, json.dumps(meta["when"], sort_keys=True)) for nid, meta in _NODES.items() if meta["when"]}
    want = {(nid, json.dumps(when, sort_keys=True)) for nid, when in _WHEN_BRANCHES}
    assert got == want

def test_when_upstream_is_a_direct_parent():
    for nid, when in _WHEN_BRANCHES:
        assert when["upstream"] in _NODES[nid]["conduction"]

def test_unconditional_nodes_succeed_without_outputs():
    from support.graph_model import run_model
    status = run_model(_EFFECTORS, {})
    for nid, meta in _NODES.items():
        if meta["when"] is None:
            assert status[nid] == "succeeded"

