"""Independent conduction and when metadata for implementation_dispatch."""
from __future__ import annotations
import json

_PATH_ID = 'implementation_dispatch'
_NODES = {'drop_stale_implementation_candidate': {'atom': 'drop_stale_implementation_candidate',
                                         'conduction': ['select_ready_outcome'],
                                         'when': {'equals': 'stale',
                                                  'path': 'route',
                                                  'upstream': 'select_ready_outcome'}},
 'inspect_implementation_mutex': {'atom': 'inspect_implementation_mutex',
                                  'conduction': ['select_implementation_candidate'],
                                  'when': {'equals': 'candidate',
                                           'path': 'route',
                                           'upstream': 'select_implementation_candidate'}},
 'keep_busy_launch': {'atom': 'keep_busy_launch',
                      'conduction': ['select_launch_route'],
                      'when': {'equals': 'busy', 'path': 'route', 'upstream': 'select_launch_route'}},
 'keep_implementation_candidate': {'atom': 'keep_implementation_candidate',
                                   'conduction': ['select_mutex_outcome'],
                                   'when': {'equals': 'keep',
                                            'path': 'route',
                                            'upstream': 'select_mutex_outcome'}},
 'label_blocked_dispatch': {'atom': 'label_blocked_dispatch',
                            'conduction': ['select_dispatch_outcome'],
                            'when': {'equals': 'blocked',
                                     'path': 'route',
                                     'upstream': 'select_dispatch_outcome'}},
 'launch_issue_to_pr': {'atom': 'launch_issue_to_pr',
                        'conduction': ['select_ready_outcome'],
                        'when': {'equals': 'ready', 'path': 'route', 'upstream': 'select_ready_outcome'}},
 'park_plan_only_dispatch': {'atom': 'park_plan_only_dispatch',
                             'conduction': ['select_blocked_dispatch'],
                             'when': {'equals': 'park',
                                      'path': 'route',
                                      'upstream': 'select_blocked_dispatch'}},
 'persist_blocked_dispatch': {'atom': 'persist_blocked_dispatch',
                              'conduction': ['label_blocked_dispatch'],
                              'when': None},
 'persist_dispatch_stuck': {'atom': 'persist_dispatch_stuck',
                            'conduction': ['select_dispatch_outcome'],
                            'when': {'equals': True,
                                     'path': 'stuck_changed',
                                     'upstream': 'select_dispatch_outcome'}},
 'record_dispatch_failure': {'atom': 'record_dispatch_failure',
                             'conduction': ['select_launch_route'],
                             'when': {'equals': 'failed',
                                      'path': 'route',
                                      'upstream': 'select_launch_route'}},
 'record_dispatch_success': {'atom': 'record_dispatch_success',
                             'conduction': ['select_launch_route'],
                             'when': {'equals': 'started',
                                      'path': 'route',
                                      'upstream': 'select_launch_route'}},
 'select_blocked_dispatch': {'atom': 'select_blocked_dispatch',
                             'conduction': ['persist_blocked_dispatch', 'select_dispatch_outcome'],
                             'when': None},
 'select_dispatch_outcome': {'atom': 'select_dispatch_outcome',
                             'conduction': ['record_dispatch_success', 'record_dispatch_failure'],
                             'when': None},
 'select_implementation_candidate': {'atom': 'select_implementation_candidate',
                                     'conduction': [],
                                     'when': None},
 'select_launch_route': {'atom': 'select_launch_route',
                         'conduction': ['select_ready_outcome', 'launch_issue_to_pr'],
                         'when': None},
 'select_mutex_outcome': {'atom': 'select_mutex_outcome',
                          'conduction': ['select_implementation_candidate', 'inspect_implementation_mutex'],
                          'when': None},
 'select_ready_outcome': {'atom': 'select_ready_outcome',
                          'conduction': ['select_mutex_outcome', 'verify_selected_issue_ready'],
                          'when': None},
 'summarize_implementation_dispatch': {'atom': 'summarize_implementation_dispatch',
                                       'conduction': ['select_implementation_candidate',
                                                      'inspect_implementation_mutex',
                                                      'select_mutex_outcome',
                                                      'keep_implementation_candidate',
                                                      'verify_selected_issue_ready',
                                                      'select_ready_outcome',
                                                      'drop_stale_implementation_candidate',
                                                      'launch_issue_to_pr',
                                                      'select_launch_route',
                                                      'keep_busy_launch',
                                                      'record_dispatch_success',
                                                      'record_dispatch_failure',
                                                      'select_dispatch_outcome',
                                                      'persist_dispatch_stuck',
                                                      'label_blocked_dispatch',
                                                      'persist_blocked_dispatch',
                                                      'select_blocked_dispatch',
                                                      'park_plan_only_dispatch',
                                                      'write_dispatch_receipt'],
                                       'when': None},
 'verify_selected_issue_ready': {'atom': 'verify_selected_issue_ready',
                                 'conduction': ['select_mutex_outcome'],
                                 'when': {'equals': 'free',
                                          'path': 'route',
                                          'upstream': 'select_mutex_outcome'}},
 'write_dispatch_receipt': {'atom': 'write_dispatch_receipt',
                            'conduction': ['select_dispatch_outcome'],
                            'when': {'equals': 'receipt',
                                     'path': 'route',
                                     'upstream': 'select_dispatch_outcome'}}}
_COND_EDGES = [('select_implementation_candidate', 'inspect_implementation_mutex'),
 ('select_implementation_candidate', 'select_mutex_outcome'),
 ('inspect_implementation_mutex', 'select_mutex_outcome'),
 ('select_mutex_outcome', 'keep_implementation_candidate'),
 ('select_mutex_outcome', 'verify_selected_issue_ready'),
 ('select_mutex_outcome', 'select_ready_outcome'),
 ('verify_selected_issue_ready', 'select_ready_outcome'),
 ('select_ready_outcome', 'drop_stale_implementation_candidate'),
 ('select_ready_outcome', 'launch_issue_to_pr'),
 ('select_ready_outcome', 'select_launch_route'),
 ('launch_issue_to_pr', 'select_launch_route'),
 ('select_launch_route', 'record_dispatch_success'),
 ('select_launch_route', 'record_dispatch_failure'),
 ('select_launch_route', 'keep_busy_launch'),
 ('record_dispatch_success', 'select_dispatch_outcome'),
 ('record_dispatch_failure', 'select_dispatch_outcome'),
 ('select_dispatch_outcome', 'persist_dispatch_stuck'),
 ('select_dispatch_outcome', 'label_blocked_dispatch'),
 ('label_blocked_dispatch', 'persist_blocked_dispatch'),
 ('persist_blocked_dispatch', 'select_blocked_dispatch'),
 ('select_dispatch_outcome', 'select_blocked_dispatch'),
 ('select_blocked_dispatch', 'park_plan_only_dispatch'),
 ('select_dispatch_outcome', 'write_dispatch_receipt'),
 ('select_implementation_candidate', 'summarize_implementation_dispatch'),
 ('inspect_implementation_mutex', 'summarize_implementation_dispatch'),
 ('select_mutex_outcome', 'summarize_implementation_dispatch'),
 ('keep_implementation_candidate', 'summarize_implementation_dispatch'),
 ('verify_selected_issue_ready', 'summarize_implementation_dispatch'),
 ('select_ready_outcome', 'summarize_implementation_dispatch'),
 ('drop_stale_implementation_candidate', 'summarize_implementation_dispatch'),
 ('launch_issue_to_pr', 'summarize_implementation_dispatch'),
 ('select_launch_route', 'summarize_implementation_dispatch'),
 ('keep_busy_launch', 'summarize_implementation_dispatch'),
 ('record_dispatch_success', 'summarize_implementation_dispatch'),
 ('record_dispatch_failure', 'summarize_implementation_dispatch'),
 ('select_dispatch_outcome', 'summarize_implementation_dispatch'),
 ('persist_dispatch_stuck', 'summarize_implementation_dispatch'),
 ('label_blocked_dispatch', 'summarize_implementation_dispatch'),
 ('persist_blocked_dispatch', 'summarize_implementation_dispatch'),
 ('select_blocked_dispatch', 'summarize_implementation_dispatch'),
 ('park_plan_only_dispatch', 'summarize_implementation_dispatch'),
 ('write_dispatch_receipt', 'summarize_implementation_dispatch')]
_WHEN_BRANCHES = [('inspect_implementation_mutex',
  {'equals': 'candidate', 'path': 'route', 'upstream': 'select_implementation_candidate'}),
 ('keep_implementation_candidate', {'equals': 'keep', 'path': 'route', 'upstream': 'select_mutex_outcome'}),
 ('verify_selected_issue_ready', {'equals': 'free', 'path': 'route', 'upstream': 'select_mutex_outcome'}),
 ('drop_stale_implementation_candidate',
  {'equals': 'stale', 'path': 'route', 'upstream': 'select_ready_outcome'}),
 ('launch_issue_to_pr', {'equals': 'ready', 'path': 'route', 'upstream': 'select_ready_outcome'}),
 ('record_dispatch_success', {'equals': 'started', 'path': 'route', 'upstream': 'select_launch_route'}),
 ('record_dispatch_failure', {'equals': 'failed', 'path': 'route', 'upstream': 'select_launch_route'}),
 ('keep_busy_launch', {'equals': 'busy', 'path': 'route', 'upstream': 'select_launch_route'}),
 ('persist_dispatch_stuck', {'equals': True, 'path': 'stuck_changed', 'upstream': 'select_dispatch_outcome'}),
 ('label_blocked_dispatch', {'equals': 'blocked', 'path': 'route', 'upstream': 'select_dispatch_outcome'}),
 ('park_plan_only_dispatch', {'equals': 'park', 'path': 'route', 'upstream': 'select_blocked_dispatch'}),
 ('write_dispatch_receipt', {'equals': 'receipt', 'path': 'route', 'upstream': 'select_dispatch_outcome'})]
_EFFECTORS = [{'conduction': [], 'id': 'select_implementation_candidate', 'when': None},
 {'conduction': ['select_implementation_candidate'],
  'id': 'inspect_implementation_mutex',
  'when': {'equals': 'candidate', 'path': 'route', 'upstream': 'select_implementation_candidate'}},
 {'conduction': ['select_implementation_candidate', 'inspect_implementation_mutex'],
  'id': 'select_mutex_outcome',
  'when': None},
 {'conduction': ['select_mutex_outcome'],
  'id': 'keep_implementation_candidate',
  'when': {'equals': 'keep', 'path': 'route', 'upstream': 'select_mutex_outcome'}},
 {'conduction': ['select_mutex_outcome'],
  'id': 'verify_selected_issue_ready',
  'when': {'equals': 'free', 'path': 'route', 'upstream': 'select_mutex_outcome'}},
 {'conduction': ['select_mutex_outcome', 'verify_selected_issue_ready'],
  'id': 'select_ready_outcome',
  'when': None},
 {'conduction': ['select_ready_outcome'],
  'id': 'drop_stale_implementation_candidate',
  'when': {'equals': 'stale', 'path': 'route', 'upstream': 'select_ready_outcome'}},
 {'conduction': ['select_ready_outcome'],
  'id': 'launch_issue_to_pr',
  'when': {'equals': 'ready', 'path': 'route', 'upstream': 'select_ready_outcome'}},
 {'conduction': ['select_ready_outcome', 'launch_issue_to_pr'], 'id': 'select_launch_route', 'when': None},
 {'conduction': ['select_launch_route'],
  'id': 'record_dispatch_success',
  'when': {'equals': 'started', 'path': 'route', 'upstream': 'select_launch_route'}},
 {'conduction': ['select_launch_route'],
  'id': 'record_dispatch_failure',
  'when': {'equals': 'failed', 'path': 'route', 'upstream': 'select_launch_route'}},
 {'conduction': ['select_launch_route'],
  'id': 'keep_busy_launch',
  'when': {'equals': 'busy', 'path': 'route', 'upstream': 'select_launch_route'}},
 {'conduction': ['record_dispatch_success', 'record_dispatch_failure'],
  'id': 'select_dispatch_outcome',
  'when': None},
 {'conduction': ['select_dispatch_outcome'],
  'id': 'persist_dispatch_stuck',
  'when': {'equals': True, 'path': 'stuck_changed', 'upstream': 'select_dispatch_outcome'}},
 {'conduction': ['select_dispatch_outcome'],
  'id': 'label_blocked_dispatch',
  'when': {'equals': 'blocked', 'path': 'route', 'upstream': 'select_dispatch_outcome'}},
 {'conduction': ['label_blocked_dispatch'], 'id': 'persist_blocked_dispatch', 'when': None},
 {'conduction': ['persist_blocked_dispatch', 'select_dispatch_outcome'],
  'id': 'select_blocked_dispatch',
  'when': None},
 {'conduction': ['select_blocked_dispatch'],
  'id': 'park_plan_only_dispatch',
  'when': {'equals': 'park', 'path': 'route', 'upstream': 'select_blocked_dispatch'}},
 {'conduction': ['select_dispatch_outcome'],
  'id': 'write_dispatch_receipt',
  'when': {'equals': 'receipt', 'path': 'route', 'upstream': 'select_dispatch_outcome'}},
 {'conduction': ['select_implementation_candidate',
                 'inspect_implementation_mutex',
                 'select_mutex_outcome',
                 'keep_implementation_candidate',
                 'verify_selected_issue_ready',
                 'select_ready_outcome',
                 'drop_stale_implementation_candidate',
                 'launch_issue_to_pr',
                 'select_launch_route',
                 'keep_busy_launch',
                 'record_dispatch_success',
                 'record_dispatch_failure',
                 'select_dispatch_outcome',
                 'persist_dispatch_stuck',
                 'label_blocked_dispatch',
                 'persist_blocked_dispatch',
                 'select_blocked_dispatch',
                 'park_plan_only_dispatch',
                 'write_dispatch_receipt'],
  'id': 'summarize_implementation_dispatch',
  'when': None}]

def test_every_conduction_edge_is_declared():
    got = {(str(up), nid) for nid, meta in _NODES.items() for up in meta["conduction"]}
    assert got == set(tuple(edge) for edge in _COND_EDGES)

def test_every_when_branch_is_declared():
    got = {(nid, json.dumps(meta["when"], sort_keys=True)) for nid, meta in _NODES.items() if meta["when"]}
    want = {(nid, json.dumps(when, sort_keys=True)) for nid, when in _WHEN_BRANCHES}
    assert got == want

def test_when_upstream_is_a_direct_parent():
    for nid, when in _WHEN_BRANCHES:
        assert when["upstream"] in _NODES[nid]["conduction"]

def test_unconditional_nodes_succeed_without_outputs():
    from support.graph_model import run_model
    status = run_model(_EFFECTORS, {})
    for nid, meta in _NODES.items():
        if meta["when"] is None:
            assert status[nid] == "succeeded"

