"""Independent conduction and when metadata for issue_to_pr_delivery."""
from __future__ import annotations
import json

_PATH_ID = 'issue_to_pr_delivery'
_NODES = {'acceptance_repair_execution': {'atom': 'local_repair_execution',
                                 'conduction': ['get_issue',
                                                'worktree_add',
                                                'coding_execution',
                                                'commit_implementation',
                                                'verify_acceptance'],
                                 'when': {'equals': 'repair',
                                          'path': 'route',
                                          'upstream': 'verify_acceptance'}},
 'assert_implementation_diff': {'atom': 'assert_real_diff',
                                'conduction': ['worktree_add', 'coding_execution', 'relocalize_off_goal'],
                                'when': {'equals': 'implemented',
                                         'path': 'route',
                                         'upstream': 'coding_execution'}},
 'assert_real_diff': {'atom': 'assert_real_diff',
                      'conduction': ['worktree_add',
                                     'finalize_local_tests',
                                     'relocalize_off_goal',
                                     'verify_acceptance',
                                     'select_publish_gate'],
                      'when': {'equals': 'publish', 'path': 'route', 'upstream': 'select_publish_gate'}},
 'assert_stamps_committed': {'atom': 'assert_stamps_committed',
                             'conduction': ['worktree_add',
                                            'list_dirty_stamp_paths',
                                            'commit_stamp_files',
                                            'finalize_acceptance',
                                            'verify_acceptance'],
                             'when': {'equals': 'publish',
                                      'path': 'route',
                                      'upstream': 'finalize_acceptance'}},
 'assign_issue': {'atom': 'assign_issue',
                  'conduction': ['get_issue', 'resolve_implementation_issue'],
                  'when': {'equals': 'open', 'path': 'route', 'upstream': 'resolve_implementation_issue'}},
 'coding_execution': {'atom': 'coding_execution',
                      'conduction': ['get_issue',
                                     'make_branch',
                                     'worktree_add',
                                     'map_repo',
                                     'plan_issue',
                                     'localize',
                                     'cycle_start',
                                     'prepare_acceptance'],
                      'when': {'equals': 'ready', 'path': 'route', 'upstream': 'localize'}},
 'coding_repair_terminal': {'atom': 'coding_repair_terminal',
                            'conduction': ['finalize_local_tests'],
                            'when': {'equals': 'repair_terminal',
                                     'path': 'route',
                                     'upstream': 'finalize_local_tests'}},
 'commit_implementation': {'atom': 'commit_all',
                           'conduction': ['get_issue',
                                          'worktree_add',
                                          'coding_execution',
                                          'assert_implementation_diff'],
                           'when': {'equals': 'implemented',
                                    'path': 'route',
                                    'upstream': 'coding_execution'}},
 'commit_stamp_files': {'atom': 'commit_stamp_files',
                        'conduction': ['get_issue',
                                       'worktree_add',
                                       'list_dirty_stamp_paths',
                                       'verify_acceptance'],
                        'when': {'equals': 'dirty', 'path': 'route', 'upstream': 'list_dirty_stamp_paths'}},
 'cycle_end': {'atom': 'cycle_end', 'conduction': ['get_issue', 'pr_create', 'cycle_start'], 'when': None},
 'cycle_start': {'atom': 'cycle_start', 'conduction': ['get_issue', 'localize'], 'when': None},
 'finalize_acceptance': {'atom': 'finalize_acceptance',
                         'conduction': ['verify_acceptance',
                                        'acceptance_repair_execution',
                                        'verify_acceptance_recheck'],
                         'when': {'equals': True, 'path': 'ok', 'upstream': 'verify_acceptance'}},
 'finalize_local_tests': {'atom': 'finalize_local_tests',
                          'conduction': ['select_local_test', 'local_repair_execution', 'coding_execution'],
                          'when': None},
 'get_issue': {'atom': 'get_issue', 'conduction': [], 'when': None},
 'list_dirty_stamp_paths': {'atom': 'list_dirty_stamp_paths',
                            'conduction': ['worktree_add',
                                           'finalize_local_tests',
                                           'finalize_acceptance',
                                           'verify_acceptance',
                                           'local_repair_execution',
                                           'commit_implementation'],
                            'when': {'equals': 'publish',
                                     'path': 'route',
                                     'upstream': 'finalize_acceptance'}},
 'list_prs': {'atom': 'list_prs', 'conduction': ['get_issue', 'pr_create', 'stage_pr_open'], 'when': None},
 'local_repair_execution': {'atom': 'local_repair_execution',
                            'conduction': ['get_issue',
                                           'worktree_add',
                                           'coding_execution',
                                           'commit_implementation',
                                           'test_local_execution',
                                           'select_local_test'],
                            'when': {'equals': 'fail', 'path': 'route', 'upstream': 'select_local_test'}},
 'local_verification_terminal': {'atom': 'local_verification_terminal',
                                 'conduction': ['finalize_local_tests'],
                                 'when': None},
 'localize': {'atom': 'localize',
              'conduction': ['get_issue', 'make_branch', 'worktree_add', 'map_repo', 'plan_issue'],
              'when': {'equals': 'ready', 'path': 'route', 'upstream': 'worktree_add'}},
 'make_branch': {'atom': 'make_branch',
                 'conduction': ['get_issue', 'resolve_implementation_issue'],
                 'when': {'equals': 'open', 'path': 'route', 'upstream': 'resolve_implementation_issue'}},
 'map_repo': {'atom': 'map_repo',
              'conduction': ['get_issue', 'worktree_add'],
              'when': {'equals': 'ready', 'path': 'route', 'upstream': 'worktree_add'}},
 'plan_issue': {'atom': 'plan_issue',
                'conduction': ['get_issue', 'make_branch', 'worktree_add', 'map_repo'],
                'when': {'equals': 'ready', 'path': 'route', 'upstream': 'worktree_add'}},
 'pr_create': {'atom': 'pr_create',
               'conduction': ['get_issue',
                              'make_branch',
                              'coding_execution',
                              'finalize_local_tests',
                              'assert_real_diff',
                              'push',
                              'finalize_acceptance',
                              'verify_acceptance',
                              'assert_stamps_committed',
                              'select_publish_gate'],
               'when': {'equals': 'publish', 'path': 'route', 'upstream': 'select_publish_gate'}},
 'pr_label': {'atom': 'pr_label', 'conduction': ['get_issue', 'list_prs', 'pr_create'], 'when': None},
 'prepare_acceptance': {'atom': 'prepare_acceptance',
                        'conduction': ['get_issue', 'worktree_add', 'plan_issue', 'localize'],
                        'when': {'equals': 'ready', 'path': 'route', 'upstream': 'localize'}},
 'push': {'atom': 'push',
          'conduction': ['make_branch',
                         'worktree_add',
                         'commit_implementation',
                         'local_repair_execution',
                         'finalize_local_tests',
                         'finalize_acceptance',
                         'verify_acceptance',
                         'assert_stamps_committed',
                         'select_publish_gate',
                         'assert_real_diff'],
          'when': {'equals': 'publish', 'path': 'route', 'upstream': 'select_publish_gate'}},
 'rebase_onto_base': {'atom': 'rebase_onto_base',
                      'conduction': ['worktree_add', 'commit_implementation', 'coding_execution'],
                      'when': {'equals': 'implemented', 'path': 'route', 'upstream': 'coding_execution'}},
 'relocalize_off_goal': {'atom': 'relocalize_off_goal',
                         'conduction': ['worktree_add', 'localize', 'coding_execution'],
                         'when': {'equals': 'implemented', 'path': 'route', 'upstream': 'coding_execution'}},
 'resolve_implementation_issue': {'atom': 'resolve_implementation_issue',
                                  'conduction': ['get_issue'],
                                  'when': None},
 'select_local_test': {'atom': 'select_local_test',
                       'conduction': ['test_local_execution', 'coding_execution'],
                       'when': None},
 'select_publish_gate': {'atom': 'select_publish_gate',
                         'conduction': ['finalize_local_tests',
                                        'local_verification_terminal',
                                        'finalize_acceptance',
                                        'verify_acceptance',
                                        'assert_stamps_committed'],
                         'when': {'equals': 'publish',
                                  'path': 'route',
                                  'upstream': 'assert_stamps_committed'}},
 'stage_implementing': {'atom': 'stage_label',
                        'conduction': ['get_issue', 'resolve_implementation_issue'],
                        'when': {'equals': 'open',
                                 'path': 'route',
                                 'upstream': 'resolve_implementation_issue'}},
 'stage_pr_open': {'atom': 'stage_label', 'conduction': ['get_issue', 'pr_create'], 'when': None},
 'summarize_issue_delivery': {'atom': 'summarize_issue_delivery',
                              'conduction': ['make_branch',
                                             'coding_execution',
                                             'finalize_local_tests',
                                             'finalize_acceptance',
                                             'verify_acceptance',
                                             'pr_create',
                                             'pr_label'],
                              'when': None},
 'test_local_execution': {'atom': 'test_local_execution',
                          'conduction': ['worktree_add',
                                         'commit_implementation',
                                         'rebase_onto_base',
                                         'coding_execution'],
                          'when': {'equals': 'implemented', 'path': 'route', 'upstream': 'coding_execution'}},
 'verify_acceptance': {'atom': 'verify_acceptance',
                       'conduction': ['prepare_acceptance',
                                      'worktree_add',
                                      'finalize_local_tests',
                                      'test_local_execution',
                                      'local_repair_execution'],
                       'when': {'equals': 'publish', 'path': 'route', 'upstream': 'finalize_local_tests'}},
 'verify_acceptance_recheck': {'atom': 'verify_acceptance_recheck',
                               'conduction': ['prepare_acceptance',
                                              'worktree_add',
                                              'verify_acceptance',
                                              'acceptance_repair_execution',
                                              'test_local_execution'],
                               'when': {'equals': True,
                                        'path': 'ok',
                                        'upstream': 'acceptance_repair_execution'}},
 'worktree_add': {'atom': 'worktree_add',
                  'conduction': ['get_issue', 'make_branch', 'assign_issue', 'stage_implementing'],
                  'when': None}}
_COND_EDGES = [('get_issue', 'resolve_implementation_issue'),
 ('get_issue', 'assign_issue'),
 ('resolve_implementation_issue', 'assign_issue'),
 ('get_issue', 'stage_implementing'),
 ('resolve_implementation_issue', 'stage_implementing'),
 ('get_issue', 'make_branch'),
 ('resolve_implementation_issue', 'make_branch'),
 ('get_issue', 'worktree_add'),
 ('make_branch', 'worktree_add'),
 ('assign_issue', 'worktree_add'),
 ('stage_implementing', 'worktree_add'),
 ('get_issue', 'map_repo'),
 ('worktree_add', 'map_repo'),
 ('get_issue', 'plan_issue'),
 ('make_branch', 'plan_issue'),
 ('worktree_add', 'plan_issue'),
 ('map_repo', 'plan_issue'),
 ('get_issue', 'localize'),
 ('make_branch', 'localize'),
 ('worktree_add', 'localize'),
 ('map_repo', 'localize'),
 ('plan_issue', 'localize'),
 ('get_issue', 'cycle_start'),
 ('localize', 'cycle_start'),
 ('get_issue', 'prepare_acceptance'),
 ('worktree_add', 'prepare_acceptance'),
 ('plan_issue', 'prepare_acceptance'),
 ('localize', 'prepare_acceptance'),
 ('get_issue', 'coding_execution'),
 ('make_branch', 'coding_execution'),
 ('worktree_add', 'coding_execution'),
 ('map_repo', 'coding_execution'),
 ('plan_issue', 'coding_execution'),
 ('localize', 'coding_execution'),
 ('cycle_start', 'coding_execution'),
 ('prepare_acceptance', 'coding_execution'),
 ('worktree_add', 'relocalize_off_goal'),
 ('localize', 'relocalize_off_goal'),
 ('coding_execution', 'relocalize_off_goal'),
 ('worktree_add', 'assert_implementation_diff'),
 ('coding_execution', 'assert_implementation_diff'),
 ('relocalize_off_goal', 'assert_implementation_diff'),
 ('get_issue', 'commit_implementation'),
 ('worktree_add', 'commit_implementation'),
 ('coding_execution', 'commit_implementation'),
 ('assert_implementation_diff', 'commit_implementation'),
 ('worktree_add', 'rebase_onto_base'),
 ('commit_implementation', 'rebase_onto_base'),
 ('coding_execution', 'rebase_onto_base'),
 ('worktree_add', 'test_local_execution'),
 ('commit_implementation', 'test_local_execution'),
 ('rebase_onto_base', 'test_local_execution'),
 ('coding_execution', 'test_local_execution'),
 ('test_local_execution', 'select_local_test'),
 ('coding_execution', 'select_local_test'),
 ('get_issue', 'local_repair_execution'),
 ('worktree_add', 'local_repair_execution'),
 ('coding_execution', 'local_repair_execution'),
 ('commit_implementation', 'local_repair_execution'),
 ('test_local_execution', 'local_repair_execution'),
 ('select_local_test', 'local_repair_execution'),
 ('select_local_test', 'finalize_local_tests'),
 ('local_repair_execution', 'finalize_local_tests'),
 ('coding_execution', 'finalize_local_tests'),
 ('finalize_local_tests', 'local_verification_terminal'),
 ('finalize_local_tests', 'coding_repair_terminal'),
 ('prepare_acceptance', 'verify_acceptance'),
 ('worktree_add', 'verify_acceptance'),
 ('finalize_local_tests', 'verify_acceptance'),
 ('test_local_execution', 'verify_acceptance'),
 ('local_repair_execution', 'verify_acceptance'),
 ('get_issue', 'acceptance_repair_execution'),
 ('worktree_add', 'acceptance_repair_execution'),
 ('coding_execution', 'acceptance_repair_execution'),
 ('commit_implementation', 'acceptance_repair_execution'),
 ('verify_acceptance', 'acceptance_repair_execution'),
 ('prepare_acceptance', 'verify_acceptance_recheck'),
 ('worktree_add', 'verify_acceptance_recheck'),
 ('verify_acceptance', 'verify_acceptance_recheck'),
 ('acceptance_repair_execution', 'verify_acceptance_recheck'),
 ('test_local_execution', 'verify_acceptance_recheck'),
 ('verify_acceptance', 'finalize_acceptance'),
 ('acceptance_repair_execution', 'finalize_acceptance'),
 ('verify_acceptance_recheck', 'finalize_acceptance'),
 ('worktree_add', 'list_dirty_stamp_paths'),
 ('finalize_local_tests', 'list_dirty_stamp_paths'),
 ('finalize_acceptance', 'list_dirty_stamp_paths'),
 ('verify_acceptance', 'list_dirty_stamp_paths'),
 ('local_repair_execution', 'list_dirty_stamp_paths'),
 ('commit_implementation', 'list_dirty_stamp_paths'),
 ('get_issue', 'commit_stamp_files'),
 ('worktree_add', 'commit_stamp_files'),
 ('list_dirty_stamp_paths', 'commit_stamp_files'),
 ('verify_acceptance', 'commit_stamp_files'),
 ('worktree_add', 'assert_stamps_committed'),
 ('list_dirty_stamp_paths', 'assert_stamps_committed'),
 ('commit_stamp_files', 'assert_stamps_committed'),
 ('finalize_acceptance', 'assert_stamps_committed'),
 ('verify_acceptance', 'assert_stamps_committed'),
 ('finalize_local_tests', 'select_publish_gate'),
 ('local_verification_terminal', 'select_publish_gate'),
 ('finalize_acceptance', 'select_publish_gate'),
 ('verify_acceptance', 'select_publish_gate'),
 ('assert_stamps_committed', 'select_publish_gate'),
 ('worktree_add', 'assert_real_diff'),
 ('finalize_local_tests', 'assert_real_diff'),
 ('relocalize_off_goal', 'assert_real_diff'),
 ('verify_acceptance', 'assert_real_diff'),
 ('select_publish_gate', 'assert_real_diff'),
 ('make_branch', 'push'),
 ('worktree_add', 'push'),
 ('commit_implementation', 'push'),
 ('local_repair_execution', 'push'),
 ('finalize_local_tests', 'push'),
 ('finalize_acceptance', 'push'),
 ('verify_acceptance', 'push'),
 ('assert_stamps_committed', 'push'),
 ('select_publish_gate', 'push'),
 ('assert_real_diff', 'push'),
 ('get_issue', 'pr_create'),
 ('make_branch', 'pr_create'),
 ('coding_execution', 'pr_create'),
 ('finalize_local_tests', 'pr_create'),
 ('assert_real_diff', 'pr_create'),
 ('push', 'pr_create'),
 ('finalize_acceptance', 'pr_create'),
 ('verify_acceptance', 'pr_create'),
 ('assert_stamps_committed', 'pr_create'),
 ('select_publish_gate', 'pr_create'),
 ('get_issue', 'cycle_end'),
 ('pr_create', 'cycle_end'),
 ('cycle_start', 'cycle_end'),
 ('get_issue', 'stage_pr_open'),
 ('pr_create', 'stage_pr_open'),
 ('get_issue', 'list_prs'),
 ('pr_create', 'list_prs'),
 ('stage_pr_open', 'list_prs'),
 ('get_issue', 'pr_label'),
 ('list_prs', 'pr_label'),
 ('pr_create', 'pr_label'),
 ('make_branch', 'summarize_issue_delivery'),
 ('coding_execution', 'summarize_issue_delivery'),
 ('finalize_local_tests', 'summarize_issue_delivery'),
 ('finalize_acceptance', 'summarize_issue_delivery'),
 ('verify_acceptance', 'summarize_issue_delivery'),
 ('pr_create', 'summarize_issue_delivery'),
 ('pr_label', 'summarize_issue_delivery')]
_WHEN_BRANCHES = [('assign_issue', {'equals': 'open', 'path': 'route', 'upstream': 'resolve_implementation_issue'}),
 ('stage_implementing', {'equals': 'open', 'path': 'route', 'upstream': 'resolve_implementation_issue'}),
 ('make_branch', {'equals': 'open', 'path': 'route', 'upstream': 'resolve_implementation_issue'}),
 ('map_repo', {'equals': 'ready', 'path': 'route', 'upstream': 'worktree_add'}),
 ('plan_issue', {'equals': 'ready', 'path': 'route', 'upstream': 'worktree_add'}),
 ('localize', {'equals': 'ready', 'path': 'route', 'upstream': 'worktree_add'}),
 ('prepare_acceptance', {'equals': 'ready', 'path': 'route', 'upstream': 'localize'}),
 ('coding_execution', {'equals': 'ready', 'path': 'route', 'upstream': 'localize'}),
 ('relocalize_off_goal', {'equals': 'implemented', 'path': 'route', 'upstream': 'coding_execution'}),
 ('assert_implementation_diff', {'equals': 'implemented', 'path': 'route', 'upstream': 'coding_execution'}),
 ('commit_implementation', {'equals': 'implemented', 'path': 'route', 'upstream': 'coding_execution'}),
 ('rebase_onto_base', {'equals': 'implemented', 'path': 'route', 'upstream': 'coding_execution'}),
 ('test_local_execution', {'equals': 'implemented', 'path': 'route', 'upstream': 'coding_execution'}),
 ('local_repair_execution', {'equals': 'fail', 'path': 'route', 'upstream': 'select_local_test'}),
 ('coding_repair_terminal',
  {'equals': 'repair_terminal', 'path': 'route', 'upstream': 'finalize_local_tests'}),
 ('verify_acceptance', {'equals': 'publish', 'path': 'route', 'upstream': 'finalize_local_tests'}),
 ('acceptance_repair_execution', {'equals': 'repair', 'path': 'route', 'upstream': 'verify_acceptance'}),
 ('verify_acceptance_recheck', {'equals': True, 'path': 'ok', 'upstream': 'acceptance_repair_execution'}),
 ('finalize_acceptance', {'equals': True, 'path': 'ok', 'upstream': 'verify_acceptance'}),
 ('list_dirty_stamp_paths', {'equals': 'publish', 'path': 'route', 'upstream': 'finalize_acceptance'}),
 ('commit_stamp_files', {'equals': 'dirty', 'path': 'route', 'upstream': 'list_dirty_stamp_paths'}),
 ('assert_stamps_committed', {'equals': 'publish', 'path': 'route', 'upstream': 'finalize_acceptance'}),
 ('select_publish_gate', {'equals': 'publish', 'path': 'route', 'upstream': 'assert_stamps_committed'}),
 ('assert_real_diff', {'equals': 'publish', 'path': 'route', 'upstream': 'select_publish_gate'}),
 ('push', {'equals': 'publish', 'path': 'route', 'upstream': 'select_publish_gate'}),
 ('pr_create', {'equals': 'publish', 'path': 'route', 'upstream': 'select_publish_gate'})]
_EFFECTORS = [{'conduction': [], 'id': 'get_issue', 'when': None},
 {'conduction': ['get_issue'], 'id': 'resolve_implementation_issue', 'when': None},
 {'conduction': ['get_issue', 'resolve_implementation_issue'],
  'id': 'assign_issue',
  'when': {'equals': 'open', 'path': 'route', 'upstream': 'resolve_implementation_issue'}},
 {'conduction': ['get_issue', 'resolve_implementation_issue'],
  'id': 'stage_implementing',
  'when': {'equals': 'open', 'path': 'route', 'upstream': 'resolve_implementation_issue'}},
 {'conduction': ['get_issue', 'resolve_implementation_issue'],
  'id': 'make_branch',
  'when': {'equals': 'open', 'path': 'route', 'upstream': 'resolve_implementation_issue'}},
 {'conduction': ['get_issue', 'make_branch', 'assign_issue', 'stage_implementing'],
  'id': 'worktree_add',
  'when': None},
 {'conduction': ['get_issue', 'worktree_add'],
  'id': 'map_repo',
  'when': {'equals': 'ready', 'path': 'route', 'upstream': 'worktree_add'}},
 {'conduction': ['get_issue', 'make_branch', 'worktree_add', 'map_repo'],
  'id': 'plan_issue',
  'when': {'equals': 'ready', 'path': 'route', 'upstream': 'worktree_add'}},
 {'conduction': ['get_issue', 'make_branch', 'worktree_add', 'map_repo', 'plan_issue'],
  'id': 'localize',
  'when': {'equals': 'ready', 'path': 'route', 'upstream': 'worktree_add'}},
 {'conduction': ['get_issue', 'localize'], 'id': 'cycle_start', 'when': None},
 {'conduction': ['get_issue', 'worktree_add', 'plan_issue', 'localize'],
  'id': 'prepare_acceptance',
  'when': {'equals': 'ready', 'path': 'route', 'upstream': 'localize'}},
 {'conduction': ['get_issue',
                 'make_branch',
                 'worktree_add',
                 'map_repo',
                 'plan_issue',
                 'localize',
                 'cycle_start',
                 'prepare_acceptance'],
  'id': 'coding_execution',
  'when': {'equals': 'ready', 'path': 'route', 'upstream': 'localize'}},
 {'conduction': ['worktree_add', 'localize', 'coding_execution'],
  'id': 'relocalize_off_goal',
  'when': {'equals': 'implemented', 'path': 'route', 'upstream': 'coding_execution'}},
 {'conduction': ['worktree_add', 'coding_execution', 'relocalize_off_goal'],
  'id': 'assert_implementation_diff',
  'when': {'equals': 'implemented', 'path': 'route', 'upstream': 'coding_execution'}},
 {'conduction': ['get_issue', 'worktree_add', 'coding_execution', 'assert_implementation_diff'],
  'id': 'commit_implementation',
  'when': {'equals': 'implemented', 'path': 'route', 'upstream': 'coding_execution'}},
 {'conduction': ['worktree_add', 'commit_implementation', 'coding_execution'],
  'id': 'rebase_onto_base',
  'when': {'equals': 'implemented', 'path': 'route', 'upstream': 'coding_execution'}},
 {'conduction': ['worktree_add', 'commit_implementation', 'rebase_onto_base', 'coding_execution'],
  'id': 'test_local_execution',
  'when': {'equals': 'implemented', 'path': 'route', 'upstream': 'coding_execution'}},
 {'conduction': ['test_local_execution', 'coding_execution'], 'id': 'select_local_test', 'when': None},
 {'conduction': ['get_issue',
                 'worktree_add',
                 'coding_execution',
                 'commit_implementation',
                 'test_local_execution',
                 'select_local_test'],
  'id': 'local_repair_execution',
  'when': {'equals': 'fail', 'path': 'route', 'upstream': 'select_local_test'}},
 {'conduction': ['select_local_test', 'local_repair_execution', 'coding_execution'],
  'id': 'finalize_local_tests',
  'when': None},
 {'conduction': ['finalize_local_tests'], 'id': 'local_verification_terminal', 'when': None},
 {'conduction': ['finalize_local_tests'],
  'id': 'coding_repair_terminal',
  'when': {'equals': 'repair_terminal', 'path': 'route', 'upstream': 'finalize_local_tests'}},
 {'conduction': ['prepare_acceptance',
                 'worktree_add',
                 'finalize_local_tests',
                 'test_local_execution',
                 'local_repair_execution'],
  'id': 'verify_acceptance',
  'when': {'equals': 'publish', 'path': 'route', 'upstream': 'finalize_local_tests'}},
 {'conduction': ['get_issue',
                 'worktree_add',
                 'coding_execution',
                 'commit_implementation',
                 'verify_acceptance'],
  'id': 'acceptance_repair_execution',
  'when': {'equals': 'repair', 'path': 'route', 'upstream': 'verify_acceptance'}},
 {'conduction': ['prepare_acceptance',
                 'worktree_add',
                 'verify_acceptance',
                 'acceptance_repair_execution',
                 'test_local_execution'],
  'id': 'verify_acceptance_recheck',
  'when': {'equals': True, 'path': 'ok', 'upstream': 'acceptance_repair_execution'}},
 {'conduction': ['verify_acceptance', 'acceptance_repair_execution', 'verify_acceptance_recheck'],
  'id': 'finalize_acceptance',
  'when': {'equals': True, 'path': 'ok', 'upstream': 'verify_acceptance'}},
 {'conduction': ['worktree_add',
                 'finalize_local_tests',
                 'finalize_acceptance',
                 'verify_acceptance',
                 'local_repair_execution',
                 'commit_implementation'],
  'id': 'list_dirty_stamp_paths',
  'when': {'equals': 'publish', 'path': 'route', 'upstream': 'finalize_acceptance'}},
 {'conduction': ['get_issue', 'worktree_add', 'list_dirty_stamp_paths', 'verify_acceptance'],
  'id': 'commit_stamp_files',
  'when': {'equals': 'dirty', 'path': 'route', 'upstream': 'list_dirty_stamp_paths'}},
 {'conduction': ['worktree_add',
                 'list_dirty_stamp_paths',
                 'commit_stamp_files',
                 'finalize_acceptance',
                 'verify_acceptance'],
  'id': 'assert_stamps_committed',
  'when': {'equals': 'publish', 'path': 'route', 'upstream': 'finalize_acceptance'}},
 {'conduction': ['finalize_local_tests',
                 'local_verification_terminal',
                 'finalize_acceptance',
                 'verify_acceptance',
                 'assert_stamps_committed'],
  'id': 'select_publish_gate',
  'when': {'equals': 'publish', 'path': 'route', 'upstream': 'assert_stamps_committed'}},
 {'conduction': ['worktree_add',
                 'finalize_local_tests',
                 'relocalize_off_goal',
                 'verify_acceptance',
                 'select_publish_gate'],
  'id': 'assert_real_diff',
  'when': {'equals': 'publish', 'path': 'route', 'upstream': 'select_publish_gate'}},
 {'conduction': ['make_branch',
                 'worktree_add',
                 'commit_implementation',
                 'local_repair_execution',
                 'finalize_local_tests',
                 'finalize_acceptance',
                 'verify_acceptance',
                 'assert_stamps_committed',
                 'select_publish_gate',
                 'assert_real_diff'],
  'id': 'push',
  'when': {'equals': 'publish', 'path': 'route', 'upstream': 'select_publish_gate'}},
 {'conduction': ['get_issue',
                 'make_branch',
                 'coding_execution',
                 'finalize_local_tests',
                 'assert_real_diff',
                 'push',
                 'finalize_acceptance',
                 'verify_acceptance',
                 'assert_stamps_committed',
                 'select_publish_gate'],
  'id': 'pr_create',
  'when': {'equals': 'publish', 'path': 'route', 'upstream': 'select_publish_gate'}},
 {'conduction': ['get_issue', 'pr_create', 'cycle_start'], 'id': 'cycle_end', 'when': None},
 {'conduction': ['get_issue', 'pr_create'], 'id': 'stage_pr_open', 'when': None},
 {'conduction': ['get_issue', 'pr_create', 'stage_pr_open'], 'id': 'list_prs', 'when': None},
 {'conduction': ['get_issue', 'list_prs', 'pr_create'], 'id': 'pr_label', 'when': None},
 {'conduction': ['make_branch',
                 'coding_execution',
                 'finalize_local_tests',
                 'finalize_acceptance',
                 'verify_acceptance',
                 'pr_create',
                 'pr_label'],
  'id': 'summarize_issue_delivery',
  'when': None}]

def test_every_conduction_edge_is_declared():
    got = {(str(up), nid) for nid, meta in _NODES.items() for up in meta["conduction"]}
    assert got == set(tuple(edge) for edge in _COND_EDGES)

def test_every_when_branch_is_declared():
    got = {(nid, json.dumps(meta["when"], sort_keys=True)) for nid, meta in _NODES.items() if meta["when"]}
    want = {(nid, json.dumps(when, sort_keys=True)) for nid, when in _WHEN_BRANCHES}
    assert got == want

def test_when_upstream_is_a_direct_parent():
    for nid, when in _WHEN_BRANCHES:
        assert when["upstream"] in _NODES[nid]["conduction"]

def test_unconditional_nodes_succeed_without_outputs():
    from support.graph_model import run_model
    status = run_model(_EFFECTORS, {})
    for nid, meta in _NODES.items():
        if meta["when"] is None:
            assert status[nid] == "succeeded"

