"""Independent conduction and when metadata for factory_pass."""
from __future__ import annotations
import json

_PATH_ID = 'factory_pass'
_NODES = {'factory_begin': {'atom': 'factory_begin',
                   'conduction': ['factory_begin_host_gate'],
                   'when': {'equals': 'begin', 'path': 'route', 'upstream': 'factory_begin_host_gate'}},
 'factory_begin_host_gate': {'atom': 'factory_begin_host_gate', 'conduction': ['host_ff'], 'when': None},
 'factory_pass_terminal': {'atom': 'factory_pass_terminal', 'conduction': ['record_pass'], 'when': None},
 'harvest_factory_children': {'atom': 'harvest_factory_children', 'conduction': [], 'when': None},
 'host_ff': {'atom': 'host_ff', 'conduction': ['harvest_factory_children'], 'when': None},
 'reap_stale_worktrees': {'atom': 'reap_stale_worktrees',
                          'conduction': ['factory_begin_host_gate', 'factory_begin'],
                          'when': None},
 'record_pass': {'atom': 'record_pass',
                 'conduction': ['factory_begin_host_gate',
                                'factory_begin',
                                'select_self_repair_department',
                                'select_issue_triage_department',
                                'select_executor_department',
                                'select_pr_triage_department',
                                'select_pr_repair_department',
                                'run_self_repair_department',
                                'run_issue_triage_department',
                                'run_executor_department',
                                'run_pr_triage_department',
                                'run_pr_repair_department'],
                 'when': None},
 'run_executor_department': {'atom': 'run_executor_department',
                             'conduction': ['select_executor_department',
                                            'factory_begin',
                                            'run_issue_triage_department',
                                            'select_issue_triage_department'],
                             'when': {'equals': 'run',
                                      'path': 'route',
                                      'upstream': 'select_executor_department'}},
 'run_issue_triage_department': {'atom': 'run_issue_triage_department',
                                 'conduction': ['select_issue_triage_department', 'factory_begin'],
                                 'when': {'equals': 'run',
                                          'path': 'route',
                                          'upstream': 'select_issue_triage_department'}},
 'run_pr_repair_department': {'atom': 'run_pr_repair_department',
                              'conduction': ['select_pr_repair_department'],
                              'when': {'equals': 'repair',
                                       'path': 'route',
                                       'upstream': 'select_pr_repair_department'}},
 'run_pr_triage_department': {'atom': 'run_pr_triage_department',
                              'conduction': ['select_pr_triage_department'],
                              'when': {'equals': 'run',
                                       'path': 'route',
                                       'upstream': 'select_pr_triage_department'}},
 'run_self_repair_department': {'atom': 'run_self_repair_department',
                                'conduction': ['select_self_repair_department'],
                                'when': {'equals': 'run',
                                         'path': 'route',
                                         'upstream': 'select_self_repair_department'}},
 'select_executor_department': {'atom': 'select_executor_department',
                                'conduction': ['factory_begin_host_gate',
                                               'factory_begin',
                                               'select_issue_triage_department',
                                               'run_issue_triage_department'],
                                'when': None},
 'select_issue_triage_department': {'atom': 'select_issue_triage_department',
                                    'conduction': ['factory_begin_host_gate',
                                                   'factory_begin',
                                                   'select_self_repair_department'],
                                    'when': None},
 'select_pr_repair_department': {'atom': 'select_pr_repair_department',
                                 'conduction': ['factory_begin_host_gate',
                                                'factory_begin',
                                                'select_pr_triage_department',
                                                'run_pr_triage_department'],
                                 'when': None},
 'select_pr_triage_department': {'atom': 'select_pr_triage_department',
                                 'conduction': ['factory_begin_host_gate',
                                                'factory_begin',
                                                'select_executor_department'],
                                 'when': None},
 'select_self_repair_department': {'atom': 'select_self_repair_department',
                                   'conduction': ['factory_begin_host_gate', 'factory_begin'],
                                   'when': None}}
_COND_EDGES = [('harvest_factory_children', 'host_ff'),
 ('host_ff', 'factory_begin_host_gate'),
 ('factory_begin_host_gate', 'factory_begin'),
 ('factory_begin_host_gate', 'select_self_repair_department'),
 ('factory_begin', 'select_self_repair_department'),
 ('select_self_repair_department', 'run_self_repair_department'),
 ('factory_begin_host_gate', 'select_issue_triage_department'),
 ('factory_begin', 'select_issue_triage_department'),
 ('select_self_repair_department', 'select_issue_triage_department'),
 ('select_issue_triage_department', 'run_issue_triage_department'),
 ('factory_begin', 'run_issue_triage_department'),
 ('factory_begin_host_gate', 'select_executor_department'),
 ('factory_begin', 'select_executor_department'),
 ('select_issue_triage_department', 'select_executor_department'),
 ('run_issue_triage_department', 'select_executor_department'),
 ('select_executor_department', 'run_executor_department'),
 ('factory_begin', 'run_executor_department'),
 ('run_issue_triage_department', 'run_executor_department'),
 ('select_issue_triage_department', 'run_executor_department'),
 ('factory_begin_host_gate', 'select_pr_triage_department'),
 ('factory_begin', 'select_pr_triage_department'),
 ('select_executor_department', 'select_pr_triage_department'),
 ('select_pr_triage_department', 'run_pr_triage_department'),
 ('factory_begin_host_gate', 'select_pr_repair_department'),
 ('factory_begin', 'select_pr_repair_department'),
 ('select_pr_triage_department', 'select_pr_repair_department'),
 ('run_pr_triage_department', 'select_pr_repair_department'),
 ('select_pr_repair_department', 'run_pr_repair_department'),
 ('factory_begin_host_gate', 'record_pass'),
 ('factory_begin', 'record_pass'),
 ('select_self_repair_department', 'record_pass'),
 ('select_issue_triage_department', 'record_pass'),
 ('select_executor_department', 'record_pass'),
 ('select_pr_triage_department', 'record_pass'),
 ('select_pr_repair_department', 'record_pass'),
 ('run_self_repair_department', 'record_pass'),
 ('run_issue_triage_department', 'record_pass'),
 ('run_executor_department', 'record_pass'),
 ('run_pr_triage_department', 'record_pass'),
 ('run_pr_repair_department', 'record_pass'),
 ('record_pass', 'factory_pass_terminal'),
 ('factory_begin_host_gate', 'reap_stale_worktrees'),
 ('factory_begin', 'reap_stale_worktrees')]
_WHEN_BRANCHES = [('factory_begin', {'equals': 'begin', 'path': 'route', 'upstream': 'factory_begin_host_gate'}),
 ('run_self_repair_department',
  {'equals': 'run', 'path': 'route', 'upstream': 'select_self_repair_department'}),
 ('run_issue_triage_department',
  {'equals': 'run', 'path': 'route', 'upstream': 'select_issue_triage_department'}),
 ('run_executor_department', {'equals': 'run', 'path': 'route', 'upstream': 'select_executor_department'}),
 ('run_pr_triage_department', {'equals': 'run', 'path': 'route', 'upstream': 'select_pr_triage_department'}),
 ('run_pr_repair_department',
  {'equals': 'repair', 'path': 'route', 'upstream': 'select_pr_repair_department'})]
_EFFECTORS = [{'conduction': [], 'id': 'harvest_factory_children', 'when': None},
 {'conduction': ['harvest_factory_children'], 'id': 'host_ff', 'when': None},
 {'conduction': ['host_ff'], 'id': 'factory_begin_host_gate', 'when': None},
 {'conduction': ['factory_begin_host_gate'],
  'id': 'factory_begin',
  'when': {'equals': 'begin', 'path': 'route', 'upstream': 'factory_begin_host_gate'}},
 {'conduction': ['factory_begin_host_gate', 'factory_begin'],
  'id': 'select_self_repair_department',
  'when': None},
 {'conduction': ['select_self_repair_department'],
  'id': 'run_self_repair_department',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_self_repair_department'}},
 {'conduction': ['factory_begin_host_gate', 'factory_begin', 'select_self_repair_department'],
  'id': 'select_issue_triage_department',
  'when': None},
 {'conduction': ['select_issue_triage_department', 'factory_begin'],
  'id': 'run_issue_triage_department',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_issue_triage_department'}},
 {'conduction': ['factory_begin_host_gate',
                 'factory_begin',
                 'select_issue_triage_department',
                 'run_issue_triage_department'],
  'id': 'select_executor_department',
  'when': None},
 {'conduction': ['select_executor_department',
                 'factory_begin',
                 'run_issue_triage_department',
                 'select_issue_triage_department'],
  'id': 'run_executor_department',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_executor_department'}},
 {'conduction': ['factory_begin_host_gate', 'factory_begin', 'select_executor_department'],
  'id': 'select_pr_triage_department',
  'when': None},
 {'conduction': ['select_pr_triage_department'],
  'id': 'run_pr_triage_department',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_pr_triage_department'}},
 {'conduction': ['factory_begin_host_gate',
                 'factory_begin',
                 'select_pr_triage_department',
                 'run_pr_triage_department'],
  'id': 'select_pr_repair_department',
  'when': None},
 {'conduction': ['select_pr_repair_department'],
  'id': 'run_pr_repair_department',
  'when': {'equals': 'repair', 'path': 'route', 'upstream': 'select_pr_repair_department'}},
 {'conduction': ['factory_begin_host_gate',
                 'factory_begin',
                 'select_self_repair_department',
                 'select_issue_triage_department',
                 'select_executor_department',
                 'select_pr_triage_department',
                 'select_pr_repair_department',
                 'run_self_repair_department',
                 'run_issue_triage_department',
                 'run_executor_department',
                 'run_pr_triage_department',
                 'run_pr_repair_department'],
  'id': 'record_pass',
  'when': None},
 {'conduction': ['record_pass'], 'id': 'factory_pass_terminal', 'when': None},
 {'conduction': ['factory_begin_host_gate', 'factory_begin'], 'id': 'reap_stale_worktrees', 'when': None}]

def test_every_conduction_edge_is_declared():
    got = {(str(up), nid) for nid, meta in _NODES.items() for up in meta["conduction"]}
    assert got == set(tuple(edge) for edge in _COND_EDGES)

def test_every_when_branch_is_declared():
    got = {(nid, json.dumps(meta["when"], sort_keys=True)) for nid, meta in _NODES.items() if meta["when"]}
    want = {(nid, json.dumps(when, sort_keys=True)) for nid, when in _WHEN_BRANCHES}
    assert got == want

def test_when_upstream_is_a_direct_parent():
    for nid, when in _WHEN_BRANCHES:
        assert when["upstream"] in _NODES[nid]["conduction"]

def test_unconditional_nodes_succeed_without_outputs():
    from support.graph_model import run_model
    status = run_model(_EFFECTORS, {})
    for nid, meta in _NODES.items():
        if meta["when"] is None:
            assert status[nid] == "succeeded"

