"""Independent conduction and when metadata for issue_triage."""
from __future__ import annotations
import json

_PATH_ID = 'issue_triage'
_NODES = {'apply_issue_blocked': {'atom': 'apply_issue_blocked',
                         'conduction': ['get_issue', 'finalize_issue_triage', 'select_triage_leaf'],
                         'when': {'equals': 'blocked', 'path': 'route', 'upstream': 'select_triage_leaf'}},
 'apply_issue_manual': {'atom': 'apply_issue_manual',
                        'conduction': ['get_issue',
                                       'finalize_issue_triage',
                                       'select_triage_leaf',
                                       'select_park_stop'],
                        'when': {'equals': 'skip', 'path': 'route', 'upstream': 'select_park_stop'}},
 'apply_issue_mark': {'atom': 'apply_issue_mark',
                      'conduction': ['get_issue', 'finalize_issue_triage', 'select_triage_leaf'],
                      'when': {'equals': 'close', 'path': 'route', 'upstream': 'select_triage_leaf'}},
 'apply_issue_ready': {'atom': 'apply_issue_ready',
                       'conduction': ['get_issue', 'finalize_issue_triage', 'select_triage_leaf'],
                       'when': {'equals': 'ready', 'path': 'route', 'upstream': 'select_triage_leaf'}},
 'apply_issue_skip': {'atom': 'apply_issue_skip',
                      'conduction': ['get_issue', 'finalize_issue_triage', 'select_triage_leaf'],
                      'when': {'equals': 'skip', 'path': 'route', 'upstream': 'select_triage_leaf'}},
 'collect_issue_covering_prs': {'atom': 'collect_issue_covering_prs',
                                'conduction': ['get_issue',
                                               'resolve_issue_candidate',
                                               'collect_issue_linked_prs'],
                                'when': {'equals': 'evaluate',
                                         'path': 'route',
                                         'upstream': 'resolve_issue_candidate'}},
 'collect_issue_linked_prs': {'atom': 'collect_issue_linked_prs',
                              'conduction': ['get_issue', 'resolve_issue_candidate'],
                              'when': {'equals': 'evaluate',
                                       'path': 'route',
                                       'upstream': 'resolve_issue_candidate'}},
 'collect_issue_named_paths': {'atom': 'collect_issue_named_paths',
                               'conduction': ['get_issue', 'select_issue_triage'],
                               'when': {'equals': 'named_paths',
                                        'path': 'evidence_kind',
                                        'upstream': 'select_issue_triage'}},
 'collect_issue_repo_shape': {'atom': 'collect_issue_repo_shape',
                              'conduction': ['select_issue_triage'],
                              'when': {'equals': 'repo_shape',
                                       'path': 'evidence_kind',
                                       'upstream': 'select_issue_triage'}},
 'finalize_issue_triage': {'atom': 'finalize_issue_triage',
                           'conduction': ['select_issue_triage', 'select_issue_evidence'],
                           'when': None},
 'get_issue': {'atom': 'get_issue', 'conduction': [], 'when': None},
 'issue_evidence_agent': {'atom': 'issue_evidence_agent',
                          'conduction': ['get_issue',
                                         'map_repo',
                                         'resolve_issue_hard_facts',
                                         'verify_issue_evidence'],
                          'when': {'equals': 'agent', 'path': 'route', 'upstream': 'verify_issue_evidence'}},
 'issue_triage_agent': {'atom': 'issue_triage_agent',
                        'conduction': ['get_issue', 'resolve_issue_hard_facts', 'map_repo'],
                        'when': {'equals': 'agent', 'path': 'route', 'upstream': 'resolve_issue_hard_facts'}},
 'issue_triage_retry_agent': {'atom': 'issue_triage_retry_agent',
                              'conduction': ['get_issue',
                                             'resolve_issue_hard_facts',
                                             'map_repo',
                                             'validate_issue_triage'],
                              'when': {'equals': 'retry',
                                       'path': 'route',
                                       'upstream': 'validate_issue_triage'}},
 'map_repo': {'atom': 'map_repo', 'conduction': ['get_issue', 'resolve_issue_hard_facts'], 'when': None},
 'resolve_issue_candidate': {'atom': 'resolve_issue_candidate', 'conduction': ['get_issue'], 'when': None},
 'resolve_issue_hard_facts': {'atom': 'resolve_issue_hard_facts',
                              'conduction': ['get_issue',
                                             'resolve_issue_candidate',
                                             'collect_issue_linked_prs',
                                             'collect_issue_covering_prs'],
                              'when': None},
 'select_issue_evidence': {'atom': 'select_issue_evidence',
                           'conduction': ['select_issue_triage', 'validate_issue_evidence'],
                           'when': None},
 'select_issue_triage': {'atom': 'select_issue_triage',
                         'conduction': ['resolve_issue_hard_facts',
                                        'validate_issue_triage',
                                        'validate_issue_triage_retry'],
                         'when': None},
 'select_park_stop': {'atom': 'select_park_stop',
                      'conduction': ['finalize_issue_triage', 'select_triage_leaf'],
                      'when': {'equals': 'park', 'path': 'route', 'upstream': 'select_triage_leaf'}},
 'select_triage_leaf': {'atom': 'select_triage_leaf', 'conduction': ['finalize_issue_triage'], 'when': None},
 'summarize_issue_triage': {'atom': 'summarize_issue_triage',
                            'conduction': ['finalize_issue_triage',
                                           'select_triage_leaf',
                                           'select_park_stop',
                                           'apply_issue_ready',
                                           'apply_issue_skip',
                                           'apply_issue_blocked',
                                           'apply_issue_mark',
                                           'apply_issue_manual'],
                            'when': None},
 'validate_issue_evidence': {'atom': 'validate_issue_evidence',
                             'conduction': ['verify_issue_evidence', 'issue_evidence_agent'],
                             'when': {'equals': 'agent',
                                      'path': 'route',
                                      'upstream': 'verify_issue_evidence'}},
 'validate_issue_triage': {'atom': 'validate_issue_triage',
                           'conduction': ['resolve_issue_hard_facts', 'issue_triage_agent'],
                           'when': None},
 'validate_issue_triage_retry': {'atom': 'validate_issue_triage_retry',
                                 'conduction': ['validate_issue_triage', 'issue_triage_retry_agent'],
                                 'when': {'equals': 'retry',
                                          'path': 'route',
                                          'upstream': 'validate_issue_triage'}},
 'verify_issue_evidence': {'atom': 'verify_issue_evidence',
                           'conduction': ['select_issue_triage',
                                          'collect_issue_linked_prs',
                                          'collect_issue_covering_prs',
                                          'collect_issue_repo_shape',
                                          'collect_issue_named_paths'],
                           'when': None}}
_COND_EDGES = [('get_issue', 'resolve_issue_candidate'),
 ('get_issue', 'collect_issue_linked_prs'),
 ('resolve_issue_candidate', 'collect_issue_linked_prs'),
 ('get_issue', 'collect_issue_covering_prs'),
 ('resolve_issue_candidate', 'collect_issue_covering_prs'),
 ('collect_issue_linked_prs', 'collect_issue_covering_prs'),
 ('get_issue', 'resolve_issue_hard_facts'),
 ('resolve_issue_candidate', 'resolve_issue_hard_facts'),
 ('collect_issue_linked_prs', 'resolve_issue_hard_facts'),
 ('collect_issue_covering_prs', 'resolve_issue_hard_facts'),
 ('get_issue', 'map_repo'),
 ('resolve_issue_hard_facts', 'map_repo'),
 ('get_issue', 'issue_triage_agent'),
 ('resolve_issue_hard_facts', 'issue_triage_agent'),
 ('map_repo', 'issue_triage_agent'),
 ('resolve_issue_hard_facts', 'validate_issue_triage'),
 ('issue_triage_agent', 'validate_issue_triage'),
 ('get_issue', 'issue_triage_retry_agent'),
 ('resolve_issue_hard_facts', 'issue_triage_retry_agent'),
 ('map_repo', 'issue_triage_retry_agent'),
 ('validate_issue_triage', 'issue_triage_retry_agent'),
 ('validate_issue_triage', 'validate_issue_triage_retry'),
 ('issue_triage_retry_agent', 'validate_issue_triage_retry'),
 ('resolve_issue_hard_facts', 'select_issue_triage'),
 ('validate_issue_triage', 'select_issue_triage'),
 ('validate_issue_triage_retry', 'select_issue_triage'),
 ('select_issue_triage', 'collect_issue_repo_shape'),
 ('get_issue', 'collect_issue_named_paths'),
 ('select_issue_triage', 'collect_issue_named_paths'),
 ('select_issue_triage', 'verify_issue_evidence'),
 ('collect_issue_linked_prs', 'verify_issue_evidence'),
 ('collect_issue_covering_prs', 'verify_issue_evidence'),
 ('collect_issue_repo_shape', 'verify_issue_evidence'),
 ('collect_issue_named_paths', 'verify_issue_evidence'),
 ('get_issue', 'issue_evidence_agent'),
 ('map_repo', 'issue_evidence_agent'),
 ('resolve_issue_hard_facts', 'issue_evidence_agent'),
 ('verify_issue_evidence', 'issue_evidence_agent'),
 ('verify_issue_evidence', 'validate_issue_evidence'),
 ('issue_evidence_agent', 'validate_issue_evidence'),
 ('select_issue_triage', 'select_issue_evidence'),
 ('validate_issue_evidence', 'select_issue_evidence'),
 ('select_issue_triage', 'finalize_issue_triage'),
 ('select_issue_evidence', 'finalize_issue_triage'),
 ('finalize_issue_triage', 'select_triage_leaf'),
 ('get_issue', 'apply_issue_blocked'),
 ('finalize_issue_triage', 'apply_issue_blocked'),
 ('select_triage_leaf', 'apply_issue_blocked'),
 ('get_issue', 'apply_issue_mark'),
 ('finalize_issue_triage', 'apply_issue_mark'),
 ('select_triage_leaf', 'apply_issue_mark'),
 ('get_issue', 'apply_issue_ready'),
 ('finalize_issue_triage', 'apply_issue_ready'),
 ('select_triage_leaf', 'apply_issue_ready'),
 ('get_issue', 'apply_issue_skip'),
 ('finalize_issue_triage', 'apply_issue_skip'),
 ('select_triage_leaf', 'apply_issue_skip'),
 ('finalize_issue_triage', 'select_park_stop'),
 ('select_triage_leaf', 'select_park_stop'),
 ('get_issue', 'apply_issue_manual'),
 ('finalize_issue_triage', 'apply_issue_manual'),
 ('select_triage_leaf', 'apply_issue_manual'),
 ('select_park_stop', 'apply_issue_manual'),
 ('finalize_issue_triage', 'summarize_issue_triage'),
 ('select_triage_leaf', 'summarize_issue_triage'),
 ('select_park_stop', 'summarize_issue_triage'),
 ('apply_issue_ready', 'summarize_issue_triage'),
 ('apply_issue_skip', 'summarize_issue_triage'),
 ('apply_issue_blocked', 'summarize_issue_triage'),
 ('apply_issue_mark', 'summarize_issue_triage'),
 ('apply_issue_manual', 'summarize_issue_triage')]
_WHEN_BRANCHES = [('collect_issue_linked_prs', {'equals': 'evaluate', 'path': 'route', 'upstream': 'resolve_issue_candidate'}),
 ('collect_issue_covering_prs',
  {'equals': 'evaluate', 'path': 'route', 'upstream': 'resolve_issue_candidate'}),
 ('issue_triage_agent', {'equals': 'agent', 'path': 'route', 'upstream': 'resolve_issue_hard_facts'}),
 ('issue_triage_retry_agent', {'equals': 'retry', 'path': 'route', 'upstream': 'validate_issue_triage'}),
 ('validate_issue_triage_retry', {'equals': 'retry', 'path': 'route', 'upstream': 'validate_issue_triage'}),
 ('collect_issue_repo_shape',
  {'equals': 'repo_shape', 'path': 'evidence_kind', 'upstream': 'select_issue_triage'}),
 ('collect_issue_named_paths',
  {'equals': 'named_paths', 'path': 'evidence_kind', 'upstream': 'select_issue_triage'}),
 ('issue_evidence_agent', {'equals': 'agent', 'path': 'route', 'upstream': 'verify_issue_evidence'}),
 ('validate_issue_evidence', {'equals': 'agent', 'path': 'route', 'upstream': 'verify_issue_evidence'}),
 ('apply_issue_blocked', {'equals': 'blocked', 'path': 'route', 'upstream': 'select_triage_leaf'}),
 ('apply_issue_mark', {'equals': 'close', 'path': 'route', 'upstream': 'select_triage_leaf'}),
 ('apply_issue_ready', {'equals': 'ready', 'path': 'route', 'upstream': 'select_triage_leaf'}),
 ('apply_issue_skip', {'equals': 'skip', 'path': 'route', 'upstream': 'select_triage_leaf'}),
 ('select_park_stop', {'equals': 'park', 'path': 'route', 'upstream': 'select_triage_leaf'}),
 ('apply_issue_manual', {'equals': 'skip', 'path': 'route', 'upstream': 'select_park_stop'})]
_EFFECTORS = [{'conduction': [], 'id': 'get_issue', 'when': None},
 {'conduction': ['get_issue'], 'id': 'resolve_issue_candidate', 'when': None},
 {'conduction': ['get_issue', 'resolve_issue_candidate'],
  'id': 'collect_issue_linked_prs',
  'when': {'equals': 'evaluate', 'path': 'route', 'upstream': 'resolve_issue_candidate'}},
 {'conduction': ['get_issue', 'resolve_issue_candidate', 'collect_issue_linked_prs'],
  'id': 'collect_issue_covering_prs',
  'when': {'equals': 'evaluate', 'path': 'route', 'upstream': 'resolve_issue_candidate'}},
 {'conduction': ['get_issue',
                 'resolve_issue_candidate',
                 'collect_issue_linked_prs',
                 'collect_issue_covering_prs'],
  'id': 'resolve_issue_hard_facts',
  'when': None},
 {'conduction': ['get_issue', 'resolve_issue_hard_facts'], 'id': 'map_repo', 'when': None},
 {'conduction': ['get_issue', 'resolve_issue_hard_facts', 'map_repo'],
  'id': 'issue_triage_agent',
  'when': {'equals': 'agent', 'path': 'route', 'upstream': 'resolve_issue_hard_facts'}},
 {'conduction': ['resolve_issue_hard_facts', 'issue_triage_agent'],
  'id': 'validate_issue_triage',
  'when': None},
 {'conduction': ['get_issue', 'resolve_issue_hard_facts', 'map_repo', 'validate_issue_triage'],
  'id': 'issue_triage_retry_agent',
  'when': {'equals': 'retry', 'path': 'route', 'upstream': 'validate_issue_triage'}},
 {'conduction': ['validate_issue_triage', 'issue_triage_retry_agent'],
  'id': 'validate_issue_triage_retry',
  'when': {'equals': 'retry', 'path': 'route', 'upstream': 'validate_issue_triage'}},
 {'conduction': ['resolve_issue_hard_facts', 'validate_issue_triage', 'validate_issue_triage_retry'],
  'id': 'select_issue_triage',
  'when': None},
 {'conduction': ['select_issue_triage'],
  'id': 'collect_issue_repo_shape',
  'when': {'equals': 'repo_shape', 'path': 'evidence_kind', 'upstream': 'select_issue_triage'}},
 {'conduction': ['get_issue', 'select_issue_triage'],
  'id': 'collect_issue_named_paths',
  'when': {'equals': 'named_paths', 'path': 'evidence_kind', 'upstream': 'select_issue_triage'}},
 {'conduction': ['select_issue_triage',
                 'collect_issue_linked_prs',
                 'collect_issue_covering_prs',
                 'collect_issue_repo_shape',
                 'collect_issue_named_paths'],
  'id': 'verify_issue_evidence',
  'when': None},
 {'conduction': ['get_issue', 'map_repo', 'resolve_issue_hard_facts', 'verify_issue_evidence'],
  'id': 'issue_evidence_agent',
  'when': {'equals': 'agent', 'path': 'route', 'upstream': 'verify_issue_evidence'}},
 {'conduction': ['verify_issue_evidence', 'issue_evidence_agent'],
  'id': 'validate_issue_evidence',
  'when': {'equals': 'agent', 'path': 'route', 'upstream': 'verify_issue_evidence'}},
 {'conduction': ['select_issue_triage', 'validate_issue_evidence'],
  'id': 'select_issue_evidence',
  'when': None},
 {'conduction': ['select_issue_triage', 'select_issue_evidence'],
  'id': 'finalize_issue_triage',
  'when': None},
 {'conduction': ['finalize_issue_triage'], 'id': 'select_triage_leaf', 'when': None},
 {'conduction': ['get_issue', 'finalize_issue_triage', 'select_triage_leaf'],
  'id': 'apply_issue_blocked',
  'when': {'equals': 'blocked', 'path': 'route', 'upstream': 'select_triage_leaf'}},
 {'conduction': ['get_issue', 'finalize_issue_triage', 'select_triage_leaf'],
  'id': 'apply_issue_mark',
  'when': {'equals': 'close', 'path': 'route', 'upstream': 'select_triage_leaf'}},
 {'conduction': ['get_issue', 'finalize_issue_triage', 'select_triage_leaf'],
  'id': 'apply_issue_ready',
  'when': {'equals': 'ready', 'path': 'route', 'upstream': 'select_triage_leaf'}},
 {'conduction': ['get_issue', 'finalize_issue_triage', 'select_triage_leaf'],
  'id': 'apply_issue_skip',
  'when': {'equals': 'skip', 'path': 'route', 'upstream': 'select_triage_leaf'}},
 {'conduction': ['finalize_issue_triage', 'select_triage_leaf'],
  'id': 'select_park_stop',
  'when': {'equals': 'park', 'path': 'route', 'upstream': 'select_triage_leaf'}},
 {'conduction': ['get_issue', 'finalize_issue_triage', 'select_triage_leaf', 'select_park_stop'],
  'id': 'apply_issue_manual',
  'when': {'equals': 'skip', 'path': 'route', 'upstream': 'select_park_stop'}},
 {'conduction': ['finalize_issue_triage',
                 'select_triage_leaf',
                 'select_park_stop',
                 'apply_issue_ready',
                 'apply_issue_skip',
                 'apply_issue_blocked',
                 'apply_issue_mark',
                 'apply_issue_manual'],
  'id': 'summarize_issue_triage',
  'when': None}]

def test_every_conduction_edge_is_declared():
    got = {(str(up), nid) for nid, meta in _NODES.items() for up in meta["conduction"]}
    assert got == set(tuple(edge) for edge in _COND_EDGES)

def test_every_when_branch_is_declared():
    got = {(nid, json.dumps(meta["when"], sort_keys=True)) for nid, meta in _NODES.items() if meta["when"]}
    want = {(nid, json.dumps(when, sort_keys=True)) for nid, when in _WHEN_BRANCHES}
    assert got == want

def test_when_upstream_is_a_direct_parent():
    for nid, when in _WHEN_BRANCHES:
        assert when["upstream"] in _NODES[nid]["conduction"]

def test_unconditional_nodes_succeed_without_outputs():
    from support.graph_model import run_model
    status = run_model(_EFFECTORS, {})
    for nid, meta in _NODES.items():
        if meta["when"] is None:
            assert status[nid] == "succeeded"

