"""Independent conduction and when metadata for pr_triage."""
from __future__ import annotations
import json

_PATH_ID = 'pr_triage'
_NODES = {'classify_pr_triage_checks': {'atom': 'classify_pr_triage_checks',
                               'conduction': ['pr_checks'],
                               'when': None},
 'close_issue': {'atom': 'close_issue',
                 'conduction': ['publish_pr_review', 'pr_merge', 'stage_clear', 'select_pr_triage_outcome'],
                 'when': {'equals': 'merge', 'path': 'route', 'upstream': 'select_pr_triage_outcome'}},
 'collect_pr_review_evidence': {'atom': 'collect_pr_review_evidence',
                                'conduction': ['pr_checks', 'classify_pr_triage_checks'],
                                'when': {'equals': 'review',
                                         'path': 'route',
                                         'upstream': 'classify_pr_triage_checks'}},
 'evidence_review_agent': {'atom': 'evidence_review_agent',
                           'conduction': ['collect_pr_review_evidence',
                                          'select_pr_review',
                                          'review_evidence_catalog'],
                           'when': {'equals': 'agent',
                                    'path': 'route',
                                    'upstream': 'review_evidence_catalog'}},
 'finalize_pr_review': {'atom': 'finalize_pr_review',
                        'conduction': ['classify_pr_triage_checks',
                                       'select_pr_review',
                                       'select_evidence_review'],
                        'when': {'equals': 'review',
                                 'path': 'route',
                                 'upstream': 'classify_pr_triage_checks'}},
 'pr_checks': {'atom': 'pr_checks', 'conduction': [], 'when': None},
 'pr_merge': {'atom': 'pr_merge',
              'conduction': ['pr_checks', 'publish_pr_review', 'test_local', 'select_pr_triage_outcome'],
              'when': {'equals': 'merge', 'path': 'route', 'upstream': 'select_pr_triage_outcome'}},
 'pr_repair_verdict': {'atom': 'pr_repair_verdict',
                       'conduction': ['classify_pr_triage_checks',
                                      'select_pr_triage_outcome',
                                      'publish_pr_review'],
                       'when': {'equals': 'repair', 'path': 'route', 'upstream': 'select_pr_triage_outcome'}},
 'pr_review_agent': {'atom': 'pr_review_agent',
                     'conduction': ['classify_pr_triage_checks',
                                    'collect_pr_review_evidence',
                                    'resolve_sha_review'],
                     'when': {'equals': 'agent', 'path': 'route', 'upstream': 'resolve_sha_review'}},
 'pr_review_retry_agent': {'atom': 'pr_review_retry_agent',
                           'conduction': ['collect_pr_review_evidence', 'validate_pr_review'],
                           'when': {'equals': 'retry', 'path': 'route', 'upstream': 'validate_pr_review'}},
 'publish_delivery_receipt': {'atom': 'publish_delivery_receipt',
                              'conduction': ['pr_merge', 'close_issue', 'select_pr_triage_outcome'],
                              'when': {'equals': 'merge',
                                       'path': 'route',
                                       'upstream': 'select_pr_triage_outcome'}},
 'publish_pr_review': {'atom': 'publish_pr_review',
                       'conduction': ['classify_pr_triage_checks',
                                      'collect_pr_review_evidence',
                                      'finalize_pr_review'],
                       'when': None},
 'resolve_sha_review': {'atom': 'resolve_sha_review',
                        'conduction': ['classify_pr_triage_checks', 'collect_pr_review_evidence'],
                        'when': None},
 'review_evidence_catalog': {'atom': 'review_evidence_catalog',
                             'conduction': ['classify_pr_triage_checks',
                                            'collect_pr_review_evidence',
                                            'select_pr_review'],
                             'when': {'equals': 'evidence', 'path': 'route', 'upstream': 'select_pr_review'}},
 'review_manual': {'atom': 'review_manual',
                   'conduction': ['publish_pr_review'],
                   'when': {'equals': 'fail_closed',
                            'path': 'decision.verdict',
                            'upstream': 'publish_pr_review'}},
 'review_repair_gate': {'atom': 'review_repair_gate',
                        'conduction': ['classify_pr_triage_checks', 'publish_pr_review'],
                        'when': None},
 'review_repair_manual': {'atom': 'review_repair_manual',
                          'conduction': ['publish_pr_review', 'review_repair_gate'],
                          'when': {'equals': 'fail_closed',
                                   'path': 'route',
                                   'upstream': 'review_repair_gate'}},
 'select_evidence_review': {'atom': 'select_evidence_review',
                            'conduction': ['classify_pr_triage_checks',
                                           'select_pr_review',
                                           'validate_evidence_review'],
                            'when': {'equals': 'review',
                                     'path': 'route',
                                     'upstream': 'classify_pr_triage_checks'}},
 'select_pr_review': {'atom': 'select_pr_review',
                      'conduction': ['classify_pr_triage_checks',
                                     'resolve_sha_review',
                                     'validate_pr_review',
                                     'validate_pr_review_retry'],
                      'when': None},
 'select_pr_triage_outcome': {'atom': 'select_pr_triage_outcome',
                              'conduction': ['classify_pr_triage_checks', 'review_repair_gate', 'test_local'],
                              'when': None},
 'stage_clear': {'atom': 'stage_label',
                 'conduction': ['publish_pr_review', 'pr_merge', 'select_pr_triage_outcome'],
                 'when': {'equals': 'merge', 'path': 'route', 'upstream': 'select_pr_triage_outcome'}},
 'summarize_pr_triage': {'atom': 'summarize_pr_triage',
                         'conduction': ['classify_pr_triage_checks',
                                        'select_pr_triage_outcome',
                                        'pr_repair_verdict',
                                        'review_repair_manual',
                                        'review_manual',
                                        'pr_merge',
                                        'close_issue',
                                        'publish_delivery_receipt',
                                        'publish_pr_review'],
                         'when': None},
 'test_local': {'atom': 'test_local',
                'conduction': ['publish_pr_review', 'worktree_add'],
                'when': {'equals': 'approve', 'path': 'decision.verdict', 'upstream': 'publish_pr_review'}},
 'validate_evidence_review': {'atom': 'validate_evidence_review',
                              'conduction': ['select_pr_review',
                                             'review_evidence_catalog',
                                             'evidence_review_agent'],
                              'when': {'equals': 'agent',
                                       'path': 'route',
                                       'upstream': 'review_evidence_catalog'}},
 'validate_pr_review': {'atom': 'validate_pr_review',
                        'conduction': ['classify_pr_triage_checks', 'resolve_sha_review', 'pr_review_agent'],
                        'when': None},
 'validate_pr_review_retry': {'atom': 'validate_pr_review_retry',
                              'conduction': ['validate_pr_review', 'pr_review_retry_agent'],
                              'when': {'equals': 'retry', 'path': 'route', 'upstream': 'validate_pr_review'}},
 'worktree_add': {'atom': 'worktree_add',
                  'conduction': ['pr_checks', 'publish_pr_review'],
                  'when': {'equals': 'approve', 'path': 'decision.verdict', 'upstream': 'publish_pr_review'}}}
_COND_EDGES = [('pr_checks', 'classify_pr_triage_checks'),
 ('pr_checks', 'collect_pr_review_evidence'),
 ('classify_pr_triage_checks', 'collect_pr_review_evidence'),
 ('classify_pr_triage_checks', 'resolve_sha_review'),
 ('collect_pr_review_evidence', 'resolve_sha_review'),
 ('classify_pr_triage_checks', 'pr_review_agent'),
 ('collect_pr_review_evidence', 'pr_review_agent'),
 ('resolve_sha_review', 'pr_review_agent'),
 ('classify_pr_triage_checks', 'validate_pr_review'),
 ('resolve_sha_review', 'validate_pr_review'),
 ('pr_review_agent', 'validate_pr_review'),
 ('collect_pr_review_evidence', 'pr_review_retry_agent'),
 ('validate_pr_review', 'pr_review_retry_agent'),
 ('validate_pr_review', 'validate_pr_review_retry'),
 ('pr_review_retry_agent', 'validate_pr_review_retry'),
 ('classify_pr_triage_checks', 'select_pr_review'),
 ('resolve_sha_review', 'select_pr_review'),
 ('validate_pr_review', 'select_pr_review'),
 ('validate_pr_review_retry', 'select_pr_review'),
 ('classify_pr_triage_checks', 'review_evidence_catalog'),
 ('collect_pr_review_evidence', 'review_evidence_catalog'),
 ('select_pr_review', 'review_evidence_catalog'),
 ('collect_pr_review_evidence', 'evidence_review_agent'),
 ('select_pr_review', 'evidence_review_agent'),
 ('review_evidence_catalog', 'evidence_review_agent'),
 ('select_pr_review', 'validate_evidence_review'),
 ('review_evidence_catalog', 'validate_evidence_review'),
 ('evidence_review_agent', 'validate_evidence_review'),
 ('classify_pr_triage_checks', 'select_evidence_review'),
 ('select_pr_review', 'select_evidence_review'),
 ('validate_evidence_review', 'select_evidence_review'),
 ('classify_pr_triage_checks', 'finalize_pr_review'),
 ('select_pr_review', 'finalize_pr_review'),
 ('select_evidence_review', 'finalize_pr_review'),
 ('classify_pr_triage_checks', 'publish_pr_review'),
 ('collect_pr_review_evidence', 'publish_pr_review'),
 ('finalize_pr_review', 'publish_pr_review'),
 ('classify_pr_triage_checks', 'review_repair_gate'),
 ('publish_pr_review', 'review_repair_gate'),
 ('publish_pr_review', 'review_repair_manual'),
 ('review_repair_gate', 'review_repair_manual'),
 ('publish_pr_review', 'review_manual'),
 ('pr_checks', 'worktree_add'),
 ('publish_pr_review', 'worktree_add'),
 ('publish_pr_review', 'test_local'),
 ('worktree_add', 'test_local'),
 ('classify_pr_triage_checks', 'select_pr_triage_outcome'),
 ('review_repair_gate', 'select_pr_triage_outcome'),
 ('test_local', 'select_pr_triage_outcome'),
 ('classify_pr_triage_checks', 'pr_repair_verdict'),
 ('select_pr_triage_outcome', 'pr_repair_verdict'),
 ('publish_pr_review', 'pr_repair_verdict'),
 ('pr_checks', 'pr_merge'),
 ('publish_pr_review', 'pr_merge'),
 ('test_local', 'pr_merge'),
 ('select_pr_triage_outcome', 'pr_merge'),
 ('publish_pr_review', 'stage_clear'),
 ('pr_merge', 'stage_clear'),
 ('select_pr_triage_outcome', 'stage_clear'),
 ('publish_pr_review', 'close_issue'),
 ('pr_merge', 'close_issue'),
 ('stage_clear', 'close_issue'),
 ('select_pr_triage_outcome', 'close_issue'),
 ('pr_merge', 'publish_delivery_receipt'),
 ('close_issue', 'publish_delivery_receipt'),
 ('select_pr_triage_outcome', 'publish_delivery_receipt'),
 ('classify_pr_triage_checks', 'summarize_pr_triage'),
 ('select_pr_triage_outcome', 'summarize_pr_triage'),
 ('pr_repair_verdict', 'summarize_pr_triage'),
 ('review_repair_manual', 'summarize_pr_triage'),
 ('review_manual', 'summarize_pr_triage'),
 ('pr_merge', 'summarize_pr_triage'),
 ('close_issue', 'summarize_pr_triage'),
 ('publish_delivery_receipt', 'summarize_pr_triage'),
 ('publish_pr_review', 'summarize_pr_triage')]
_WHEN_BRANCHES = [('collect_pr_review_evidence',
  {'equals': 'review', 'path': 'route', 'upstream': 'classify_pr_triage_checks'}),
 ('pr_review_agent', {'equals': 'agent', 'path': 'route', 'upstream': 'resolve_sha_review'}),
 ('pr_review_retry_agent', {'equals': 'retry', 'path': 'route', 'upstream': 'validate_pr_review'}),
 ('validate_pr_review_retry', {'equals': 'retry', 'path': 'route', 'upstream': 'validate_pr_review'}),
 ('review_evidence_catalog', {'equals': 'evidence', 'path': 'route', 'upstream': 'select_pr_review'}),
 ('evidence_review_agent', {'equals': 'agent', 'path': 'route', 'upstream': 'review_evidence_catalog'}),
 ('validate_evidence_review', {'equals': 'agent', 'path': 'route', 'upstream': 'review_evidence_catalog'}),
 ('select_evidence_review', {'equals': 'review', 'path': 'route', 'upstream': 'classify_pr_triage_checks'}),
 ('finalize_pr_review', {'equals': 'review', 'path': 'route', 'upstream': 'classify_pr_triage_checks'}),
 ('review_repair_manual', {'equals': 'fail_closed', 'path': 'route', 'upstream': 'review_repair_gate'}),
 ('review_manual', {'equals': 'fail_closed', 'path': 'decision.verdict', 'upstream': 'publish_pr_review'}),
 ('worktree_add', {'equals': 'approve', 'path': 'decision.verdict', 'upstream': 'publish_pr_review'}),
 ('test_local', {'equals': 'approve', 'path': 'decision.verdict', 'upstream': 'publish_pr_review'}),
 ('pr_repair_verdict', {'equals': 'repair', 'path': 'route', 'upstream': 'select_pr_triage_outcome'}),
 ('pr_merge', {'equals': 'merge', 'path': 'route', 'upstream': 'select_pr_triage_outcome'}),
 ('stage_clear', {'equals': 'merge', 'path': 'route', 'upstream': 'select_pr_triage_outcome'}),
 ('close_issue', {'equals': 'merge', 'path': 'route', 'upstream': 'select_pr_triage_outcome'}),
 ('publish_delivery_receipt', {'equals': 'merge', 'path': 'route', 'upstream': 'select_pr_triage_outcome'})]
_EFFECTORS = [{'conduction': [], 'id': 'pr_checks', 'when': None},
 {'conduction': ['pr_checks'], 'id': 'classify_pr_triage_checks', 'when': None},
 {'conduction': ['pr_checks', 'classify_pr_triage_checks'],
  'id': 'collect_pr_review_evidence',
  'when': {'equals': 'review', 'path': 'route', 'upstream': 'classify_pr_triage_checks'}},
 {'conduction': ['classify_pr_triage_checks', 'collect_pr_review_evidence'],
  'id': 'resolve_sha_review',
  'when': None},
 {'conduction': ['classify_pr_triage_checks', 'collect_pr_review_evidence', 'resolve_sha_review'],
  'id': 'pr_review_agent',
  'when': {'equals': 'agent', 'path': 'route', 'upstream': 'resolve_sha_review'}},
 {'conduction': ['classify_pr_triage_checks', 'resolve_sha_review', 'pr_review_agent'],
  'id': 'validate_pr_review',
  'when': None},
 {'conduction': ['collect_pr_review_evidence', 'validate_pr_review'],
  'id': 'pr_review_retry_agent',
  'when': {'equals': 'retry', 'path': 'route', 'upstream': 'validate_pr_review'}},
 {'conduction': ['validate_pr_review', 'pr_review_retry_agent'],
  'id': 'validate_pr_review_retry',
  'when': {'equals': 'retry', 'path': 'route', 'upstream': 'validate_pr_review'}},
 {'conduction': ['classify_pr_triage_checks',
                 'resolve_sha_review',
                 'validate_pr_review',
                 'validate_pr_review_retry'],
  'id': 'select_pr_review',
  'when': None},
 {'conduction': ['classify_pr_triage_checks', 'collect_pr_review_evidence', 'select_pr_review'],
  'id': 'review_evidence_catalog',
  'when': {'equals': 'evidence', 'path': 'route', 'upstream': 'select_pr_review'}},
 {'conduction': ['collect_pr_review_evidence', 'select_pr_review', 'review_evidence_catalog'],
  'id': 'evidence_review_agent',
  'when': {'equals': 'agent', 'path': 'route', 'upstream': 'review_evidence_catalog'}},
 {'conduction': ['select_pr_review', 'review_evidence_catalog', 'evidence_review_agent'],
  'id': 'validate_evidence_review',
  'when': {'equals': 'agent', 'path': 'route', 'upstream': 'review_evidence_catalog'}},
 {'conduction': ['classify_pr_triage_checks', 'select_pr_review', 'validate_evidence_review'],
  'id': 'select_evidence_review',
  'when': {'equals': 'review', 'path': 'route', 'upstream': 'classify_pr_triage_checks'}},
 {'conduction': ['classify_pr_triage_checks', 'select_pr_review', 'select_evidence_review'],
  'id': 'finalize_pr_review',
  'when': {'equals': 'review', 'path': 'route', 'upstream': 'classify_pr_triage_checks'}},
 {'conduction': ['classify_pr_triage_checks', 'collect_pr_review_evidence', 'finalize_pr_review'],
  'id': 'publish_pr_review',
  'when': None},
 {'conduction': ['classify_pr_triage_checks', 'publish_pr_review'], 'id': 'review_repair_gate', 'when': None},
 {'conduction': ['publish_pr_review', 'review_repair_gate'],
  'id': 'review_repair_manual',
  'when': {'equals': 'fail_closed', 'path': 'route', 'upstream': 'review_repair_gate'}},
 {'conduction': ['publish_pr_review'],
  'id': 'review_manual',
  'when': {'equals': 'fail_closed', 'path': 'decision.verdict', 'upstream': 'publish_pr_review'}},
 {'conduction': ['pr_checks', 'publish_pr_review'],
  'id': 'worktree_add',
  'when': {'equals': 'approve', 'path': 'decision.verdict', 'upstream': 'publish_pr_review'}},
 {'conduction': ['publish_pr_review', 'worktree_add'],
  'id': 'test_local',
  'when': {'equals': 'approve', 'path': 'decision.verdict', 'upstream': 'publish_pr_review'}},
 {'conduction': ['classify_pr_triage_checks', 'review_repair_gate', 'test_local'],
  'id': 'select_pr_triage_outcome',
  'when': None},
 {'conduction': ['classify_pr_triage_checks', 'select_pr_triage_outcome', 'publish_pr_review'],
  'id': 'pr_repair_verdict',
  'when': {'equals': 'repair', 'path': 'route', 'upstream': 'select_pr_triage_outcome'}},
 {'conduction': ['pr_checks', 'publish_pr_review', 'test_local', 'select_pr_triage_outcome'],
  'id': 'pr_merge',
  'when': {'equals': 'merge', 'path': 'route', 'upstream': 'select_pr_triage_outcome'}},
 {'conduction': ['publish_pr_review', 'pr_merge', 'select_pr_triage_outcome'],
  'id': 'stage_clear',
  'when': {'equals': 'merge', 'path': 'route', 'upstream': 'select_pr_triage_outcome'}},
 {'conduction': ['publish_pr_review', 'pr_merge', 'stage_clear', 'select_pr_triage_outcome'],
  'id': 'close_issue',
  'when': {'equals': 'merge', 'path': 'route', 'upstream': 'select_pr_triage_outcome'}},
 {'conduction': ['pr_merge', 'close_issue', 'select_pr_triage_outcome'],
  'id': 'publish_delivery_receipt',
  'when': {'equals': 'merge', 'path': 'route', 'upstream': 'select_pr_triage_outcome'}},
 {'conduction': ['classify_pr_triage_checks',
                 'select_pr_triage_outcome',
                 'pr_repair_verdict',
                 'review_repair_manual',
                 'review_manual',
                 'pr_merge',
                 'close_issue',
                 'publish_delivery_receipt',
                 'publish_pr_review'],
  'id': 'summarize_pr_triage',
  'when': None}]

def test_every_conduction_edge_is_declared():
    got = {(str(up), nid) for nid, meta in _NODES.items() for up in meta["conduction"]}
    assert got == set(tuple(edge) for edge in _COND_EDGES)

def test_every_when_branch_is_declared():
    got = {(nid, json.dumps(meta["when"], sort_keys=True)) for nid, meta in _NODES.items() if meta["when"]}
    want = {(nid, json.dumps(when, sort_keys=True)) for nid, when in _WHEN_BRANCHES}
    assert got == want

def test_when_upstream_is_a_direct_parent():
    for nid, when in _WHEN_BRANCHES:
        assert when["upstream"] in _NODES[nid]["conduction"]

def test_unconditional_nodes_succeed_without_outputs():
    from support.graph_model import run_model
    status = run_model(_EFFECTORS, {})
    for nid, meta in _NODES.items():
        if meta["when"] is None:
            assert status[nid] == "succeeded"

