"""Independent conduction and when metadata for relocalize_off_goal."""
from __future__ import annotations
import json

_PATH_ID = 'relocalize_off_goal'
_NODES = {'authorize_relocalization_restore': {'atom': 'authorize_relocalization_restore',
                                      'conduction': ['classify_relocalization_residue'],
                                      'when': None},
 'build_relocalization_agent_request': {'atom': 'build_relocalization_agent_request',
                                        'conduction': ['inspect_relocalization_evidence',
                                                       'classify_relocalization_off_goal'],
                                        'when': None},
 'build_relocalization_retry': {'atom': 'build_relocalization_retry',
                                'conduction': ['validate_relocalization_agent_json'],
                                'when': None},
 'classify_relocalization_off_goal': {'atom': 'classify_relocalization_off_goal',
                                      'conduction': ['inspect_relocalization_evidence',
                                                     'read_relocalization_changed_paths',
                                                     'record_relocalization_restore'],
                                      'when': None},
 'classify_relocalization_residue': {'atom': 'classify_relocalization_residue',
                                     'conduction': ['read_relocalization_changed_paths',
                                                    'read_relocalization_issue_paths'],
                                     'when': None},
 'inspect_relocalization_evidence': {'atom': 'inspect_relocalization_evidence',
                                     'conduction': [],
                                     'when': None},
 'read_relocalization_changed_paths': {'atom': 'read_relocalization_changed_paths',
                                       'conduction': ['inspect_relocalization_evidence'],
                                       'when': None},
 'read_relocalization_issue_paths': {'atom': 'read_relocalization_issue_paths',
                                     'conduction': [],
                                     'when': None},
 'record_relocalization_restore': {'atom': 'record_relocalization_restore',
                                   'conduction': ['classify_relocalization_residue',
                                                  'authorize_relocalization_restore',
                                                  'restore_relocalization_residue'],
                                   'when': None},
 'relocalization_terminal': {'atom': 'relocalization_terminal',
                             'conduction': ['inspect_relocalization_evidence',
                                            'read_relocalization_changed_paths',
                                            'classify_relocalization_off_goal',
                                            'validate_relocalization_approval',
                                            'write_relocalization_evidence'],
                             'when': None},
 'restore_relocalization_residue': {'atom': 'restore_relocalization_residue',
                                    'conduction': ['inspect_relocalization_evidence',
                                                   'read_relocalization_changed_paths',
                                                   'authorize_relocalization_restore'],
                                    'when': {'equals': 'restore',
                                             'path': 'route',
                                             'upstream': 'authorize_relocalization_restore'}},
 'retry_relocalization_agent': {'atom': 'retry_relocalization_agent',
                                'conduction': ['inspect_relocalization_evidence',
                                               'build_relocalization_agent_request',
                                               'build_relocalization_retry'],
                                'when': {'equals': 'retry',
                                         'path': 'route',
                                         'upstream': 'build_relocalization_retry'}},
 'run_relocalization_agent': {'atom': 'run_relocalization_agent',
                              'conduction': ['inspect_relocalization_evidence',
                                             'build_relocalization_agent_request'],
                              'when': {'equals': 'agent',
                                       'path': 'route',
                                       'upstream': 'build_relocalization_agent_request'}},
 'select_relocalization_validation': {'atom': 'select_relocalization_validation',
                                      'conduction': ['run_relocalization_agent',
                                                     'validate_relocalization_agent_json',
                                                     'retry_relocalization_agent',
                                                     'validate_relocalization_retry_json'],
                                      'when': None},
 'validate_relocalization_agent_json': {'atom': 'validate_relocalization_agent_json',
                                        'conduction': ['run_relocalization_agent'],
                                        'when': None},
 'validate_relocalization_approval': {'atom': 'validate_relocalization_approval',
                                      'conduction': ['classify_relocalization_off_goal',
                                                     'select_relocalization_validation'],
                                      'when': None},
 'validate_relocalization_retry_json': {'atom': 'validate_relocalization_retry_json',
                                        'conduction': ['retry_relocalization_agent'],
                                        'when': None},
 'write_relocalization_evidence': {'atom': 'write_relocalization_evidence',
                                   'conduction': ['inspect_relocalization_evidence',
                                                  'classify_relocalization_off_goal',
                                                  'validate_relocalization_approval'],
                                   'when': {'equals': 'write',
                                            'path': 'route',
                                            'upstream': 'validate_relocalization_approval'}}}
_COND_EDGES = [('inspect_relocalization_evidence', 'read_relocalization_changed_paths'),
 ('read_relocalization_changed_paths', 'classify_relocalization_residue'),
 ('read_relocalization_issue_paths', 'classify_relocalization_residue'),
 ('classify_relocalization_residue', 'authorize_relocalization_restore'),
 ('inspect_relocalization_evidence', 'restore_relocalization_residue'),
 ('read_relocalization_changed_paths', 'restore_relocalization_residue'),
 ('authorize_relocalization_restore', 'restore_relocalization_residue'),
 ('classify_relocalization_residue', 'record_relocalization_restore'),
 ('authorize_relocalization_restore', 'record_relocalization_restore'),
 ('restore_relocalization_residue', 'record_relocalization_restore'),
 ('inspect_relocalization_evidence', 'classify_relocalization_off_goal'),
 ('read_relocalization_changed_paths', 'classify_relocalization_off_goal'),
 ('record_relocalization_restore', 'classify_relocalization_off_goal'),
 ('inspect_relocalization_evidence', 'build_relocalization_agent_request'),
 ('classify_relocalization_off_goal', 'build_relocalization_agent_request'),
 ('inspect_relocalization_evidence', 'run_relocalization_agent'),
 ('build_relocalization_agent_request', 'run_relocalization_agent'),
 ('run_relocalization_agent', 'validate_relocalization_agent_json'),
 ('validate_relocalization_agent_json', 'build_relocalization_retry'),
 ('inspect_relocalization_evidence', 'retry_relocalization_agent'),
 ('build_relocalization_agent_request', 'retry_relocalization_agent'),
 ('build_relocalization_retry', 'retry_relocalization_agent'),
 ('retry_relocalization_agent', 'validate_relocalization_retry_json'),
 ('run_relocalization_agent', 'select_relocalization_validation'),
 ('validate_relocalization_agent_json', 'select_relocalization_validation'),
 ('retry_relocalization_agent', 'select_relocalization_validation'),
 ('validate_relocalization_retry_json', 'select_relocalization_validation'),
 ('classify_relocalization_off_goal', 'validate_relocalization_approval'),
 ('select_relocalization_validation', 'validate_relocalization_approval'),
 ('inspect_relocalization_evidence', 'write_relocalization_evidence'),
 ('classify_relocalization_off_goal', 'write_relocalization_evidence'),
 ('validate_relocalization_approval', 'write_relocalization_evidence'),
 ('inspect_relocalization_evidence', 'relocalization_terminal'),
 ('read_relocalization_changed_paths', 'relocalization_terminal'),
 ('classify_relocalization_off_goal', 'relocalization_terminal'),
 ('validate_relocalization_approval', 'relocalization_terminal'),
 ('write_relocalization_evidence', 'relocalization_terminal')]
_WHEN_BRANCHES = [('restore_relocalization_residue',
  {'equals': 'restore', 'path': 'route', 'upstream': 'authorize_relocalization_restore'}),
 ('run_relocalization_agent',
  {'equals': 'agent', 'path': 'route', 'upstream': 'build_relocalization_agent_request'}),
 ('retry_relocalization_agent',
  {'equals': 'retry', 'path': 'route', 'upstream': 'build_relocalization_retry'}),
 ('write_relocalization_evidence',
  {'equals': 'write', 'path': 'route', 'upstream': 'validate_relocalization_approval'})]
_EFFECTORS = [{'conduction': [], 'id': 'inspect_relocalization_evidence', 'when': None},
 {'conduction': ['inspect_relocalization_evidence'], 'id': 'read_relocalization_changed_paths', 'when': None},
 {'conduction': [], 'id': 'read_relocalization_issue_paths', 'when': None},
 {'conduction': ['read_relocalization_changed_paths', 'read_relocalization_issue_paths'],
  'id': 'classify_relocalization_residue',
  'when': None},
 {'conduction': ['classify_relocalization_residue'], 'id': 'authorize_relocalization_restore', 'when': None},
 {'conduction': ['inspect_relocalization_evidence',
                 'read_relocalization_changed_paths',
                 'authorize_relocalization_restore'],
  'id': 'restore_relocalization_residue',
  'when': {'equals': 'restore', 'path': 'route', 'upstream': 'authorize_relocalization_restore'}},
 {'conduction': ['classify_relocalization_residue',
                 'authorize_relocalization_restore',
                 'restore_relocalization_residue'],
  'id': 'record_relocalization_restore',
  'when': None},
 {'conduction': ['inspect_relocalization_evidence',
                 'read_relocalization_changed_paths',
                 'record_relocalization_restore'],
  'id': 'classify_relocalization_off_goal',
  'when': None},
 {'conduction': ['inspect_relocalization_evidence', 'classify_relocalization_off_goal'],
  'id': 'build_relocalization_agent_request',
  'when': None},
 {'conduction': ['inspect_relocalization_evidence', 'build_relocalization_agent_request'],
  'id': 'run_relocalization_agent',
  'when': {'equals': 'agent', 'path': 'route', 'upstream': 'build_relocalization_agent_request'}},
 {'conduction': ['run_relocalization_agent'], 'id': 'validate_relocalization_agent_json', 'when': None},
 {'conduction': ['validate_relocalization_agent_json'], 'id': 'build_relocalization_retry', 'when': None},
 {'conduction': ['inspect_relocalization_evidence',
                 'build_relocalization_agent_request',
                 'build_relocalization_retry'],
  'id': 'retry_relocalization_agent',
  'when': {'equals': 'retry', 'path': 'route', 'upstream': 'build_relocalization_retry'}},
 {'conduction': ['retry_relocalization_agent'], 'id': 'validate_relocalization_retry_json', 'when': None},
 {'conduction': ['run_relocalization_agent',
                 'validate_relocalization_agent_json',
                 'retry_relocalization_agent',
                 'validate_relocalization_retry_json'],
  'id': 'select_relocalization_validation',
  'when': None},
 {'conduction': ['classify_relocalization_off_goal', 'select_relocalization_validation'],
  'id': 'validate_relocalization_approval',
  'when': None},
 {'conduction': ['inspect_relocalization_evidence',
                 'classify_relocalization_off_goal',
                 'validate_relocalization_approval'],
  'id': 'write_relocalization_evidence',
  'when': {'equals': 'write', 'path': 'route', 'upstream': 'validate_relocalization_approval'}},
 {'conduction': ['inspect_relocalization_evidence',
                 'read_relocalization_changed_paths',
                 'classify_relocalization_off_goal',
                 'validate_relocalization_approval',
                 'write_relocalization_evidence'],
  'id': 'relocalization_terminal',
  'when': None}]

def test_every_conduction_edge_is_declared():
    got = {(str(up), nid) for nid, meta in _NODES.items() for up in meta["conduction"]}
    assert got == set(tuple(edge) for edge in _COND_EDGES)

def test_every_when_branch_is_declared():
    got = {(nid, json.dumps(meta["when"], sort_keys=True)) for nid, meta in _NODES.items() if meta["when"]}
    want = {(nid, json.dumps(when, sort_keys=True)) for nid, when in _WHEN_BRANCHES}
    assert got == want

def test_when_upstream_is_a_direct_parent():
    for nid, when in _WHEN_BRANCHES:
        assert when["upstream"] in _NODES[nid]["conduction"]

def test_unconditional_nodes_succeed_without_outputs():
    from support.graph_model import run_model
    status = run_model(_EFFECTORS, {})
    for nid, meta in _NODES.items():
        if meta["when"] is None:
            assert status[nid] == "succeeded"

