"""Native Fala host_run_package proofs for product_pass_budget."""
from __future__ import annotations

import pytest

_PATH_ID = 'product_pass_budget'
_EFFECTORS = [{'conduction': [], 'id': 'prepare_product_budget', 'when': None},
 {'conduction': ['prepare_product_budget'], 'id': 'select_product_pass_slot_1', 'when': None},
 {'conduction': ['select_product_pass_slot_1'],
  'id': 'run_product_factory_pass_1',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_1'}},
 {'conduction': ['select_product_pass_slot_1', 'run_product_factory_pass_1'],
  'id': 'run_product_leftover_closeout_1',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_1'}},
 {'conduction': ['run_product_factory_pass_1', 'run_product_leftover_closeout_1'],
  'id': 'apply_product_leftover_1',
  'when': None},
 {'conduction': ['select_product_pass_slot_1', 'apply_product_leftover_1'],
  'id': 'record_product_pass_1',
  'when': None},
 {'conduction': ['prepare_product_budget', 'record_product_pass_1'],
  'id': 'classify_product_pass_1',
  'when': None},
 {'conduction': ['classify_product_pass_1'], 'id': 'classify_product_plateau_1', 'when': None},
 {'conduction': ['prepare_product_budget', 'classify_product_plateau_1'],
  'id': 'decide_product_pass_stop_1',
  'when': None},
 {'conduction': ['prepare_product_budget', 'decide_product_pass_stop_1'],
  'id': 'finalize_product_pass_1',
  'when': None},
 {'conduction': ['prepare_product_budget', 'finalize_product_pass_1'],
  'id': 'select_product_pass_slot_2',
  'when': None},
 {'conduction': ['select_product_pass_slot_2'],
  'id': 'run_product_factory_pass_2',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_2'}},
 {'conduction': ['select_product_pass_slot_2', 'run_product_factory_pass_2'],
  'id': 'run_product_leftover_closeout_2',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_2'}},
 {'conduction': ['run_product_factory_pass_2', 'run_product_leftover_closeout_2'],
  'id': 'apply_product_leftover_2',
  'when': None},
 {'conduction': ['select_product_pass_slot_2', 'apply_product_leftover_2', 'finalize_product_pass_1'],
  'id': 'record_product_pass_2',
  'when': None},
 {'conduction': ['prepare_product_budget', 'record_product_pass_2'],
  'id': 'classify_product_pass_2',
  'when': None},
 {'conduction': ['classify_product_pass_2'], 'id': 'classify_product_plateau_2', 'when': None},
 {'conduction': ['prepare_product_budget', 'classify_product_plateau_2'],
  'id': 'decide_product_pass_stop_2',
  'when': None},
 {'conduction': ['prepare_product_budget', 'decide_product_pass_stop_2'],
  'id': 'finalize_product_pass_2',
  'when': None},
 {'conduction': ['prepare_product_budget', 'finalize_product_pass_2'],
  'id': 'select_product_pass_slot_3',
  'when': None},
 {'conduction': ['select_product_pass_slot_3'],
  'id': 'run_product_factory_pass_3',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_3'}},
 {'conduction': ['select_product_pass_slot_3', 'run_product_factory_pass_3'],
  'id': 'run_product_leftover_closeout_3',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_3'}},
 {'conduction': ['run_product_factory_pass_3', 'run_product_leftover_closeout_3'],
  'id': 'apply_product_leftover_3',
  'when': None},
 {'conduction': ['select_product_pass_slot_3', 'apply_product_leftover_3', 'finalize_product_pass_2'],
  'id': 'record_product_pass_3',
  'when': None},
 {'conduction': ['prepare_product_budget', 'record_product_pass_3'],
  'id': 'classify_product_pass_3',
  'when': None},
 {'conduction': ['classify_product_pass_3'], 'id': 'classify_product_plateau_3', 'when': None},
 {'conduction': ['prepare_product_budget', 'classify_product_plateau_3'],
  'id': 'decide_product_pass_stop_3',
  'when': None},
 {'conduction': ['prepare_product_budget', 'decide_product_pass_stop_3'],
  'id': 'finalize_product_pass_3',
  'when': None},
 {'conduction': ['prepare_product_budget', 'finalize_product_pass_3'],
  'id': 'select_product_pass_slot_4',
  'when': None},
 {'conduction': ['select_product_pass_slot_4'],
  'id': 'run_product_factory_pass_4',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_4'}},
 {'conduction': ['select_product_pass_slot_4', 'run_product_factory_pass_4'],
  'id': 'run_product_leftover_closeout_4',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_4'}},
 {'conduction': ['run_product_factory_pass_4', 'run_product_leftover_closeout_4'],
  'id': 'apply_product_leftover_4',
  'when': None},
 {'conduction': ['select_product_pass_slot_4', 'apply_product_leftover_4', 'finalize_product_pass_3'],
  'id': 'record_product_pass_4',
  'when': None},
 {'conduction': ['prepare_product_budget', 'record_product_pass_4'],
  'id': 'classify_product_pass_4',
  'when': None},
 {'conduction': ['classify_product_pass_4'], 'id': 'classify_product_plateau_4', 'when': None},
 {'conduction': ['prepare_product_budget', 'classify_product_plateau_4'],
  'id': 'decide_product_pass_stop_4',
  'when': None},
 {'conduction': ['prepare_product_budget', 'decide_product_pass_stop_4'],
  'id': 'finalize_product_pass_4',
  'when': None},
 {'conduction': ['prepare_product_budget', 'finalize_product_pass_4'],
  'id': 'select_product_pass_slot_5',
  'when': None},
 {'conduction': ['select_product_pass_slot_5'],
  'id': 'run_product_factory_pass_5',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_5'}},
 {'conduction': ['select_product_pass_slot_5', 'run_product_factory_pass_5'],
  'id': 'run_product_leftover_closeout_5',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_5'}},
 {'conduction': ['run_product_factory_pass_5', 'run_product_leftover_closeout_5'],
  'id': 'apply_product_leftover_5',
  'when': None},
 {'conduction': ['select_product_pass_slot_5', 'apply_product_leftover_5', 'finalize_product_pass_4'],
  'id': 'record_product_pass_5',
  'when': None},
 {'conduction': ['prepare_product_budget', 'record_product_pass_5'],
  'id': 'classify_product_pass_5',
  'when': None},
 {'conduction': ['classify_product_pass_5'], 'id': 'classify_product_plateau_5', 'when': None},
 {'conduction': ['prepare_product_budget', 'classify_product_plateau_5'],
  'id': 'decide_product_pass_stop_5',
  'when': None},
 {'conduction': ['prepare_product_budget', 'decide_product_pass_stop_5'],
  'id': 'finalize_product_pass_5',
  'when': None},
 {'conduction': ['prepare_product_budget', 'finalize_product_pass_5'],
  'id': 'select_product_pass_slot_6',
  'when': None},
 {'conduction': ['select_product_pass_slot_6'],
  'id': 'run_product_factory_pass_6',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_6'}},
 {'conduction': ['select_product_pass_slot_6', 'run_product_factory_pass_6'],
  'id': 'run_product_leftover_closeout_6',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_6'}},
 {'conduction': ['run_product_factory_pass_6', 'run_product_leftover_closeout_6'],
  'id': 'apply_product_leftover_6',
  'when': None},
 {'conduction': ['select_product_pass_slot_6', 'apply_product_leftover_6', 'finalize_product_pass_5'],
  'id': 'record_product_pass_6',
  'when': None},
 {'conduction': ['prepare_product_budget', 'record_product_pass_6'],
  'id': 'classify_product_pass_6',
  'when': None},
 {'conduction': ['classify_product_pass_6'], 'id': 'classify_product_plateau_6', 'when': None},
 {'conduction': ['prepare_product_budget', 'classify_product_plateau_6'],
  'id': 'decide_product_pass_stop_6',
  'when': None},
 {'conduction': ['prepare_product_budget', 'decide_product_pass_stop_6'],
  'id': 'finalize_product_pass_6',
  'when': None},
 {'conduction': ['prepare_product_budget', 'finalize_product_pass_6'],
  'id': 'select_product_pass_slot_7',
  'when': None},
 {'conduction': ['select_product_pass_slot_7'],
  'id': 'run_product_factory_pass_7',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_7'}},
 {'conduction': ['select_product_pass_slot_7', 'run_product_factory_pass_7'],
  'id': 'run_product_leftover_closeout_7',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_7'}},
 {'conduction': ['run_product_factory_pass_7', 'run_product_leftover_closeout_7'],
  'id': 'apply_product_leftover_7',
  'when': None},
 {'conduction': ['select_product_pass_slot_7', 'apply_product_leftover_7', 'finalize_product_pass_6'],
  'id': 'record_product_pass_7',
  'when': None},
 {'conduction': ['prepare_product_budget', 'record_product_pass_7'],
  'id': 'classify_product_pass_7',
  'when': None},
 {'conduction': ['classify_product_pass_7'], 'id': 'classify_product_plateau_7', 'when': None},
 {'conduction': ['prepare_product_budget', 'classify_product_plateau_7'],
  'id': 'decide_product_pass_stop_7',
  'when': None},
 {'conduction': ['prepare_product_budget', 'decide_product_pass_stop_7'],
  'id': 'finalize_product_pass_7',
  'when': None},
 {'conduction': ['prepare_product_budget', 'finalize_product_pass_7'],
  'id': 'select_product_pass_slot_8',
  'when': None},
 {'conduction': ['select_product_pass_slot_8'],
  'id': 'run_product_factory_pass_8',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_8'}},
 {'conduction': ['select_product_pass_slot_8', 'run_product_factory_pass_8'],
  'id': 'run_product_leftover_closeout_8',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_8'}},
 {'conduction': ['run_product_factory_pass_8', 'run_product_leftover_closeout_8'],
  'id': 'apply_product_leftover_8',
  'when': None},
 {'conduction': ['select_product_pass_slot_8', 'apply_product_leftover_8', 'finalize_product_pass_7'],
  'id': 'record_product_pass_8',
  'when': None},
 {'conduction': ['prepare_product_budget', 'record_product_pass_8'],
  'id': 'classify_product_pass_8',
  'when': None},
 {'conduction': ['classify_product_pass_8'], 'id': 'classify_product_plateau_8', 'when': None},
 {'conduction': ['prepare_product_budget', 'classify_product_plateau_8'],
  'id': 'decide_product_pass_stop_8',
  'when': None},
 {'conduction': ['prepare_product_budget', 'decide_product_pass_stop_8'],
  'id': 'finalize_product_pass_8',
  'when': None},
 {'conduction': ['prepare_product_budget',
                 'finalize_product_pass_1',
                 'finalize_product_pass_2',
                 'finalize_product_pass_3',
                 'finalize_product_pass_4',
                 'finalize_product_pass_5',
                 'finalize_product_pass_6',
                 'finalize_product_pass_7',
                 'finalize_product_pass_8'],
  'id': 'select_product_budget_result',
  'when': None}]
_MATCH = {'select_product_pass_slot_1': {'route': 'run'},
 'select_product_pass_slot_2': {'route': 'run'},
 'select_product_pass_slot_3': {'route': 'run'},
 'select_product_pass_slot_4': {'route': 'run'},
 'select_product_pass_slot_5': {'route': 'run'},
 'select_product_pass_slot_6': {'route': 'run'},
 'select_product_pass_slot_7': {'route': 'run'},
 'select_product_pass_slot_8': {'route': 'run'}}
_MISS = {'select_product_pass_slot_1': {'route': 'not-run'},
 'select_product_pass_slot_2': {'route': 'not-run'},
 'select_product_pass_slot_3': {'route': 'not-run'},
 'select_product_pass_slot_4': {'route': 'not-run'},
 'select_product_pass_slot_5': {'route': 'not-run'},
 'select_product_pass_slot_6': {'route': 'not-run'},
 'select_product_pass_slot_7': {'route': 'not-run'},
 'select_product_pass_slot_8': {'route': 'not-run'}}
_MAX_TICKS = 296

def test_model_match_and_miss_differ_when_branches_exist():
    from support.graph_model import run_model
    matched = run_model(_EFFECTORS, _MATCH)
    missed = run_model(_EFFECTORS, _MISS)
    if _MATCH:
        assert matched != missed
    for item in _EFFECTORS:
        assert matched[item["id"]] in {"succeeded", "skipped"}
        assert missed[item["id"]] in {"succeeded", "skipped"}

def test_native_match_skips_nonmatching_adapters(tmp_path):
    from support.graph_model import node_status_map, run_model
    from support.native_path import run_overridden_path
    expected = run_model(_EFFECTORS, _MATCH)
    result = run_overridden_path(tmp_path, _PATH_ID, _MATCH, run_id="match", max_ticks=_MAX_TICKS)
    assert result.get("run_status") == "completed"
    native = node_status_map(result)
    assert native == expected
    ran = set(result.get("_ran") or [])
    for nid, status in native.items():
        if status == "skipped":
            assert nid not in ran
        elif status == "succeeded":
            assert nid in ran

def test_native_miss_skips_matching_when_branches(tmp_path):
    from support.graph_model import node_status_map, run_model
    from support.native_path import run_overridden_path
    if not _MISS:
        pytest.skip("path has no when branches")
    expected = run_model(_EFFECTORS, _MISS)
    result = run_overridden_path(tmp_path, _PATH_ID, _MISS, run_id="miss", max_ticks=_MAX_TICKS)
    assert result.get("run_status") == "completed"
    native = node_status_map(result)
    assert native == expected
    ran = set(result.get("_ran") or [])
    for nid, status in native.items():
        if status == "skipped":
            assert nid not in ran
