"""Independent conduction and when metadata for product_pass_budget."""
from __future__ import annotations
import json

_PATH_ID = 'product_pass_budget'
_NODES = {'apply_product_leftover_1': {'atom': 'apply_product_leftover_1',
                              'conduction': ['run_product_factory_pass_1', 'run_product_leftover_closeout_1'],
                              'when': None},
 'apply_product_leftover_2': {'atom': 'apply_product_leftover_2',
                              'conduction': ['run_product_factory_pass_2', 'run_product_leftover_closeout_2'],
                              'when': None},
 'apply_product_leftover_3': {'atom': 'apply_product_leftover_3',
                              'conduction': ['run_product_factory_pass_3', 'run_product_leftover_closeout_3'],
                              'when': None},
 'apply_product_leftover_4': {'atom': 'apply_product_leftover_4',
                              'conduction': ['run_product_factory_pass_4', 'run_product_leftover_closeout_4'],
                              'when': None},
 'apply_product_leftover_5': {'atom': 'apply_product_leftover_5',
                              'conduction': ['run_product_factory_pass_5', 'run_product_leftover_closeout_5'],
                              'when': None},
 'apply_product_leftover_6': {'atom': 'apply_product_leftover_6',
                              'conduction': ['run_product_factory_pass_6', 'run_product_leftover_closeout_6'],
                              'when': None},
 'apply_product_leftover_7': {'atom': 'apply_product_leftover_7',
                              'conduction': ['run_product_factory_pass_7', 'run_product_leftover_closeout_7'],
                              'when': None},
 'apply_product_leftover_8': {'atom': 'apply_product_leftover_8',
                              'conduction': ['run_product_factory_pass_8', 'run_product_leftover_closeout_8'],
                              'when': None},
 'classify_product_pass_1': {'atom': 'classify_product_pass_1',
                             'conduction': ['prepare_product_budget', 'record_product_pass_1'],
                             'when': None},
 'classify_product_pass_2': {'atom': 'classify_product_pass_2',
                             'conduction': ['prepare_product_budget', 'record_product_pass_2'],
                             'when': None},
 'classify_product_pass_3': {'atom': 'classify_product_pass_3',
                             'conduction': ['prepare_product_budget', 'record_product_pass_3'],
                             'when': None},
 'classify_product_pass_4': {'atom': 'classify_product_pass_4',
                             'conduction': ['prepare_product_budget', 'record_product_pass_4'],
                             'when': None},
 'classify_product_pass_5': {'atom': 'classify_product_pass_5',
                             'conduction': ['prepare_product_budget', 'record_product_pass_5'],
                             'when': None},
 'classify_product_pass_6': {'atom': 'classify_product_pass_6',
                             'conduction': ['prepare_product_budget', 'record_product_pass_6'],
                             'when': None},
 'classify_product_pass_7': {'atom': 'classify_product_pass_7',
                             'conduction': ['prepare_product_budget', 'record_product_pass_7'],
                             'when': None},
 'classify_product_pass_8': {'atom': 'classify_product_pass_8',
                             'conduction': ['prepare_product_budget', 'record_product_pass_8'],
                             'when': None},
 'classify_product_plateau_1': {'atom': 'classify_product_plateau_1',
                                'conduction': ['classify_product_pass_1'],
                                'when': None},
 'classify_product_plateau_2': {'atom': 'classify_product_plateau_2',
                                'conduction': ['classify_product_pass_2'],
                                'when': None},
 'classify_product_plateau_3': {'atom': 'classify_product_plateau_3',
                                'conduction': ['classify_product_pass_3'],
                                'when': None},
 'classify_product_plateau_4': {'atom': 'classify_product_plateau_4',
                                'conduction': ['classify_product_pass_4'],
                                'when': None},
 'classify_product_plateau_5': {'atom': 'classify_product_plateau_5',
                                'conduction': ['classify_product_pass_5'],
                                'when': None},
 'classify_product_plateau_6': {'atom': 'classify_product_plateau_6',
                                'conduction': ['classify_product_pass_6'],
                                'when': None},
 'classify_product_plateau_7': {'atom': 'classify_product_plateau_7',
                                'conduction': ['classify_product_pass_7'],
                                'when': None},
 'classify_product_plateau_8': {'atom': 'classify_product_plateau_8',
                                'conduction': ['classify_product_pass_8'],
                                'when': None},
 'decide_product_pass_stop_1': {'atom': 'decide_product_pass_stop_1',
                                'conduction': ['prepare_product_budget', 'classify_product_plateau_1'],
                                'when': None},
 'decide_product_pass_stop_2': {'atom': 'decide_product_pass_stop_2',
                                'conduction': ['prepare_product_budget', 'classify_product_plateau_2'],
                                'when': None},
 'decide_product_pass_stop_3': {'atom': 'decide_product_pass_stop_3',
                                'conduction': ['prepare_product_budget', 'classify_product_plateau_3'],
                                'when': None},
 'decide_product_pass_stop_4': {'atom': 'decide_product_pass_stop_4',
                                'conduction': ['prepare_product_budget', 'classify_product_plateau_4'],
                                'when': None},
 'decide_product_pass_stop_5': {'atom': 'decide_product_pass_stop_5',
                                'conduction': ['prepare_product_budget', 'classify_product_plateau_5'],
                                'when': None},
 'decide_product_pass_stop_6': {'atom': 'decide_product_pass_stop_6',
                                'conduction': ['prepare_product_budget', 'classify_product_plateau_6'],
                                'when': None},
 'decide_product_pass_stop_7': {'atom': 'decide_product_pass_stop_7',
                                'conduction': ['prepare_product_budget', 'classify_product_plateau_7'],
                                'when': None},
 'decide_product_pass_stop_8': {'atom': 'decide_product_pass_stop_8',
                                'conduction': ['prepare_product_budget', 'classify_product_plateau_8'],
                                'when': None},
 'finalize_product_pass_1': {'atom': 'finalize_product_pass_1',
                             'conduction': ['prepare_product_budget', 'decide_product_pass_stop_1'],
                             'when': None},
 'finalize_product_pass_2': {'atom': 'finalize_product_pass_2',
                             'conduction': ['prepare_product_budget', 'decide_product_pass_stop_2'],
                             'when': None},
 'finalize_product_pass_3': {'atom': 'finalize_product_pass_3',
                             'conduction': ['prepare_product_budget', 'decide_product_pass_stop_3'],
                             'when': None},
 'finalize_product_pass_4': {'atom': 'finalize_product_pass_4',
                             'conduction': ['prepare_product_budget', 'decide_product_pass_stop_4'],
                             'when': None},
 'finalize_product_pass_5': {'atom': 'finalize_product_pass_5',
                             'conduction': ['prepare_product_budget', 'decide_product_pass_stop_5'],
                             'when': None},
 'finalize_product_pass_6': {'atom': 'finalize_product_pass_6',
                             'conduction': ['prepare_product_budget', 'decide_product_pass_stop_6'],
                             'when': None},
 'finalize_product_pass_7': {'atom': 'finalize_product_pass_7',
                             'conduction': ['prepare_product_budget', 'decide_product_pass_stop_7'],
                             'when': None},
 'finalize_product_pass_8': {'atom': 'finalize_product_pass_8',
                             'conduction': ['prepare_product_budget', 'decide_product_pass_stop_8'],
                             'when': None},
 'prepare_product_budget': {'atom': 'prepare_product_budget', 'conduction': [], 'when': None},
 'record_product_pass_1': {'atom': 'record_product_pass_1',
                           'conduction': ['select_product_pass_slot_1', 'apply_product_leftover_1'],
                           'when': None},
 'record_product_pass_2': {'atom': 'record_product_pass_2',
                           'conduction': ['select_product_pass_slot_2',
                                          'apply_product_leftover_2',
                                          'finalize_product_pass_1'],
                           'when': None},
 'record_product_pass_3': {'atom': 'record_product_pass_3',
                           'conduction': ['select_product_pass_slot_3',
                                          'apply_product_leftover_3',
                                          'finalize_product_pass_2'],
                           'when': None},
 'record_product_pass_4': {'atom': 'record_product_pass_4',
                           'conduction': ['select_product_pass_slot_4',
                                          'apply_product_leftover_4',
                                          'finalize_product_pass_3'],
                           'when': None},
 'record_product_pass_5': {'atom': 'record_product_pass_5',
                           'conduction': ['select_product_pass_slot_5',
                                          'apply_product_leftover_5',
                                          'finalize_product_pass_4'],
                           'when': None},
 'record_product_pass_6': {'atom': 'record_product_pass_6',
                           'conduction': ['select_product_pass_slot_6',
                                          'apply_product_leftover_6',
                                          'finalize_product_pass_5'],
                           'when': None},
 'record_product_pass_7': {'atom': 'record_product_pass_7',
                           'conduction': ['select_product_pass_slot_7',
                                          'apply_product_leftover_7',
                                          'finalize_product_pass_6'],
                           'when': None},
 'record_product_pass_8': {'atom': 'record_product_pass_8',
                           'conduction': ['select_product_pass_slot_8',
                                          'apply_product_leftover_8',
                                          'finalize_product_pass_7'],
                           'when': None},
 'run_product_factory_pass_1': {'atom': 'run_product_factory_pass_1',
                                'conduction': ['select_product_pass_slot_1'],
                                'when': {'equals': 'run',
                                         'path': 'route',
                                         'upstream': 'select_product_pass_slot_1'}},
 'run_product_factory_pass_2': {'atom': 'run_product_factory_pass_2',
                                'conduction': ['select_product_pass_slot_2'],
                                'when': {'equals': 'run',
                                         'path': 'route',
                                         'upstream': 'select_product_pass_slot_2'}},
 'run_product_factory_pass_3': {'atom': 'run_product_factory_pass_3',
                                'conduction': ['select_product_pass_slot_3'],
                                'when': {'equals': 'run',
                                         'path': 'route',
                                         'upstream': 'select_product_pass_slot_3'}},
 'run_product_factory_pass_4': {'atom': 'run_product_factory_pass_4',
                                'conduction': ['select_product_pass_slot_4'],
                                'when': {'equals': 'run',
                                         'path': 'route',
                                         'upstream': 'select_product_pass_slot_4'}},
 'run_product_factory_pass_5': {'atom': 'run_product_factory_pass_5',
                                'conduction': ['select_product_pass_slot_5'],
                                'when': {'equals': 'run',
                                         'path': 'route',
                                         'upstream': 'select_product_pass_slot_5'}},
 'run_product_factory_pass_6': {'atom': 'run_product_factory_pass_6',
                                'conduction': ['select_product_pass_slot_6'],
                                'when': {'equals': 'run',
                                         'path': 'route',
                                         'upstream': 'select_product_pass_slot_6'}},
 'run_product_factory_pass_7': {'atom': 'run_product_factory_pass_7',
                                'conduction': ['select_product_pass_slot_7'],
                                'when': {'equals': 'run',
                                         'path': 'route',
                                         'upstream': 'select_product_pass_slot_7'}},
 'run_product_factory_pass_8': {'atom': 'run_product_factory_pass_8',
                                'conduction': ['select_product_pass_slot_8'],
                                'when': {'equals': 'run',
                                         'path': 'route',
                                         'upstream': 'select_product_pass_slot_8'}},
 'run_product_leftover_closeout_1': {'atom': 'run_product_leftover_closeout_1',
                                     'conduction': ['select_product_pass_slot_1',
                                                    'run_product_factory_pass_1'],
                                     'when': {'equals': 'run',
                                              'path': 'route',
                                              'upstream': 'select_product_pass_slot_1'}},
 'run_product_leftover_closeout_2': {'atom': 'run_product_leftover_closeout_2',
                                     'conduction': ['select_product_pass_slot_2',
                                                    'run_product_factory_pass_2'],
                                     'when': {'equals': 'run',
                                              'path': 'route',
                                              'upstream': 'select_product_pass_slot_2'}},
 'run_product_leftover_closeout_3': {'atom': 'run_product_leftover_closeout_3',
                                     'conduction': ['select_product_pass_slot_3',
                                                    'run_product_factory_pass_3'],
                                     'when': {'equals': 'run',
                                              'path': 'route',
                                              'upstream': 'select_product_pass_slot_3'}},
 'run_product_leftover_closeout_4': {'atom': 'run_product_leftover_closeout_4',
                                     'conduction': ['select_product_pass_slot_4',
                                                    'run_product_factory_pass_4'],
                                     'when': {'equals': 'run',
                                              'path': 'route',
                                              'upstream': 'select_product_pass_slot_4'}},
 'run_product_leftover_closeout_5': {'atom': 'run_product_leftover_closeout_5',
                                     'conduction': ['select_product_pass_slot_5',
                                                    'run_product_factory_pass_5'],
                                     'when': {'equals': 'run',
                                              'path': 'route',
                                              'upstream': 'select_product_pass_slot_5'}},
 'run_product_leftover_closeout_6': {'atom': 'run_product_leftover_closeout_6',
                                     'conduction': ['select_product_pass_slot_6',
                                                    'run_product_factory_pass_6'],
                                     'when': {'equals': 'run',
                                              'path': 'route',
                                              'upstream': 'select_product_pass_slot_6'}},
 'run_product_leftover_closeout_7': {'atom': 'run_product_leftover_closeout_7',
                                     'conduction': ['select_product_pass_slot_7',
                                                    'run_product_factory_pass_7'],
                                     'when': {'equals': 'run',
                                              'path': 'route',
                                              'upstream': 'select_product_pass_slot_7'}},
 'run_product_leftover_closeout_8': {'atom': 'run_product_leftover_closeout_8',
                                     'conduction': ['select_product_pass_slot_8',
                                                    'run_product_factory_pass_8'],
                                     'when': {'equals': 'run',
                                              'path': 'route',
                                              'upstream': 'select_product_pass_slot_8'}},
 'select_product_budget_result': {'atom': 'select_product_budget_result',
                                  'conduction': ['prepare_product_budget',
                                                 'finalize_product_pass_1',
                                                 'finalize_product_pass_2',
                                                 'finalize_product_pass_3',
                                                 'finalize_product_pass_4',
                                                 'finalize_product_pass_5',
                                                 'finalize_product_pass_6',
                                                 'finalize_product_pass_7',
                                                 'finalize_product_pass_8'],
                                  'when': None},
 'select_product_pass_slot_1': {'atom': 'select_product_pass_slot_1',
                                'conduction': ['prepare_product_budget'],
                                'when': None},
 'select_product_pass_slot_2': {'atom': 'select_product_pass_slot_2',
                                'conduction': ['prepare_product_budget', 'finalize_product_pass_1'],
                                'when': None},
 'select_product_pass_slot_3': {'atom': 'select_product_pass_slot_3',
                                'conduction': ['prepare_product_budget', 'finalize_product_pass_2'],
                                'when': None},
 'select_product_pass_slot_4': {'atom': 'select_product_pass_slot_4',
                                'conduction': ['prepare_product_budget', 'finalize_product_pass_3'],
                                'when': None},
 'select_product_pass_slot_5': {'atom': 'select_product_pass_slot_5',
                                'conduction': ['prepare_product_budget', 'finalize_product_pass_4'],
                                'when': None},
 'select_product_pass_slot_6': {'atom': 'select_product_pass_slot_6',
                                'conduction': ['prepare_product_budget', 'finalize_product_pass_5'],
                                'when': None},
 'select_product_pass_slot_7': {'atom': 'select_product_pass_slot_7',
                                'conduction': ['prepare_product_budget', 'finalize_product_pass_6'],
                                'when': None},
 'select_product_pass_slot_8': {'atom': 'select_product_pass_slot_8',
                                'conduction': ['prepare_product_budget', 'finalize_product_pass_7'],
                                'when': None}}
_COND_EDGES = [('prepare_product_budget', 'select_product_pass_slot_1'),
 ('select_product_pass_slot_1', 'run_product_factory_pass_1'),
 ('select_product_pass_slot_1', 'run_product_leftover_closeout_1'),
 ('run_product_factory_pass_1', 'run_product_leftover_closeout_1'),
 ('run_product_factory_pass_1', 'apply_product_leftover_1'),
 ('run_product_leftover_closeout_1', 'apply_product_leftover_1'),
 ('select_product_pass_slot_1', 'record_product_pass_1'),
 ('apply_product_leftover_1', 'record_product_pass_1'),
 ('prepare_product_budget', 'classify_product_pass_1'),
 ('record_product_pass_1', 'classify_product_pass_1'),
 ('classify_product_pass_1', 'classify_product_plateau_1'),
 ('prepare_product_budget', 'decide_product_pass_stop_1'),
 ('classify_product_plateau_1', 'decide_product_pass_stop_1'),
 ('prepare_product_budget', 'finalize_product_pass_1'),
 ('decide_product_pass_stop_1', 'finalize_product_pass_1'),
 ('prepare_product_budget', 'select_product_pass_slot_2'),
 ('finalize_product_pass_1', 'select_product_pass_slot_2'),
 ('select_product_pass_slot_2', 'run_product_factory_pass_2'),
 ('select_product_pass_slot_2', 'run_product_leftover_closeout_2'),
 ('run_product_factory_pass_2', 'run_product_leftover_closeout_2'),
 ('run_product_factory_pass_2', 'apply_product_leftover_2'),
 ('run_product_leftover_closeout_2', 'apply_product_leftover_2'),
 ('select_product_pass_slot_2', 'record_product_pass_2'),
 ('apply_product_leftover_2', 'record_product_pass_2'),
 ('finalize_product_pass_1', 'record_product_pass_2'),
 ('prepare_product_budget', 'classify_product_pass_2'),
 ('record_product_pass_2', 'classify_product_pass_2'),
 ('classify_product_pass_2', 'classify_product_plateau_2'),
 ('prepare_product_budget', 'decide_product_pass_stop_2'),
 ('classify_product_plateau_2', 'decide_product_pass_stop_2'),
 ('prepare_product_budget', 'finalize_product_pass_2'),
 ('decide_product_pass_stop_2', 'finalize_product_pass_2'),
 ('prepare_product_budget', 'select_product_pass_slot_3'),
 ('finalize_product_pass_2', 'select_product_pass_slot_3'),
 ('select_product_pass_slot_3', 'run_product_factory_pass_3'),
 ('select_product_pass_slot_3', 'run_product_leftover_closeout_3'),
 ('run_product_factory_pass_3', 'run_product_leftover_closeout_3'),
 ('run_product_factory_pass_3', 'apply_product_leftover_3'),
 ('run_product_leftover_closeout_3', 'apply_product_leftover_3'),
 ('select_product_pass_slot_3', 'record_product_pass_3'),
 ('apply_product_leftover_3', 'record_product_pass_3'),
 ('finalize_product_pass_2', 'record_product_pass_3'),
 ('prepare_product_budget', 'classify_product_pass_3'),
 ('record_product_pass_3', 'classify_product_pass_3'),
 ('classify_product_pass_3', 'classify_product_plateau_3'),
 ('prepare_product_budget', 'decide_product_pass_stop_3'),
 ('classify_product_plateau_3', 'decide_product_pass_stop_3'),
 ('prepare_product_budget', 'finalize_product_pass_3'),
 ('decide_product_pass_stop_3', 'finalize_product_pass_3'),
 ('prepare_product_budget', 'select_product_pass_slot_4'),
 ('finalize_product_pass_3', 'select_product_pass_slot_4'),
 ('select_product_pass_slot_4', 'run_product_factory_pass_4'),
 ('select_product_pass_slot_4', 'run_product_leftover_closeout_4'),
 ('run_product_factory_pass_4', 'run_product_leftover_closeout_4'),
 ('run_product_factory_pass_4', 'apply_product_leftover_4'),
 ('run_product_leftover_closeout_4', 'apply_product_leftover_4'),
 ('select_product_pass_slot_4', 'record_product_pass_4'),
 ('apply_product_leftover_4', 'record_product_pass_4'),
 ('finalize_product_pass_3', 'record_product_pass_4'),
 ('prepare_product_budget', 'classify_product_pass_4'),
 ('record_product_pass_4', 'classify_product_pass_4'),
 ('classify_product_pass_4', 'classify_product_plateau_4'),
 ('prepare_product_budget', 'decide_product_pass_stop_4'),
 ('classify_product_plateau_4', 'decide_product_pass_stop_4'),
 ('prepare_product_budget', 'finalize_product_pass_4'),
 ('decide_product_pass_stop_4', 'finalize_product_pass_4'),
 ('prepare_product_budget', 'select_product_pass_slot_5'),
 ('finalize_product_pass_4', 'select_product_pass_slot_5'),
 ('select_product_pass_slot_5', 'run_product_factory_pass_5'),
 ('select_product_pass_slot_5', 'run_product_leftover_closeout_5'),
 ('run_product_factory_pass_5', 'run_product_leftover_closeout_5'),
 ('run_product_factory_pass_5', 'apply_product_leftover_5'),
 ('run_product_leftover_closeout_5', 'apply_product_leftover_5'),
 ('select_product_pass_slot_5', 'record_product_pass_5'),
 ('apply_product_leftover_5', 'record_product_pass_5'),
 ('finalize_product_pass_4', 'record_product_pass_5'),
 ('prepare_product_budget', 'classify_product_pass_5'),
 ('record_product_pass_5', 'classify_product_pass_5'),
 ('classify_product_pass_5', 'classify_product_plateau_5'),
 ('prepare_product_budget', 'decide_product_pass_stop_5'),
 ('classify_product_plateau_5', 'decide_product_pass_stop_5'),
 ('prepare_product_budget', 'finalize_product_pass_5'),
 ('decide_product_pass_stop_5', 'finalize_product_pass_5'),
 ('prepare_product_budget', 'select_product_pass_slot_6'),
 ('finalize_product_pass_5', 'select_product_pass_slot_6'),
 ('select_product_pass_slot_6', 'run_product_factory_pass_6'),
 ('select_product_pass_slot_6', 'run_product_leftover_closeout_6'),
 ('run_product_factory_pass_6', 'run_product_leftover_closeout_6'),
 ('run_product_factory_pass_6', 'apply_product_leftover_6'),
 ('run_product_leftover_closeout_6', 'apply_product_leftover_6'),
 ('select_product_pass_slot_6', 'record_product_pass_6'),
 ('apply_product_leftover_6', 'record_product_pass_6'),
 ('finalize_product_pass_5', 'record_product_pass_6'),
 ('prepare_product_budget', 'classify_product_pass_6'),
 ('record_product_pass_6', 'classify_product_pass_6'),
 ('classify_product_pass_6', 'classify_product_plateau_6'),
 ('prepare_product_budget', 'decide_product_pass_stop_6'),
 ('classify_product_plateau_6', 'decide_product_pass_stop_6'),
 ('prepare_product_budget', 'finalize_product_pass_6'),
 ('decide_product_pass_stop_6', 'finalize_product_pass_6'),
 ('prepare_product_budget', 'select_product_pass_slot_7'),
 ('finalize_product_pass_6', 'select_product_pass_slot_7'),
 ('select_product_pass_slot_7', 'run_product_factory_pass_7'),
 ('select_product_pass_slot_7', 'run_product_leftover_closeout_7'),
 ('run_product_factory_pass_7', 'run_product_leftover_closeout_7'),
 ('run_product_factory_pass_7', 'apply_product_leftover_7'),
 ('run_product_leftover_closeout_7', 'apply_product_leftover_7'),
 ('select_product_pass_slot_7', 'record_product_pass_7'),
 ('apply_product_leftover_7', 'record_product_pass_7'),
 ('finalize_product_pass_6', 'record_product_pass_7'),
 ('prepare_product_budget', 'classify_product_pass_7'),
 ('record_product_pass_7', 'classify_product_pass_7'),
 ('classify_product_pass_7', 'classify_product_plateau_7'),
 ('prepare_product_budget', 'decide_product_pass_stop_7'),
 ('classify_product_plateau_7', 'decide_product_pass_stop_7'),
 ('prepare_product_budget', 'finalize_product_pass_7'),
 ('decide_product_pass_stop_7', 'finalize_product_pass_7'),
 ('prepare_product_budget', 'select_product_pass_slot_8'),
 ('finalize_product_pass_7', 'select_product_pass_slot_8'),
 ('select_product_pass_slot_8', 'run_product_factory_pass_8'),
 ('select_product_pass_slot_8', 'run_product_leftover_closeout_8'),
 ('run_product_factory_pass_8', 'run_product_leftover_closeout_8'),
 ('run_product_factory_pass_8', 'apply_product_leftover_8'),
 ('run_product_leftover_closeout_8', 'apply_product_leftover_8'),
 ('select_product_pass_slot_8', 'record_product_pass_8'),
 ('apply_product_leftover_8', 'record_product_pass_8'),
 ('finalize_product_pass_7', 'record_product_pass_8'),
 ('prepare_product_budget', 'classify_product_pass_8'),
 ('record_product_pass_8', 'classify_product_pass_8'),
 ('classify_product_pass_8', 'classify_product_plateau_8'),
 ('prepare_product_budget', 'decide_product_pass_stop_8'),
 ('classify_product_plateau_8', 'decide_product_pass_stop_8'),
 ('prepare_product_budget', 'finalize_product_pass_8'),
 ('decide_product_pass_stop_8', 'finalize_product_pass_8'),
 ('prepare_product_budget', 'select_product_budget_result'),
 ('finalize_product_pass_1', 'select_product_budget_result'),
 ('finalize_product_pass_2', 'select_product_budget_result'),
 ('finalize_product_pass_3', 'select_product_budget_result'),
 ('finalize_product_pass_4', 'select_product_budget_result'),
 ('finalize_product_pass_5', 'select_product_budget_result'),
 ('finalize_product_pass_6', 'select_product_budget_result'),
 ('finalize_product_pass_7', 'select_product_budget_result'),
 ('finalize_product_pass_8', 'select_product_budget_result')]
_WHEN_BRANCHES = [('run_product_factory_pass_1', {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_1'}),
 ('run_product_leftover_closeout_1',
  {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_1'}),
 ('run_product_factory_pass_2', {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_2'}),
 ('run_product_leftover_closeout_2',
  {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_2'}),
 ('run_product_factory_pass_3', {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_3'}),
 ('run_product_leftover_closeout_3',
  {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_3'}),
 ('run_product_factory_pass_4', {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_4'}),
 ('run_product_leftover_closeout_4',
  {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_4'}),
 ('run_product_factory_pass_5', {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_5'}),
 ('run_product_leftover_closeout_5',
  {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_5'}),
 ('run_product_factory_pass_6', {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_6'}),
 ('run_product_leftover_closeout_6',
  {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_6'}),
 ('run_product_factory_pass_7', {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_7'}),
 ('run_product_leftover_closeout_7',
  {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_7'}),
 ('run_product_factory_pass_8', {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_8'}),
 ('run_product_leftover_closeout_8',
  {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_8'})]
_EFFECTORS = [{'conduction': [], 'id': 'prepare_product_budget', 'when': None},
 {'conduction': ['prepare_product_budget'], 'id': 'select_product_pass_slot_1', 'when': None},
 {'conduction': ['select_product_pass_slot_1'],
  'id': 'run_product_factory_pass_1',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_1'}},
 {'conduction': ['select_product_pass_slot_1', 'run_product_factory_pass_1'],
  'id': 'run_product_leftover_closeout_1',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_1'}},
 {'conduction': ['run_product_factory_pass_1', 'run_product_leftover_closeout_1'],
  'id': 'apply_product_leftover_1',
  'when': None},
 {'conduction': ['select_product_pass_slot_1', 'apply_product_leftover_1'],
  'id': 'record_product_pass_1',
  'when': None},
 {'conduction': ['prepare_product_budget', 'record_product_pass_1'],
  'id': 'classify_product_pass_1',
  'when': None},
 {'conduction': ['classify_product_pass_1'], 'id': 'classify_product_plateau_1', 'when': None},
 {'conduction': ['prepare_product_budget', 'classify_product_plateau_1'],
  'id': 'decide_product_pass_stop_1',
  'when': None},
 {'conduction': ['prepare_product_budget', 'decide_product_pass_stop_1'],
  'id': 'finalize_product_pass_1',
  'when': None},
 {'conduction': ['prepare_product_budget', 'finalize_product_pass_1'],
  'id': 'select_product_pass_slot_2',
  'when': None},
 {'conduction': ['select_product_pass_slot_2'],
  'id': 'run_product_factory_pass_2',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_2'}},
 {'conduction': ['select_product_pass_slot_2', 'run_product_factory_pass_2'],
  'id': 'run_product_leftover_closeout_2',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_2'}},
 {'conduction': ['run_product_factory_pass_2', 'run_product_leftover_closeout_2'],
  'id': 'apply_product_leftover_2',
  'when': None},
 {'conduction': ['select_product_pass_slot_2', 'apply_product_leftover_2', 'finalize_product_pass_1'],
  'id': 'record_product_pass_2',
  'when': None},
 {'conduction': ['prepare_product_budget', 'record_product_pass_2'],
  'id': 'classify_product_pass_2',
  'when': None},
 {'conduction': ['classify_product_pass_2'], 'id': 'classify_product_plateau_2', 'when': None},
 {'conduction': ['prepare_product_budget', 'classify_product_plateau_2'],
  'id': 'decide_product_pass_stop_2',
  'when': None},
 {'conduction': ['prepare_product_budget', 'decide_product_pass_stop_2'],
  'id': 'finalize_product_pass_2',
  'when': None},
 {'conduction': ['prepare_product_budget', 'finalize_product_pass_2'],
  'id': 'select_product_pass_slot_3',
  'when': None},
 {'conduction': ['select_product_pass_slot_3'],
  'id': 'run_product_factory_pass_3',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_3'}},
 {'conduction': ['select_product_pass_slot_3', 'run_product_factory_pass_3'],
  'id': 'run_product_leftover_closeout_3',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_3'}},
 {'conduction': ['run_product_factory_pass_3', 'run_product_leftover_closeout_3'],
  'id': 'apply_product_leftover_3',
  'when': None},
 {'conduction': ['select_product_pass_slot_3', 'apply_product_leftover_3', 'finalize_product_pass_2'],
  'id': 'record_product_pass_3',
  'when': None},
 {'conduction': ['prepare_product_budget', 'record_product_pass_3'],
  'id': 'classify_product_pass_3',
  'when': None},
 {'conduction': ['classify_product_pass_3'], 'id': 'classify_product_plateau_3', 'when': None},
 {'conduction': ['prepare_product_budget', 'classify_product_plateau_3'],
  'id': 'decide_product_pass_stop_3',
  'when': None},
 {'conduction': ['prepare_product_budget', 'decide_product_pass_stop_3'],
  'id': 'finalize_product_pass_3',
  'when': None},
 {'conduction': ['prepare_product_budget', 'finalize_product_pass_3'],
  'id': 'select_product_pass_slot_4',
  'when': None},
 {'conduction': ['select_product_pass_slot_4'],
  'id': 'run_product_factory_pass_4',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_4'}},
 {'conduction': ['select_product_pass_slot_4', 'run_product_factory_pass_4'],
  'id': 'run_product_leftover_closeout_4',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_4'}},
 {'conduction': ['run_product_factory_pass_4', 'run_product_leftover_closeout_4'],
  'id': 'apply_product_leftover_4',
  'when': None},
 {'conduction': ['select_product_pass_slot_4', 'apply_product_leftover_4', 'finalize_product_pass_3'],
  'id': 'record_product_pass_4',
  'when': None},
 {'conduction': ['prepare_product_budget', 'record_product_pass_4'],
  'id': 'classify_product_pass_4',
  'when': None},
 {'conduction': ['classify_product_pass_4'], 'id': 'classify_product_plateau_4', 'when': None},
 {'conduction': ['prepare_product_budget', 'classify_product_plateau_4'],
  'id': 'decide_product_pass_stop_4',
  'when': None},
 {'conduction': ['prepare_product_budget', 'decide_product_pass_stop_4'],
  'id': 'finalize_product_pass_4',
  'when': None},
 {'conduction': ['prepare_product_budget', 'finalize_product_pass_4'],
  'id': 'select_product_pass_slot_5',
  'when': None},
 {'conduction': ['select_product_pass_slot_5'],
  'id': 'run_product_factory_pass_5',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_5'}},
 {'conduction': ['select_product_pass_slot_5', 'run_product_factory_pass_5'],
  'id': 'run_product_leftover_closeout_5',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_5'}},
 {'conduction': ['run_product_factory_pass_5', 'run_product_leftover_closeout_5'],
  'id': 'apply_product_leftover_5',
  'when': None},
 {'conduction': ['select_product_pass_slot_5', 'apply_product_leftover_5', 'finalize_product_pass_4'],
  'id': 'record_product_pass_5',
  'when': None},
 {'conduction': ['prepare_product_budget', 'record_product_pass_5'],
  'id': 'classify_product_pass_5',
  'when': None},
 {'conduction': ['classify_product_pass_5'], 'id': 'classify_product_plateau_5', 'when': None},
 {'conduction': ['prepare_product_budget', 'classify_product_plateau_5'],
  'id': 'decide_product_pass_stop_5',
  'when': None},
 {'conduction': ['prepare_product_budget', 'decide_product_pass_stop_5'],
  'id': 'finalize_product_pass_5',
  'when': None},
 {'conduction': ['prepare_product_budget', 'finalize_product_pass_5'],
  'id': 'select_product_pass_slot_6',
  'when': None},
 {'conduction': ['select_product_pass_slot_6'],
  'id': 'run_product_factory_pass_6',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_6'}},
 {'conduction': ['select_product_pass_slot_6', 'run_product_factory_pass_6'],
  'id': 'run_product_leftover_closeout_6',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_6'}},
 {'conduction': ['run_product_factory_pass_6', 'run_product_leftover_closeout_6'],
  'id': 'apply_product_leftover_6',
  'when': None},
 {'conduction': ['select_product_pass_slot_6', 'apply_product_leftover_6', 'finalize_product_pass_5'],
  'id': 'record_product_pass_6',
  'when': None},
 {'conduction': ['prepare_product_budget', 'record_product_pass_6'],
  'id': 'classify_product_pass_6',
  'when': None},
 {'conduction': ['classify_product_pass_6'], 'id': 'classify_product_plateau_6', 'when': None},
 {'conduction': ['prepare_product_budget', 'classify_product_plateau_6'],
  'id': 'decide_product_pass_stop_6',
  'when': None},
 {'conduction': ['prepare_product_budget', 'decide_product_pass_stop_6'],
  'id': 'finalize_product_pass_6',
  'when': None},
 {'conduction': ['prepare_product_budget', 'finalize_product_pass_6'],
  'id': 'select_product_pass_slot_7',
  'when': None},
 {'conduction': ['select_product_pass_slot_7'],
  'id': 'run_product_factory_pass_7',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_7'}},
 {'conduction': ['select_product_pass_slot_7', 'run_product_factory_pass_7'],
  'id': 'run_product_leftover_closeout_7',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_7'}},
 {'conduction': ['run_product_factory_pass_7', 'run_product_leftover_closeout_7'],
  'id': 'apply_product_leftover_7',
  'when': None},
 {'conduction': ['select_product_pass_slot_7', 'apply_product_leftover_7', 'finalize_product_pass_6'],
  'id': 'record_product_pass_7',
  'when': None},
 {'conduction': ['prepare_product_budget', 'record_product_pass_7'],
  'id': 'classify_product_pass_7',
  'when': None},
 {'conduction': ['classify_product_pass_7'], 'id': 'classify_product_plateau_7', 'when': None},
 {'conduction': ['prepare_product_budget', 'classify_product_plateau_7'],
  'id': 'decide_product_pass_stop_7',
  'when': None},
 {'conduction': ['prepare_product_budget', 'decide_product_pass_stop_7'],
  'id': 'finalize_product_pass_7',
  'when': None},
 {'conduction': ['prepare_product_budget', 'finalize_product_pass_7'],
  'id': 'select_product_pass_slot_8',
  'when': None},
 {'conduction': ['select_product_pass_slot_8'],
  'id': 'run_product_factory_pass_8',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_8'}},
 {'conduction': ['select_product_pass_slot_8', 'run_product_factory_pass_8'],
  'id': 'run_product_leftover_closeout_8',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_8'}},
 {'conduction': ['run_product_factory_pass_8', 'run_product_leftover_closeout_8'],
  'id': 'apply_product_leftover_8',
  'when': None},
 {'conduction': ['select_product_pass_slot_8', 'apply_product_leftover_8', 'finalize_product_pass_7'],
  'id': 'record_product_pass_8',
  'when': None},
 {'conduction': ['prepare_product_budget', 'record_product_pass_8'],
  'id': 'classify_product_pass_8',
  'when': None},
 {'conduction': ['classify_product_pass_8'], 'id': 'classify_product_plateau_8', 'when': None},
 {'conduction': ['prepare_product_budget', 'classify_product_plateau_8'],
  'id': 'decide_product_pass_stop_8',
  'when': None},
 {'conduction': ['prepare_product_budget', 'decide_product_pass_stop_8'],
  'id': 'finalize_product_pass_8',
  'when': None},
 {'conduction': ['prepare_product_budget',
                 'finalize_product_pass_1',
                 'finalize_product_pass_2',
                 'finalize_product_pass_3',
                 'finalize_product_pass_4',
                 'finalize_product_pass_5',
                 'finalize_product_pass_6',
                 'finalize_product_pass_7',
                 'finalize_product_pass_8'],
  'id': 'select_product_budget_result',
  'when': None}]

def test_every_conduction_edge_is_declared():
    got = {(str(up), nid) for nid, meta in _NODES.items() for up in meta["conduction"]}
    assert got == set(tuple(edge) for edge in _COND_EDGES)

def test_every_when_branch_is_declared():
    got = {(nid, json.dumps(meta["when"], sort_keys=True)) for nid, meta in _NODES.items() if meta["when"]}
    want = {(nid, json.dumps(when, sort_keys=True)) for nid, when in _WHEN_BRANCHES}
    assert got == want

def test_when_upstream_is_a_direct_parent():
    for nid, when in _WHEN_BRANCHES:
        assert when["upstream"] in _NODES[nid]["conduction"]

def test_unconditional_nodes_succeed_without_outputs():
    from support.graph_model import run_model
    status = run_model(_EFFECTORS, {})
    for nid, meta in _NODES.items():
        if meta["when"] is None:
            assert status[nid] == "succeeded"

