"""select_product_pass_slot_5 in product_pass_budget: geometry and required when fields."""
from __future__ import annotations

_PATH_ID = 'product_pass_budget'
_NODE_ID = 'select_product_pass_slot_5'
_ATOM = 'select_product_pass_slot_5'
_CONDUCTION = ['prepare_product_budget', 'finalize_product_pass_4']
_WHEN = None
_REQUIRED_WHEN_FIELDS = ['route']
_EFFECTORS = [{'conduction': [], 'id': 'prepare_product_budget', 'when': None},
 {'conduction': ['prepare_product_budget'], 'id': 'select_product_pass_slot_1', 'when': None},
 {'conduction': ['select_product_pass_slot_1'],
  'id': 'run_product_factory_pass_1',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_1'}},
 {'conduction': ['select_product_pass_slot_1', 'run_product_factory_pass_1'],
  'id': 'run_product_leftover_closeout_1',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_1'}},
 {'conduction': ['run_product_factory_pass_1', 'run_product_leftover_closeout_1'],
  'id': 'apply_product_leftover_1',
  'when': None},
 {'conduction': ['select_product_pass_slot_1', 'apply_product_leftover_1'],
  'id': 'record_product_pass_1',
  'when': None},
 {'conduction': ['prepare_product_budget', 'record_product_pass_1'],
  'id': 'classify_product_pass_1',
  'when': None},
 {'conduction': ['classify_product_pass_1'], 'id': 'classify_product_plateau_1', 'when': None},
 {'conduction': ['prepare_product_budget', 'classify_product_plateau_1'],
  'id': 'decide_product_pass_stop_1',
  'when': None},
 {'conduction': ['prepare_product_budget', 'decide_product_pass_stop_1'],
  'id': 'finalize_product_pass_1',
  'when': None},
 {'conduction': ['prepare_product_budget', 'finalize_product_pass_1'],
  'id': 'select_product_pass_slot_2',
  'when': None},
 {'conduction': ['select_product_pass_slot_2'],
  'id': 'run_product_factory_pass_2',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_2'}},
 {'conduction': ['select_product_pass_slot_2', 'run_product_factory_pass_2'],
  'id': 'run_product_leftover_closeout_2',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_2'}},
 {'conduction': ['run_product_factory_pass_2', 'run_product_leftover_closeout_2'],
  'id': 'apply_product_leftover_2',
  'when': None},
 {'conduction': ['select_product_pass_slot_2', 'apply_product_leftover_2', 'finalize_product_pass_1'],
  'id': 'record_product_pass_2',
  'when': None},
 {'conduction': ['prepare_product_budget', 'record_product_pass_2'],
  'id': 'classify_product_pass_2',
  'when': None},
 {'conduction': ['classify_product_pass_2'], 'id': 'classify_product_plateau_2', 'when': None},
 {'conduction': ['prepare_product_budget', 'classify_product_plateau_2'],
  'id': 'decide_product_pass_stop_2',
  'when': None},
 {'conduction': ['prepare_product_budget', 'decide_product_pass_stop_2'],
  'id': 'finalize_product_pass_2',
  'when': None},
 {'conduction': ['prepare_product_budget', 'finalize_product_pass_2'],
  'id': 'select_product_pass_slot_3',
  'when': None},
 {'conduction': ['select_product_pass_slot_3'],
  'id': 'run_product_factory_pass_3',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_3'}},
 {'conduction': ['select_product_pass_slot_3', 'run_product_factory_pass_3'],
  'id': 'run_product_leftover_closeout_3',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_3'}},
 {'conduction': ['run_product_factory_pass_3', 'run_product_leftover_closeout_3'],
  'id': 'apply_product_leftover_3',
  'when': None},
 {'conduction': ['select_product_pass_slot_3', 'apply_product_leftover_3', 'finalize_product_pass_2'],
  'id': 'record_product_pass_3',
  'when': None},
 {'conduction': ['prepare_product_budget', 'record_product_pass_3'],
  'id': 'classify_product_pass_3',
  'when': None},
 {'conduction': ['classify_product_pass_3'], 'id': 'classify_product_plateau_3', 'when': None},
 {'conduction': ['prepare_product_budget', 'classify_product_plateau_3'],
  'id': 'decide_product_pass_stop_3',
  'when': None},
 {'conduction': ['prepare_product_budget', 'decide_product_pass_stop_3'],
  'id': 'finalize_product_pass_3',
  'when': None},
 {'conduction': ['prepare_product_budget', 'finalize_product_pass_3'],
  'id': 'select_product_pass_slot_4',
  'when': None},
 {'conduction': ['select_product_pass_slot_4'],
  'id': 'run_product_factory_pass_4',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_4'}},
 {'conduction': ['select_product_pass_slot_4', 'run_product_factory_pass_4'],
  'id': 'run_product_leftover_closeout_4',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_4'}},
 {'conduction': ['run_product_factory_pass_4', 'run_product_leftover_closeout_4'],
  'id': 'apply_product_leftover_4',
  'when': None},
 {'conduction': ['select_product_pass_slot_4', 'apply_product_leftover_4', 'finalize_product_pass_3'],
  'id': 'record_product_pass_4',
  'when': None},
 {'conduction': ['prepare_product_budget', 'record_product_pass_4'],
  'id': 'classify_product_pass_4',
  'when': None},
 {'conduction': ['classify_product_pass_4'], 'id': 'classify_product_plateau_4', 'when': None},
 {'conduction': ['prepare_product_budget', 'classify_product_plateau_4'],
  'id': 'decide_product_pass_stop_4',
  'when': None},
 {'conduction': ['prepare_product_budget', 'decide_product_pass_stop_4'],
  'id': 'finalize_product_pass_4',
  'when': None},
 {'conduction': ['prepare_product_budget', 'finalize_product_pass_4'],
  'id': 'select_product_pass_slot_5',
  'when': None},
 {'conduction': ['select_product_pass_slot_5'],
  'id': 'run_product_factory_pass_5',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_5'}},
 {'conduction': ['select_product_pass_slot_5', 'run_product_factory_pass_5'],
  'id': 'run_product_leftover_closeout_5',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_5'}},
 {'conduction': ['run_product_factory_pass_5', 'run_product_leftover_closeout_5'],
  'id': 'apply_product_leftover_5',
  'when': None},
 {'conduction': ['select_product_pass_slot_5', 'apply_product_leftover_5', 'finalize_product_pass_4'],
  'id': 'record_product_pass_5',
  'when': None},
 {'conduction': ['prepare_product_budget', 'record_product_pass_5'],
  'id': 'classify_product_pass_5',
  'when': None},
 {'conduction': ['classify_product_pass_5'], 'id': 'classify_product_plateau_5', 'when': None},
 {'conduction': ['prepare_product_budget', 'classify_product_plateau_5'],
  'id': 'decide_product_pass_stop_5',
  'when': None},
 {'conduction': ['prepare_product_budget', 'decide_product_pass_stop_5'],
  'id': 'finalize_product_pass_5',
  'when': None},
 {'conduction': ['prepare_product_budget', 'finalize_product_pass_5'],
  'id': 'select_product_pass_slot_6',
  'when': None},
 {'conduction': ['select_product_pass_slot_6'],
  'id': 'run_product_factory_pass_6',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_6'}},
 {'conduction': ['select_product_pass_slot_6', 'run_product_factory_pass_6'],
  'id': 'run_product_leftover_closeout_6',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_6'}},
 {'conduction': ['run_product_factory_pass_6', 'run_product_leftover_closeout_6'],
  'id': 'apply_product_leftover_6',
  'when': None},
 {'conduction': ['select_product_pass_slot_6', 'apply_product_leftover_6', 'finalize_product_pass_5'],
  'id': 'record_product_pass_6',
  'when': None},
 {'conduction': ['prepare_product_budget', 'record_product_pass_6'],
  'id': 'classify_product_pass_6',
  'when': None},
 {'conduction': ['classify_product_pass_6'], 'id': 'classify_product_plateau_6', 'when': None},
 {'conduction': ['prepare_product_budget', 'classify_product_plateau_6'],
  'id': 'decide_product_pass_stop_6',
  'when': None},
 {'conduction': ['prepare_product_budget', 'decide_product_pass_stop_6'],
  'id': 'finalize_product_pass_6',
  'when': None},
 {'conduction': ['prepare_product_budget', 'finalize_product_pass_6'],
  'id': 'select_product_pass_slot_7',
  'when': None},
 {'conduction': ['select_product_pass_slot_7'],
  'id': 'run_product_factory_pass_7',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_7'}},
 {'conduction': ['select_product_pass_slot_7', 'run_product_factory_pass_7'],
  'id': 'run_product_leftover_closeout_7',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_7'}},
 {'conduction': ['run_product_factory_pass_7', 'run_product_leftover_closeout_7'],
  'id': 'apply_product_leftover_7',
  'when': None},
 {'conduction': ['select_product_pass_slot_7', 'apply_product_leftover_7', 'finalize_product_pass_6'],
  'id': 'record_product_pass_7',
  'when': None},
 {'conduction': ['prepare_product_budget', 'record_product_pass_7'],
  'id': 'classify_product_pass_7',
  'when': None},
 {'conduction': ['classify_product_pass_7'], 'id': 'classify_product_plateau_7', 'when': None},
 {'conduction': ['prepare_product_budget', 'classify_product_plateau_7'],
  'id': 'decide_product_pass_stop_7',
  'when': None},
 {'conduction': ['prepare_product_budget', 'decide_product_pass_stop_7'],
  'id': 'finalize_product_pass_7',
  'when': None},
 {'conduction': ['prepare_product_budget', 'finalize_product_pass_7'],
  'id': 'select_product_pass_slot_8',
  'when': None},
 {'conduction': ['select_product_pass_slot_8'],
  'id': 'run_product_factory_pass_8',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_8'}},
 {'conduction': ['select_product_pass_slot_8', 'run_product_factory_pass_8'],
  'id': 'run_product_leftover_closeout_8',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_product_pass_slot_8'}},
 {'conduction': ['run_product_factory_pass_8', 'run_product_leftover_closeout_8'],
  'id': 'apply_product_leftover_8',
  'when': None},
 {'conduction': ['select_product_pass_slot_8', 'apply_product_leftover_8', 'finalize_product_pass_7'],
  'id': 'record_product_pass_8',
  'when': None},
 {'conduction': ['prepare_product_budget', 'record_product_pass_8'],
  'id': 'classify_product_pass_8',
  'when': None},
 {'conduction': ['classify_product_pass_8'], 'id': 'classify_product_plateau_8', 'when': None},
 {'conduction': ['prepare_product_budget', 'classify_product_plateau_8'],
  'id': 'decide_product_pass_stop_8',
  'when': None},
 {'conduction': ['prepare_product_budget', 'decide_product_pass_stop_8'],
  'id': 'finalize_product_pass_8',
  'when': None},
 {'conduction': ['prepare_product_budget',
                 'finalize_product_pass_1',
                 'finalize_product_pass_2',
                 'finalize_product_pass_3',
                 'finalize_product_pass_4',
                 'finalize_product_pass_5',
                 'finalize_product_pass_6',
                 'finalize_product_pass_7',
                 'finalize_product_pass_8'],
  'id': 'select_product_budget_result',
  'when': None}]

def test_node_identity():
    assert _NODE_ID
    assert _ATOM

def test_conduction_is_declared():
    assert isinstance(_CONDUCTION, list)

def test_required_when_fields_are_listed():
    assert all(isinstance(field, str) and field for field in _REQUIRED_WHEN_FIELDS)

def test_model_status_for_this_node():
    from support.graph_model import run_model
    status = run_model(_EFFECTORS, {})
    assert _NODE_ID in status
    assert status[_NODE_ID] in {"succeeded", "skipped"}

def test_required_when_fields_live_on_domain_output():
    values = {"ok": True, "atom": _ATOM}
    for field in _REQUIRED_WHEN_FIELDS:
        if "." in field:
            current = values
            parts = field.split(".")
            for part in parts[:-1]:
                current = current.setdefault(part, {})
            current.setdefault(parts[-1], "value")
        else:
            values.setdefault(field, "value")
    from support.graph_model import lookup_path
    for field in _REQUIRED_WHEN_FIELDS:
        found, _ = lookup_path(values, field)
        assert found, field

