"""Independent conduction and when metadata for closeout_pr."""
from __future__ import annotations
import json

_PATH_ID = 'closeout_pr'
_NODES = {'authorize_closeout_repair': {'atom': 'authorize_closeout_repair',
                               'conduction': ['classify_closeout_gate', 'route_closeout_checks'],
                               'when': None},
 'authorize_closeout_review_repair': {'atom': 'authorize_closeout_review_repair',
                                      'conduction': ['classify_closeout_gate', 'classify_closeout_triage'],
                                      'when': None},
 'build_closeout_evidence': {'atom': 'build_closeout_evidence',
                             'conduction': ['classify_closeout_gate',
                                            'route_closeout_checks',
                                            'classify_closeout_triage',
                                            'select_closeout_repair_result',
                                            'select_closeout_park_result'],
                             'when': None},
 'classify_closeout_gate': {'atom': 'classify_closeout_gate',
                            'conduction': ['inspect_closeout_pr', 'read_closeout_issue'],
                            'when': None},
 'classify_closeout_triage': {'atom': 'classify_closeout_triage',
                              'conduction': ['route_closeout_checks', 'run_closeout_triage'],
                              'when': None},
 'finalize_closeout_pr': {'atom': 'finalize_closeout_pr',
                          'conduction': ['classify_closeout_gate',
                                         'route_closeout_checks',
                                         'classify_closeout_triage',
                                         'select_closeout_repair_result',
                                         'build_closeout_evidence'],
                          'when': None},
 'inspect_closeout_pr': {'atom': 'inspect_closeout_pr', 'conduction': [], 'when': None},
 'park_closed_pr_issue': {'atom': 'park_closed_pr_issue',
                          'conduction': ['classify_closeout_gate'],
                          'when': {'equals': 'issue_closed',
                                   'path': 'route',
                                   'upstream': 'classify_closeout_gate'}},
 'park_delivered_pr_issue': {'atom': 'park_delivered_pr_issue',
                             'conduction': ['classify_closeout_gate', 'classify_closeout_triage'],
                             'when': {'equals': 'merged',
                                      'path': 'route',
                                      'upstream': 'classify_closeout_triage'}},
 'read_closeout_checks': {'atom': 'read_closeout_checks',
                          'conduction': ['classify_closeout_gate'],
                          'when': {'equals': 'checks',
                                   'path': 'route',
                                   'upstream': 'classify_closeout_gate'}},
 'read_closeout_issue': {'atom': 'read_closeout_issue', 'conduction': ['inspect_closeout_pr'], 'when': None},
 'route_closeout_checks': {'atom': 'route_closeout_checks',
                           'conduction': ['classify_closeout_gate', 'read_closeout_checks'],
                           'when': None},
 'run_closeout_repair': {'atom': 'run_closeout_repair',
                         'conduction': ['classify_closeout_gate', 'authorize_closeout_repair'],
                         'when': {'equals': 'repair',
                                  'path': 'route',
                                  'upstream': 'authorize_closeout_repair'}},
 'run_closeout_review_repair': {'atom': 'run_closeout_review_repair',
                                'conduction': ['classify_closeout_gate', 'authorize_closeout_review_repair'],
                                'when': {'equals': 'repair',
                                         'path': 'route',
                                         'upstream': 'authorize_closeout_review_repair'}},
 'run_closeout_triage': {'atom': 'run_closeout_triage',
                         'conduction': ['classify_closeout_gate', 'route_closeout_checks'],
                         'when': {'equals': 'triage', 'path': 'route', 'upstream': 'route_closeout_checks'}},
 'select_closeout_park_result': {'atom': 'select_closeout_park_result',
                                 'conduction': ['park_closed_pr_issue', 'park_delivered_pr_issue'],
                                 'when': None},
 'select_closeout_repair_result': {'atom': 'select_closeout_repair_result',
                                   'conduction': ['authorize_closeout_repair',
                                                  'run_closeout_repair',
                                                  'authorize_closeout_review_repair',
                                                  'run_closeout_review_repair'],
                                   'when': None},
 'summarize_closeout_pr': {'atom': 'summarize_closeout_pr',
                           'conduction': ['finalize_closeout_pr'],
                           'when': None}}
_COND_EDGES = [('inspect_closeout_pr', 'read_closeout_issue'),
 ('inspect_closeout_pr', 'classify_closeout_gate'),
 ('read_closeout_issue', 'classify_closeout_gate'),
 ('classify_closeout_gate', 'park_closed_pr_issue'),
 ('classify_closeout_gate', 'read_closeout_checks'),
 ('classify_closeout_gate', 'route_closeout_checks'),
 ('read_closeout_checks', 'route_closeout_checks'),
 ('classify_closeout_gate', 'authorize_closeout_repair'),
 ('route_closeout_checks', 'authorize_closeout_repair'),
 ('classify_closeout_gate', 'run_closeout_repair'),
 ('authorize_closeout_repair', 'run_closeout_repair'),
 ('classify_closeout_gate', 'run_closeout_triage'),
 ('route_closeout_checks', 'run_closeout_triage'),
 ('route_closeout_checks', 'classify_closeout_triage'),
 ('run_closeout_triage', 'classify_closeout_triage'),
 ('classify_closeout_gate', 'authorize_closeout_review_repair'),
 ('classify_closeout_triage', 'authorize_closeout_review_repair'),
 ('classify_closeout_gate', 'run_closeout_review_repair'),
 ('authorize_closeout_review_repair', 'run_closeout_review_repair'),
 ('classify_closeout_gate', 'park_delivered_pr_issue'),
 ('classify_closeout_triage', 'park_delivered_pr_issue'),
 ('authorize_closeout_repair', 'select_closeout_repair_result'),
 ('run_closeout_repair', 'select_closeout_repair_result'),
 ('authorize_closeout_review_repair', 'select_closeout_repair_result'),
 ('run_closeout_review_repair', 'select_closeout_repair_result'),
 ('park_closed_pr_issue', 'select_closeout_park_result'),
 ('park_delivered_pr_issue', 'select_closeout_park_result'),
 ('classify_closeout_gate', 'build_closeout_evidence'),
 ('route_closeout_checks', 'build_closeout_evidence'),
 ('classify_closeout_triage', 'build_closeout_evidence'),
 ('select_closeout_repair_result', 'build_closeout_evidence'),
 ('select_closeout_park_result', 'build_closeout_evidence'),
 ('classify_closeout_gate', 'finalize_closeout_pr'),
 ('route_closeout_checks', 'finalize_closeout_pr'),
 ('classify_closeout_triage', 'finalize_closeout_pr'),
 ('select_closeout_repair_result', 'finalize_closeout_pr'),
 ('build_closeout_evidence', 'finalize_closeout_pr'),
 ('finalize_closeout_pr', 'summarize_closeout_pr')]
_WHEN_BRANCHES = [('park_closed_pr_issue', {'equals': 'issue_closed', 'path': 'route', 'upstream': 'classify_closeout_gate'}),
 ('read_closeout_checks', {'equals': 'checks', 'path': 'route', 'upstream': 'classify_closeout_gate'}),
 ('run_closeout_repair', {'equals': 'repair', 'path': 'route', 'upstream': 'authorize_closeout_repair'}),
 ('run_closeout_triage', {'equals': 'triage', 'path': 'route', 'upstream': 'route_closeout_checks'}),
 ('run_closeout_review_repair',
  {'equals': 'repair', 'path': 'route', 'upstream': 'authorize_closeout_review_repair'}),
 ('park_delivered_pr_issue', {'equals': 'merged', 'path': 'route', 'upstream': 'classify_closeout_triage'})]
_EFFECTORS = [{'conduction': [], 'id': 'inspect_closeout_pr', 'when': None},
 {'conduction': ['inspect_closeout_pr'], 'id': 'read_closeout_issue', 'when': None},
 {'conduction': ['inspect_closeout_pr', 'read_closeout_issue'], 'id': 'classify_closeout_gate', 'when': None},
 {'conduction': ['classify_closeout_gate'],
  'id': 'park_closed_pr_issue',
  'when': {'equals': 'issue_closed', 'path': 'route', 'upstream': 'classify_closeout_gate'}},
 {'conduction': ['classify_closeout_gate'],
  'id': 'read_closeout_checks',
  'when': {'equals': 'checks', 'path': 'route', 'upstream': 'classify_closeout_gate'}},
 {'conduction': ['classify_closeout_gate', 'read_closeout_checks'],
  'id': 'route_closeout_checks',
  'when': None},
 {'conduction': ['classify_closeout_gate', 'route_closeout_checks'],
  'id': 'authorize_closeout_repair',
  'when': None},
 {'conduction': ['classify_closeout_gate', 'authorize_closeout_repair'],
  'id': 'run_closeout_repair',
  'when': {'equals': 'repair', 'path': 'route', 'upstream': 'authorize_closeout_repair'}},
 {'conduction': ['classify_closeout_gate', 'route_closeout_checks'],
  'id': 'run_closeout_triage',
  'when': {'equals': 'triage', 'path': 'route', 'upstream': 'route_closeout_checks'}},
 {'conduction': ['route_closeout_checks', 'run_closeout_triage'],
  'id': 'classify_closeout_triage',
  'when': None},
 {'conduction': ['classify_closeout_gate', 'classify_closeout_triage'],
  'id': 'authorize_closeout_review_repair',
  'when': None},
 {'conduction': ['classify_closeout_gate', 'authorize_closeout_review_repair'],
  'id': 'run_closeout_review_repair',
  'when': {'equals': 'repair', 'path': 'route', 'upstream': 'authorize_closeout_review_repair'}},
 {'conduction': ['classify_closeout_gate', 'classify_closeout_triage'],
  'id': 'park_delivered_pr_issue',
  'when': {'equals': 'merged', 'path': 'route', 'upstream': 'classify_closeout_triage'}},
 {'conduction': ['authorize_closeout_repair',
                 'run_closeout_repair',
                 'authorize_closeout_review_repair',
                 'run_closeout_review_repair'],
  'id': 'select_closeout_repair_result',
  'when': None},
 {'conduction': ['park_closed_pr_issue', 'park_delivered_pr_issue'],
  'id': 'select_closeout_park_result',
  'when': None},
 {'conduction': ['classify_closeout_gate',
                 'route_closeout_checks',
                 'classify_closeout_triage',
                 'select_closeout_repair_result',
                 'select_closeout_park_result'],
  'id': 'build_closeout_evidence',
  'when': None},
 {'conduction': ['classify_closeout_gate',
                 'route_closeout_checks',
                 'classify_closeout_triage',
                 'select_closeout_repair_result',
                 'build_closeout_evidence'],
  'id': 'finalize_closeout_pr',
  'when': None},
 {'conduction': ['finalize_closeout_pr'], 'id': 'summarize_closeout_pr', 'when': None}]

def test_every_conduction_edge_is_declared():
    got = {(str(up), nid) for nid, meta in _NODES.items() for up in meta["conduction"]}
    assert got == set(tuple(edge) for edge in _COND_EDGES)

def test_every_when_branch_is_declared():
    got = {(nid, json.dumps(meta["when"], sort_keys=True)) for nid, meta in _NODES.items() if meta["when"]}
    want = {(nid, json.dumps(when, sort_keys=True)) for nid, when in _WHEN_BRANCHES}
    assert got == want

def test_when_upstream_is_a_direct_parent():
    for nid, when in _WHEN_BRANCHES:
        assert when["upstream"] in _NODES[nid]["conduction"]

def test_unconditional_nodes_succeed_without_outputs():
    from support.graph_model import run_model
    status = run_model(_EFFECTORS, {})
    for nid, meta in _NODES.items():
        if meta["when"] is None:
            assert status[nid] == "succeeded"

