"""Independent conduction and when metadata for issue_sieve_rows."""
from __future__ import annotations
import json

_PATH_ID = 'issue_sieve_rows'
_NODES = {'classify_issue_sieve_row_1': {'atom': 'classify_issue_sieve_row_1',
                                'conduction': ['prepare_issue_sieve',
                                               'select_issue_sieve_slot_1',
                                               'run_issue_sieve_row_1'],
                                'when': None},
 'classify_issue_sieve_row_2': {'atom': 'classify_issue_sieve_row_2',
                                'conduction': ['prepare_issue_sieve',
                                               'select_issue_sieve_slot_2',
                                               'run_issue_sieve_row_2',
                                               'classify_issue_sieve_row_1'],
                                'when': None},
 'classify_issue_sieve_row_3': {'atom': 'classify_issue_sieve_row_3',
                                'conduction': ['prepare_issue_sieve',
                                               'select_issue_sieve_slot_3',
                                               'run_issue_sieve_row_3',
                                               'classify_issue_sieve_row_2'],
                                'when': None},
 'classify_issue_sieve_row_4': {'atom': 'classify_issue_sieve_row_4',
                                'conduction': ['prepare_issue_sieve',
                                               'select_issue_sieve_slot_4',
                                               'run_issue_sieve_row_4',
                                               'classify_issue_sieve_row_3'],
                                'when': None},
 'classify_issue_sieve_row_5': {'atom': 'classify_issue_sieve_row_5',
                                'conduction': ['prepare_issue_sieve',
                                               'select_issue_sieve_slot_5',
                                               'run_issue_sieve_row_5',
                                               'classify_issue_sieve_row_4'],
                                'when': None},
 'prepare_issue_sieve': {'atom': 'prepare_issue_sieve', 'conduction': [], 'when': None},
 'run_issue_sieve_row_1': {'atom': 'run_issue_sieve_row_1',
                           'conduction': ['prepare_issue_sieve', 'select_issue_sieve_slot_1'],
                           'when': {'equals': 'run',
                                    'path': 'route',
                                    'upstream': 'select_issue_sieve_slot_1'}},
 'run_issue_sieve_row_2': {'atom': 'run_issue_sieve_row_2',
                           'conduction': ['prepare_issue_sieve',
                                          'select_issue_sieve_slot_2',
                                          'classify_issue_sieve_row_1'],
                           'when': {'equals': 'run',
                                    'path': 'route',
                                    'upstream': 'select_issue_sieve_slot_2'}},
 'run_issue_sieve_row_3': {'atom': 'run_issue_sieve_row_3',
                           'conduction': ['prepare_issue_sieve',
                                          'select_issue_sieve_slot_3',
                                          'classify_issue_sieve_row_2'],
                           'when': {'equals': 'run',
                                    'path': 'route',
                                    'upstream': 'select_issue_sieve_slot_3'}},
 'run_issue_sieve_row_4': {'atom': 'run_issue_sieve_row_4',
                           'conduction': ['prepare_issue_sieve',
                                          'select_issue_sieve_slot_4',
                                          'classify_issue_sieve_row_3'],
                           'when': {'equals': 'run',
                                    'path': 'route',
                                    'upstream': 'select_issue_sieve_slot_4'}},
 'run_issue_sieve_row_5': {'atom': 'run_issue_sieve_row_5',
                           'conduction': ['prepare_issue_sieve',
                                          'select_issue_sieve_slot_5',
                                          'classify_issue_sieve_row_4'],
                           'when': {'equals': 'run',
                                    'path': 'route',
                                    'upstream': 'select_issue_sieve_slot_5'}},
 'select_issue_sieve_result': {'atom': 'select_issue_sieve_result',
                               'conduction': ['prepare_issue_sieve',
                                              'classify_issue_sieve_row_1',
                                              'classify_issue_sieve_row_2',
                                              'classify_issue_sieve_row_3',
                                              'classify_issue_sieve_row_4',
                                              'classify_issue_sieve_row_5'],
                               'when': None},
 'select_issue_sieve_slot_1': {'atom': 'select_issue_sieve_slot_1',
                               'conduction': ['prepare_issue_sieve'],
                               'when': None},
 'select_issue_sieve_slot_2': {'atom': 'select_issue_sieve_slot_2',
                               'conduction': ['prepare_issue_sieve', 'classify_issue_sieve_row_1'],
                               'when': None},
 'select_issue_sieve_slot_3': {'atom': 'select_issue_sieve_slot_3',
                               'conduction': ['prepare_issue_sieve', 'classify_issue_sieve_row_2'],
                               'when': None},
 'select_issue_sieve_slot_4': {'atom': 'select_issue_sieve_slot_4',
                               'conduction': ['prepare_issue_sieve', 'classify_issue_sieve_row_3'],
                               'when': None},
 'select_issue_sieve_slot_5': {'atom': 'select_issue_sieve_slot_5',
                               'conduction': ['prepare_issue_sieve', 'classify_issue_sieve_row_4'],
                               'when': None}}
_COND_EDGES = [('prepare_issue_sieve', 'select_issue_sieve_slot_1'),
 ('prepare_issue_sieve', 'run_issue_sieve_row_1'),
 ('select_issue_sieve_slot_1', 'run_issue_sieve_row_1'),
 ('prepare_issue_sieve', 'classify_issue_sieve_row_1'),
 ('select_issue_sieve_slot_1', 'classify_issue_sieve_row_1'),
 ('run_issue_sieve_row_1', 'classify_issue_sieve_row_1'),
 ('prepare_issue_sieve', 'select_issue_sieve_slot_2'),
 ('classify_issue_sieve_row_1', 'select_issue_sieve_slot_2'),
 ('prepare_issue_sieve', 'run_issue_sieve_row_2'),
 ('select_issue_sieve_slot_2', 'run_issue_sieve_row_2'),
 ('classify_issue_sieve_row_1', 'run_issue_sieve_row_2'),
 ('prepare_issue_sieve', 'classify_issue_sieve_row_2'),
 ('select_issue_sieve_slot_2', 'classify_issue_sieve_row_2'),
 ('run_issue_sieve_row_2', 'classify_issue_sieve_row_2'),
 ('classify_issue_sieve_row_1', 'classify_issue_sieve_row_2'),
 ('prepare_issue_sieve', 'select_issue_sieve_slot_3'),
 ('classify_issue_sieve_row_2', 'select_issue_sieve_slot_3'),
 ('prepare_issue_sieve', 'run_issue_sieve_row_3'),
 ('select_issue_sieve_slot_3', 'run_issue_sieve_row_3'),
 ('classify_issue_sieve_row_2', 'run_issue_sieve_row_3'),
 ('prepare_issue_sieve', 'classify_issue_sieve_row_3'),
 ('select_issue_sieve_slot_3', 'classify_issue_sieve_row_3'),
 ('run_issue_sieve_row_3', 'classify_issue_sieve_row_3'),
 ('classify_issue_sieve_row_2', 'classify_issue_sieve_row_3'),
 ('prepare_issue_sieve', 'select_issue_sieve_slot_4'),
 ('classify_issue_sieve_row_3', 'select_issue_sieve_slot_4'),
 ('prepare_issue_sieve', 'run_issue_sieve_row_4'),
 ('select_issue_sieve_slot_4', 'run_issue_sieve_row_4'),
 ('classify_issue_sieve_row_3', 'run_issue_sieve_row_4'),
 ('prepare_issue_sieve', 'classify_issue_sieve_row_4'),
 ('select_issue_sieve_slot_4', 'classify_issue_sieve_row_4'),
 ('run_issue_sieve_row_4', 'classify_issue_sieve_row_4'),
 ('classify_issue_sieve_row_3', 'classify_issue_sieve_row_4'),
 ('prepare_issue_sieve', 'select_issue_sieve_slot_5'),
 ('classify_issue_sieve_row_4', 'select_issue_sieve_slot_5'),
 ('prepare_issue_sieve', 'run_issue_sieve_row_5'),
 ('select_issue_sieve_slot_5', 'run_issue_sieve_row_5'),
 ('classify_issue_sieve_row_4', 'run_issue_sieve_row_5'),
 ('prepare_issue_sieve', 'classify_issue_sieve_row_5'),
 ('select_issue_sieve_slot_5', 'classify_issue_sieve_row_5'),
 ('run_issue_sieve_row_5', 'classify_issue_sieve_row_5'),
 ('classify_issue_sieve_row_4', 'classify_issue_sieve_row_5'),
 ('prepare_issue_sieve', 'select_issue_sieve_result'),
 ('classify_issue_sieve_row_1', 'select_issue_sieve_result'),
 ('classify_issue_sieve_row_2', 'select_issue_sieve_result'),
 ('classify_issue_sieve_row_3', 'select_issue_sieve_result'),
 ('classify_issue_sieve_row_4', 'select_issue_sieve_result'),
 ('classify_issue_sieve_row_5', 'select_issue_sieve_result')]
_WHEN_BRANCHES = [('run_issue_sieve_row_1', {'equals': 'run', 'path': 'route', 'upstream': 'select_issue_sieve_slot_1'}),
 ('run_issue_sieve_row_2', {'equals': 'run', 'path': 'route', 'upstream': 'select_issue_sieve_slot_2'}),
 ('run_issue_sieve_row_3', {'equals': 'run', 'path': 'route', 'upstream': 'select_issue_sieve_slot_3'}),
 ('run_issue_sieve_row_4', {'equals': 'run', 'path': 'route', 'upstream': 'select_issue_sieve_slot_4'}),
 ('run_issue_sieve_row_5', {'equals': 'run', 'path': 'route', 'upstream': 'select_issue_sieve_slot_5'})]
_EFFECTORS = [{'conduction': [], 'id': 'prepare_issue_sieve', 'when': None},
 {'conduction': ['prepare_issue_sieve'], 'id': 'select_issue_sieve_slot_1', 'when': None},
 {'conduction': ['prepare_issue_sieve', 'select_issue_sieve_slot_1'],
  'id': 'run_issue_sieve_row_1',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_issue_sieve_slot_1'}},
 {'conduction': ['prepare_issue_sieve', 'select_issue_sieve_slot_1', 'run_issue_sieve_row_1'],
  'id': 'classify_issue_sieve_row_1',
  'when': None},
 {'conduction': ['prepare_issue_sieve', 'classify_issue_sieve_row_1'],
  'id': 'select_issue_sieve_slot_2',
  'when': None},
 {'conduction': ['prepare_issue_sieve', 'select_issue_sieve_slot_2', 'classify_issue_sieve_row_1'],
  'id': 'run_issue_sieve_row_2',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_issue_sieve_slot_2'}},
 {'conduction': ['prepare_issue_sieve',
                 'select_issue_sieve_slot_2',
                 'run_issue_sieve_row_2',
                 'classify_issue_sieve_row_1'],
  'id': 'classify_issue_sieve_row_2',
  'when': None},
 {'conduction': ['prepare_issue_sieve', 'classify_issue_sieve_row_2'],
  'id': 'select_issue_sieve_slot_3',
  'when': None},
 {'conduction': ['prepare_issue_sieve', 'select_issue_sieve_slot_3', 'classify_issue_sieve_row_2'],
  'id': 'run_issue_sieve_row_3',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_issue_sieve_slot_3'}},
 {'conduction': ['prepare_issue_sieve',
                 'select_issue_sieve_slot_3',
                 'run_issue_sieve_row_3',
                 'classify_issue_sieve_row_2'],
  'id': 'classify_issue_sieve_row_3',
  'when': None},
 {'conduction': ['prepare_issue_sieve', 'classify_issue_sieve_row_3'],
  'id': 'select_issue_sieve_slot_4',
  'when': None},
 {'conduction': ['prepare_issue_sieve', 'select_issue_sieve_slot_4', 'classify_issue_sieve_row_3'],
  'id': 'run_issue_sieve_row_4',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_issue_sieve_slot_4'}},
 {'conduction': ['prepare_issue_sieve',
                 'select_issue_sieve_slot_4',
                 'run_issue_sieve_row_4',
                 'classify_issue_sieve_row_3'],
  'id': 'classify_issue_sieve_row_4',
  'when': None},
 {'conduction': ['prepare_issue_sieve', 'classify_issue_sieve_row_4'],
  'id': 'select_issue_sieve_slot_5',
  'when': None},
 {'conduction': ['prepare_issue_sieve', 'select_issue_sieve_slot_5', 'classify_issue_sieve_row_4'],
  'id': 'run_issue_sieve_row_5',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_issue_sieve_slot_5'}},
 {'conduction': ['prepare_issue_sieve',
                 'select_issue_sieve_slot_5',
                 'run_issue_sieve_row_5',
                 'classify_issue_sieve_row_4'],
  'id': 'classify_issue_sieve_row_5',
  'when': None},
 {'conduction': ['prepare_issue_sieve',
                 'classify_issue_sieve_row_1',
                 'classify_issue_sieve_row_2',
                 'classify_issue_sieve_row_3',
                 'classify_issue_sieve_row_4',
                 'classify_issue_sieve_row_5'],
  'id': 'select_issue_sieve_result',
  'when': None}]

def test_every_conduction_edge_is_declared():
    got = {(str(up), nid) for nid, meta in _NODES.items() for up in meta["conduction"]}
    assert got == set(tuple(edge) for edge in _COND_EDGES)

def test_every_when_branch_is_declared():
    got = {(nid, json.dumps(meta["when"], sort_keys=True)) for nid, meta in _NODES.items() if meta["when"]}
    want = {(nid, json.dumps(when, sort_keys=True)) for nid, when in _WHEN_BRANCHES}
    assert got == want

def test_when_upstream_is_a_direct_parent():
    for nid, when in _WHEN_BRANCHES:
        assert when["upstream"] in _NODES[nid]["conduction"]

def test_unconditional_nodes_succeed_without_outputs():
    from support.graph_model import run_model
    status = run_model(_EFFECTORS, {})
    for nid, meta in _NODES.items():
        if meta["when"] is None:
            assert status[nid] == "succeeded"

