"""Independent conduction and when metadata for executor_rows."""
from __future__ import annotations
import json

_PATH_ID = 'executor_rows'
_NODES = {'classify_executor_row_1': {'atom': 'classify_executor_row_1',
                             'conduction': ['prepare_executor_rows',
                                            'select_executor_slot_1',
                                            'run_executor_row_1'],
                             'when': None},
 'classify_executor_row_2': {'atom': 'classify_executor_row_2',
                             'conduction': ['prepare_executor_rows',
                                            'select_executor_slot_2',
                                            'run_executor_row_2',
                                            'classify_executor_row_1'],
                             'when': None},
 'classify_executor_row_3': {'atom': 'classify_executor_row_3',
                             'conduction': ['prepare_executor_rows',
                                            'select_executor_slot_3',
                                            'run_executor_row_3',
                                            'classify_executor_row_2'],
                             'when': None},
 'classify_executor_row_4': {'atom': 'classify_executor_row_4',
                             'conduction': ['prepare_executor_rows',
                                            'select_executor_slot_4',
                                            'run_executor_row_4',
                                            'classify_executor_row_3'],
                             'when': None},
 'classify_executor_row_5': {'atom': 'classify_executor_row_5',
                             'conduction': ['prepare_executor_rows',
                                            'select_executor_slot_5',
                                            'run_executor_row_5',
                                            'classify_executor_row_4'],
                             'when': None},
 'classify_executor_row_6': {'atom': 'classify_executor_row_6',
                             'conduction': ['prepare_executor_rows',
                                            'select_executor_slot_6',
                                            'run_executor_row_6',
                                            'classify_executor_row_5'],
                             'when': None},
 'classify_executor_row_7': {'atom': 'classify_executor_row_7',
                             'conduction': ['prepare_executor_rows',
                                            'select_executor_slot_7',
                                            'run_executor_row_7',
                                            'classify_executor_row_6'],
                             'when': None},
 'classify_executor_row_8': {'atom': 'classify_executor_row_8',
                             'conduction': ['prepare_executor_rows',
                                            'select_executor_slot_8',
                                            'run_executor_row_8',
                                            'classify_executor_row_7'],
                             'when': None},
 'prepare_executor_rows': {'atom': 'prepare_executor_rows', 'conduction': [], 'when': None},
 'run_executor_row_1': {'atom': 'run_executor_row_1',
                        'conduction': ['prepare_executor_rows', 'select_executor_slot_1'],
                        'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_executor_slot_1'}},
 'run_executor_row_2': {'atom': 'run_executor_row_2',
                        'conduction': ['prepare_executor_rows',
                                       'select_executor_slot_2',
                                       'classify_executor_row_1'],
                        'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_executor_slot_2'}},
 'run_executor_row_3': {'atom': 'run_executor_row_3',
                        'conduction': ['prepare_executor_rows',
                                       'select_executor_slot_3',
                                       'classify_executor_row_2'],
                        'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_executor_slot_3'}},
 'run_executor_row_4': {'atom': 'run_executor_row_4',
                        'conduction': ['prepare_executor_rows',
                                       'select_executor_slot_4',
                                       'classify_executor_row_3'],
                        'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_executor_slot_4'}},
 'run_executor_row_5': {'atom': 'run_executor_row_5',
                        'conduction': ['prepare_executor_rows',
                                       'select_executor_slot_5',
                                       'classify_executor_row_4'],
                        'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_executor_slot_5'}},
 'run_executor_row_6': {'atom': 'run_executor_row_6',
                        'conduction': ['prepare_executor_rows',
                                       'select_executor_slot_6',
                                       'classify_executor_row_5'],
                        'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_executor_slot_6'}},
 'run_executor_row_7': {'atom': 'run_executor_row_7',
                        'conduction': ['prepare_executor_rows',
                                       'select_executor_slot_7',
                                       'classify_executor_row_6'],
                        'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_executor_slot_7'}},
 'run_executor_row_8': {'atom': 'run_executor_row_8',
                        'conduction': ['prepare_executor_rows',
                                       'select_executor_slot_8',
                                       'classify_executor_row_7'],
                        'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_executor_slot_8'}},
 'select_executor_result': {'atom': 'select_executor_result',
                            'conduction': ['prepare_executor_rows',
                                           'classify_executor_row_1',
                                           'classify_executor_row_2',
                                           'classify_executor_row_3',
                                           'classify_executor_row_4',
                                           'classify_executor_row_5',
                                           'classify_executor_row_6',
                                           'classify_executor_row_7',
                                           'classify_executor_row_8'],
                            'when': None},
 'select_executor_slot_1': {'atom': 'select_executor_slot_1',
                            'conduction': ['prepare_executor_rows'],
                            'when': None},
 'select_executor_slot_2': {'atom': 'select_executor_slot_2',
                            'conduction': ['prepare_executor_rows', 'classify_executor_row_1'],
                            'when': None},
 'select_executor_slot_3': {'atom': 'select_executor_slot_3',
                            'conduction': ['prepare_executor_rows', 'classify_executor_row_2'],
                            'when': None},
 'select_executor_slot_4': {'atom': 'select_executor_slot_4',
                            'conduction': ['prepare_executor_rows', 'classify_executor_row_3'],
                            'when': None},
 'select_executor_slot_5': {'atom': 'select_executor_slot_5',
                            'conduction': ['prepare_executor_rows', 'classify_executor_row_4'],
                            'when': None},
 'select_executor_slot_6': {'atom': 'select_executor_slot_6',
                            'conduction': ['prepare_executor_rows', 'classify_executor_row_5'],
                            'when': None},
 'select_executor_slot_7': {'atom': 'select_executor_slot_7',
                            'conduction': ['prepare_executor_rows', 'classify_executor_row_6'],
                            'when': None},
 'select_executor_slot_8': {'atom': 'select_executor_slot_8',
                            'conduction': ['prepare_executor_rows', 'classify_executor_row_7'],
                            'when': None}}
_COND_EDGES = [('prepare_executor_rows', 'select_executor_slot_1'),
 ('prepare_executor_rows', 'run_executor_row_1'),
 ('select_executor_slot_1', 'run_executor_row_1'),
 ('prepare_executor_rows', 'classify_executor_row_1'),
 ('select_executor_slot_1', 'classify_executor_row_1'),
 ('run_executor_row_1', 'classify_executor_row_1'),
 ('prepare_executor_rows', 'select_executor_slot_2'),
 ('classify_executor_row_1', 'select_executor_slot_2'),
 ('prepare_executor_rows', 'run_executor_row_2'),
 ('select_executor_slot_2', 'run_executor_row_2'),
 ('classify_executor_row_1', 'run_executor_row_2'),
 ('prepare_executor_rows', 'classify_executor_row_2'),
 ('select_executor_slot_2', 'classify_executor_row_2'),
 ('run_executor_row_2', 'classify_executor_row_2'),
 ('classify_executor_row_1', 'classify_executor_row_2'),
 ('prepare_executor_rows', 'select_executor_slot_3'),
 ('classify_executor_row_2', 'select_executor_slot_3'),
 ('prepare_executor_rows', 'run_executor_row_3'),
 ('select_executor_slot_3', 'run_executor_row_3'),
 ('classify_executor_row_2', 'run_executor_row_3'),
 ('prepare_executor_rows', 'classify_executor_row_3'),
 ('select_executor_slot_3', 'classify_executor_row_3'),
 ('run_executor_row_3', 'classify_executor_row_3'),
 ('classify_executor_row_2', 'classify_executor_row_3'),
 ('prepare_executor_rows', 'select_executor_slot_4'),
 ('classify_executor_row_3', 'select_executor_slot_4'),
 ('prepare_executor_rows', 'run_executor_row_4'),
 ('select_executor_slot_4', 'run_executor_row_4'),
 ('classify_executor_row_3', 'run_executor_row_4'),
 ('prepare_executor_rows', 'classify_executor_row_4'),
 ('select_executor_slot_4', 'classify_executor_row_4'),
 ('run_executor_row_4', 'classify_executor_row_4'),
 ('classify_executor_row_3', 'classify_executor_row_4'),
 ('prepare_executor_rows', 'select_executor_slot_5'),
 ('classify_executor_row_4', 'select_executor_slot_5'),
 ('prepare_executor_rows', 'run_executor_row_5'),
 ('select_executor_slot_5', 'run_executor_row_5'),
 ('classify_executor_row_4', 'run_executor_row_5'),
 ('prepare_executor_rows', 'classify_executor_row_5'),
 ('select_executor_slot_5', 'classify_executor_row_5'),
 ('run_executor_row_5', 'classify_executor_row_5'),
 ('classify_executor_row_4', 'classify_executor_row_5'),
 ('prepare_executor_rows', 'select_executor_slot_6'),
 ('classify_executor_row_5', 'select_executor_slot_6'),
 ('prepare_executor_rows', 'run_executor_row_6'),
 ('select_executor_slot_6', 'run_executor_row_6'),
 ('classify_executor_row_5', 'run_executor_row_6'),
 ('prepare_executor_rows', 'classify_executor_row_6'),
 ('select_executor_slot_6', 'classify_executor_row_6'),
 ('run_executor_row_6', 'classify_executor_row_6'),
 ('classify_executor_row_5', 'classify_executor_row_6'),
 ('prepare_executor_rows', 'select_executor_slot_7'),
 ('classify_executor_row_6', 'select_executor_slot_7'),
 ('prepare_executor_rows', 'run_executor_row_7'),
 ('select_executor_slot_7', 'run_executor_row_7'),
 ('classify_executor_row_6', 'run_executor_row_7'),
 ('prepare_executor_rows', 'classify_executor_row_7'),
 ('select_executor_slot_7', 'classify_executor_row_7'),
 ('run_executor_row_7', 'classify_executor_row_7'),
 ('classify_executor_row_6', 'classify_executor_row_7'),
 ('prepare_executor_rows', 'select_executor_slot_8'),
 ('classify_executor_row_7', 'select_executor_slot_8'),
 ('prepare_executor_rows', 'run_executor_row_8'),
 ('select_executor_slot_8', 'run_executor_row_8'),
 ('classify_executor_row_7', 'run_executor_row_8'),
 ('prepare_executor_rows', 'classify_executor_row_8'),
 ('select_executor_slot_8', 'classify_executor_row_8'),
 ('run_executor_row_8', 'classify_executor_row_8'),
 ('classify_executor_row_7', 'classify_executor_row_8'),
 ('prepare_executor_rows', 'select_executor_result'),
 ('classify_executor_row_1', 'select_executor_result'),
 ('classify_executor_row_2', 'select_executor_result'),
 ('classify_executor_row_3', 'select_executor_result'),
 ('classify_executor_row_4', 'select_executor_result'),
 ('classify_executor_row_5', 'select_executor_result'),
 ('classify_executor_row_6', 'select_executor_result'),
 ('classify_executor_row_7', 'select_executor_result'),
 ('classify_executor_row_8', 'select_executor_result')]
_WHEN_BRANCHES = [('run_executor_row_1', {'equals': 'run', 'path': 'route', 'upstream': 'select_executor_slot_1'}),
 ('run_executor_row_2', {'equals': 'run', 'path': 'route', 'upstream': 'select_executor_slot_2'}),
 ('run_executor_row_3', {'equals': 'run', 'path': 'route', 'upstream': 'select_executor_slot_3'}),
 ('run_executor_row_4', {'equals': 'run', 'path': 'route', 'upstream': 'select_executor_slot_4'}),
 ('run_executor_row_5', {'equals': 'run', 'path': 'route', 'upstream': 'select_executor_slot_5'}),
 ('run_executor_row_6', {'equals': 'run', 'path': 'route', 'upstream': 'select_executor_slot_6'}),
 ('run_executor_row_7', {'equals': 'run', 'path': 'route', 'upstream': 'select_executor_slot_7'}),
 ('run_executor_row_8', {'equals': 'run', 'path': 'route', 'upstream': 'select_executor_slot_8'})]
_EFFECTORS = [{'conduction': [], 'id': 'prepare_executor_rows', 'when': None},
 {'conduction': ['prepare_executor_rows'], 'id': 'select_executor_slot_1', 'when': None},
 {'conduction': ['prepare_executor_rows', 'select_executor_slot_1'],
  'id': 'run_executor_row_1',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_executor_slot_1'}},
 {'conduction': ['prepare_executor_rows', 'select_executor_slot_1', 'run_executor_row_1'],
  'id': 'classify_executor_row_1',
  'when': None},
 {'conduction': ['prepare_executor_rows', 'classify_executor_row_1'],
  'id': 'select_executor_slot_2',
  'when': None},
 {'conduction': ['prepare_executor_rows', 'select_executor_slot_2', 'classify_executor_row_1'],
  'id': 'run_executor_row_2',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_executor_slot_2'}},
 {'conduction': ['prepare_executor_rows',
                 'select_executor_slot_2',
                 'run_executor_row_2',
                 'classify_executor_row_1'],
  'id': 'classify_executor_row_2',
  'when': None},
 {'conduction': ['prepare_executor_rows', 'classify_executor_row_2'],
  'id': 'select_executor_slot_3',
  'when': None},
 {'conduction': ['prepare_executor_rows', 'select_executor_slot_3', 'classify_executor_row_2'],
  'id': 'run_executor_row_3',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_executor_slot_3'}},
 {'conduction': ['prepare_executor_rows',
                 'select_executor_slot_3',
                 'run_executor_row_3',
                 'classify_executor_row_2'],
  'id': 'classify_executor_row_3',
  'when': None},
 {'conduction': ['prepare_executor_rows', 'classify_executor_row_3'],
  'id': 'select_executor_slot_4',
  'when': None},
 {'conduction': ['prepare_executor_rows', 'select_executor_slot_4', 'classify_executor_row_3'],
  'id': 'run_executor_row_4',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_executor_slot_4'}},
 {'conduction': ['prepare_executor_rows',
                 'select_executor_slot_4',
                 'run_executor_row_4',
                 'classify_executor_row_3'],
  'id': 'classify_executor_row_4',
  'when': None},
 {'conduction': ['prepare_executor_rows', 'classify_executor_row_4'],
  'id': 'select_executor_slot_5',
  'when': None},
 {'conduction': ['prepare_executor_rows', 'select_executor_slot_5', 'classify_executor_row_4'],
  'id': 'run_executor_row_5',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_executor_slot_5'}},
 {'conduction': ['prepare_executor_rows',
                 'select_executor_slot_5',
                 'run_executor_row_5',
                 'classify_executor_row_4'],
  'id': 'classify_executor_row_5',
  'when': None},
 {'conduction': ['prepare_executor_rows', 'classify_executor_row_5'],
  'id': 'select_executor_slot_6',
  'when': None},
 {'conduction': ['prepare_executor_rows', 'select_executor_slot_6', 'classify_executor_row_5'],
  'id': 'run_executor_row_6',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_executor_slot_6'}},
 {'conduction': ['prepare_executor_rows',
                 'select_executor_slot_6',
                 'run_executor_row_6',
                 'classify_executor_row_5'],
  'id': 'classify_executor_row_6',
  'when': None},
 {'conduction': ['prepare_executor_rows', 'classify_executor_row_6'],
  'id': 'select_executor_slot_7',
  'when': None},
 {'conduction': ['prepare_executor_rows', 'select_executor_slot_7', 'classify_executor_row_6'],
  'id': 'run_executor_row_7',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_executor_slot_7'}},
 {'conduction': ['prepare_executor_rows',
                 'select_executor_slot_7',
                 'run_executor_row_7',
                 'classify_executor_row_6'],
  'id': 'classify_executor_row_7',
  'when': None},
 {'conduction': ['prepare_executor_rows', 'classify_executor_row_7'],
  'id': 'select_executor_slot_8',
  'when': None},
 {'conduction': ['prepare_executor_rows', 'select_executor_slot_8', 'classify_executor_row_7'],
  'id': 'run_executor_row_8',
  'when': {'equals': 'run', 'path': 'route', 'upstream': 'select_executor_slot_8'}},
 {'conduction': ['prepare_executor_rows',
                 'select_executor_slot_8',
                 'run_executor_row_8',
                 'classify_executor_row_7'],
  'id': 'classify_executor_row_8',
  'when': None},
 {'conduction': ['prepare_executor_rows',
                 'classify_executor_row_1',
                 'classify_executor_row_2',
                 'classify_executor_row_3',
                 'classify_executor_row_4',
                 'classify_executor_row_5',
                 'classify_executor_row_6',
                 'classify_executor_row_7',
                 'classify_executor_row_8'],
  'id': 'select_executor_result',
  'when': None}]

def test_every_conduction_edge_is_declared():
    got = {(str(up), nid) for nid, meta in _NODES.items() for up in meta["conduction"]}
    assert got == set(tuple(edge) for edge in _COND_EDGES)

def test_every_when_branch_is_declared():
    got = {(nid, json.dumps(meta["when"], sort_keys=True)) for nid, meta in _NODES.items() if meta["when"]}
    want = {(nid, json.dumps(when, sort_keys=True)) for nid, when in _WHEN_BRANCHES}
    assert got == want

def test_when_upstream_is_a_direct_parent():
    for nid, when in _WHEN_BRANCHES:
        assert when["upstream"] in _NODES[nid]["conduction"]

def test_unconditional_nodes_succeed_without_outputs():
    from support.graph_model import run_model
    status = run_model(_EFFECTORS, {})
    for nid, meta in _NODES.items():
        if meta["when"] is None:
            assert status[nid] == "succeeded"

