"""Independent conduction and when metadata for test_local_execution."""
from __future__ import annotations
import json

_PATH_ID = 'test_local_execution'
_NODES = {'build_test_terminal_cached': {'atom': 'build_test_terminal_cached',
                                'conduction': ['inspect_test_declaration',
                                               'read_test_green_cache',
                                               'run_declared_tests',
                                               'run_changed_scope_tests',
                                               'write_test_green_cache',
                                               'classify_test_terminal'],
                                'when': {'equals': 'cached',
                                         'path': 'kind',
                                         'upstream': 'classify_test_terminal'}},
 'build_test_terminal_green': {'atom': 'build_test_terminal_green',
                               'conduction': ['inspect_test_declaration',
                                              'read_test_green_cache',
                                              'run_declared_tests',
                                              'run_changed_scope_tests',
                                              'write_test_green_cache',
                                              'classify_test_terminal'],
                               'when': {'equals': 'green',
                                        'path': 'kind',
                                        'upstream': 'classify_test_terminal'}},
 'build_test_terminal_inspection': {'atom': 'build_test_terminal_inspection',
                                    'conduction': ['inspect_test_declaration',
                                                   'read_test_green_cache',
                                                   'run_declared_tests',
                                                   'run_changed_scope_tests',
                                                   'write_test_green_cache',
                                                   'classify_test_terminal'],
                                    'when': {'equals': 'inspection',
                                             'path': 'kind',
                                             'upstream': 'classify_test_terminal'}},
 'build_test_terminal_red': {'atom': 'build_test_terminal_red',
                             'conduction': ['inspect_test_declaration',
                                            'read_test_green_cache',
                                            'run_declared_tests',
                                            'run_changed_scope_tests',
                                            'write_test_green_cache',
                                            'classify_test_terminal'],
                             'when': {'equals': 'red', 'path': 'kind', 'upstream': 'classify_test_terminal'}},
 'classify_test_terminal': {'atom': 'classify_test_terminal',
                            'conduction': ['inspect_test_declaration',
                                           'read_test_green_cache',
                                           'run_declared_tests',
                                           'run_changed_scope_tests',
                                           'write_test_green_cache'],
                            'when': None},
 'derive_changed_test_scope': {'atom': 'derive_changed_test_scope',
                               'conduction': ['inspect_test_declaration', 'select_declared_test_outcome'],
                               'when': None},
 'inspect_test_declaration': {'atom': 'inspect_test_declaration', 'conduction': [], 'when': None},
 'read_test_green_cache': {'atom': 'read_test_green_cache',
                           'conduction': ['inspect_test_declaration'],
                           'when': None},
 'run_changed_scope_tests': {'atom': 'run_changed_scope_tests',
                             'conduction': ['inspect_test_declaration', 'derive_changed_test_scope'],
                             'when': {'equals': 'scope',
                                      'path': 'route',
                                      'upstream': 'derive_changed_test_scope'}},
 'run_declared_tests': {'atom': 'run_declared_tests',
                        'conduction': ['inspect_test_declaration', 'read_test_green_cache'],
                        'when': {'equals': 'miss', 'path': 'route', 'upstream': 'read_test_green_cache'}},
 'select_declared_test_outcome': {'atom': 'select_declared_test_outcome',
                                  'conduction': ['run_declared_tests'],
                                  'when': None},
 'select_green_test_result': {'atom': 'select_green_test_result',
                              'conduction': ['run_declared_tests', 'run_changed_scope_tests'],
                              'when': None},
 'select_test_terminal': {'atom': 'select_test_terminal',
                          'conduction': ['build_test_terminal_inspection',
                                         'build_test_terminal_cached',
                                         'build_test_terminal_green',
                                         'build_test_terminal_red'],
                          'when': None},
 'write_test_green_cache': {'atom': 'write_test_green_cache',
                            'conduction': ['inspect_test_declaration',
                                           'read_test_green_cache',
                                           'select_green_test_result'],
                            'when': None}}
_COND_EDGES = [('inspect_test_declaration', 'read_test_green_cache'),
 ('inspect_test_declaration', 'run_declared_tests'),
 ('read_test_green_cache', 'run_declared_tests'),
 ('run_declared_tests', 'select_declared_test_outcome'),
 ('inspect_test_declaration', 'derive_changed_test_scope'),
 ('select_declared_test_outcome', 'derive_changed_test_scope'),
 ('inspect_test_declaration', 'run_changed_scope_tests'),
 ('derive_changed_test_scope', 'run_changed_scope_tests'),
 ('run_declared_tests', 'select_green_test_result'),
 ('run_changed_scope_tests', 'select_green_test_result'),
 ('inspect_test_declaration', 'write_test_green_cache'),
 ('read_test_green_cache', 'write_test_green_cache'),
 ('select_green_test_result', 'write_test_green_cache'),
 ('inspect_test_declaration', 'classify_test_terminal'),
 ('read_test_green_cache', 'classify_test_terminal'),
 ('run_declared_tests', 'classify_test_terminal'),
 ('run_changed_scope_tests', 'classify_test_terminal'),
 ('write_test_green_cache', 'classify_test_terminal'),
 ('inspect_test_declaration', 'build_test_terminal_inspection'),
 ('read_test_green_cache', 'build_test_terminal_inspection'),
 ('run_declared_tests', 'build_test_terminal_inspection'),
 ('run_changed_scope_tests', 'build_test_terminal_inspection'),
 ('write_test_green_cache', 'build_test_terminal_inspection'),
 ('classify_test_terminal', 'build_test_terminal_inspection'),
 ('inspect_test_declaration', 'build_test_terminal_cached'),
 ('read_test_green_cache', 'build_test_terminal_cached'),
 ('run_declared_tests', 'build_test_terminal_cached'),
 ('run_changed_scope_tests', 'build_test_terminal_cached'),
 ('write_test_green_cache', 'build_test_terminal_cached'),
 ('classify_test_terminal', 'build_test_terminal_cached'),
 ('inspect_test_declaration', 'build_test_terminal_green'),
 ('read_test_green_cache', 'build_test_terminal_green'),
 ('run_declared_tests', 'build_test_terminal_green'),
 ('run_changed_scope_tests', 'build_test_terminal_green'),
 ('write_test_green_cache', 'build_test_terminal_green'),
 ('classify_test_terminal', 'build_test_terminal_green'),
 ('inspect_test_declaration', 'build_test_terminal_red'),
 ('read_test_green_cache', 'build_test_terminal_red'),
 ('run_declared_tests', 'build_test_terminal_red'),
 ('run_changed_scope_tests', 'build_test_terminal_red'),
 ('write_test_green_cache', 'build_test_terminal_red'),
 ('classify_test_terminal', 'build_test_terminal_red'),
 ('build_test_terminal_inspection', 'select_test_terminal'),
 ('build_test_terminal_cached', 'select_test_terminal'),
 ('build_test_terminal_green', 'select_test_terminal'),
 ('build_test_terminal_red', 'select_test_terminal')]
_WHEN_BRANCHES = [('run_declared_tests', {'equals': 'miss', 'path': 'route', 'upstream': 'read_test_green_cache'}),
 ('run_changed_scope_tests', {'equals': 'scope', 'path': 'route', 'upstream': 'derive_changed_test_scope'}),
 ('build_test_terminal_inspection',
  {'equals': 'inspection', 'path': 'kind', 'upstream': 'classify_test_terminal'}),
 ('build_test_terminal_cached', {'equals': 'cached', 'path': 'kind', 'upstream': 'classify_test_terminal'}),
 ('build_test_terminal_green', {'equals': 'green', 'path': 'kind', 'upstream': 'classify_test_terminal'}),
 ('build_test_terminal_red', {'equals': 'red', 'path': 'kind', 'upstream': 'classify_test_terminal'})]
_EFFECTORS = [{'conduction': [], 'id': 'inspect_test_declaration', 'when': None},
 {'conduction': ['inspect_test_declaration'], 'id': 'read_test_green_cache', 'when': None},
 {'conduction': ['inspect_test_declaration', 'read_test_green_cache'],
  'id': 'run_declared_tests',
  'when': {'equals': 'miss', 'path': 'route', 'upstream': 'read_test_green_cache'}},
 {'conduction': ['run_declared_tests'], 'id': 'select_declared_test_outcome', 'when': None},
 {'conduction': ['inspect_test_declaration', 'select_declared_test_outcome'],
  'id': 'derive_changed_test_scope',
  'when': None},
 {'conduction': ['inspect_test_declaration', 'derive_changed_test_scope'],
  'id': 'run_changed_scope_tests',
  'when': {'equals': 'scope', 'path': 'route', 'upstream': 'derive_changed_test_scope'}},
 {'conduction': ['run_declared_tests', 'run_changed_scope_tests'],
  'id': 'select_green_test_result',
  'when': None},
 {'conduction': ['inspect_test_declaration', 'read_test_green_cache', 'select_green_test_result'],
  'id': 'write_test_green_cache',
  'when': None},
 {'conduction': ['inspect_test_declaration',
                 'read_test_green_cache',
                 'run_declared_tests',
                 'run_changed_scope_tests',
                 'write_test_green_cache'],
  'id': 'classify_test_terminal',
  'when': None},
 {'conduction': ['inspect_test_declaration',
                 'read_test_green_cache',
                 'run_declared_tests',
                 'run_changed_scope_tests',
                 'write_test_green_cache',
                 'classify_test_terminal'],
  'id': 'build_test_terminal_inspection',
  'when': {'equals': 'inspection', 'path': 'kind', 'upstream': 'classify_test_terminal'}},
 {'conduction': ['inspect_test_declaration',
                 'read_test_green_cache',
                 'run_declared_tests',
                 'run_changed_scope_tests',
                 'write_test_green_cache',
                 'classify_test_terminal'],
  'id': 'build_test_terminal_cached',
  'when': {'equals': 'cached', 'path': 'kind', 'upstream': 'classify_test_terminal'}},
 {'conduction': ['inspect_test_declaration',
                 'read_test_green_cache',
                 'run_declared_tests',
                 'run_changed_scope_tests',
                 'write_test_green_cache',
                 'classify_test_terminal'],
  'id': 'build_test_terminal_green',
  'when': {'equals': 'green', 'path': 'kind', 'upstream': 'classify_test_terminal'}},
 {'conduction': ['inspect_test_declaration',
                 'read_test_green_cache',
                 'run_declared_tests',
                 'run_changed_scope_tests',
                 'write_test_green_cache',
                 'classify_test_terminal'],
  'id': 'build_test_terminal_red',
  'when': {'equals': 'red', 'path': 'kind', 'upstream': 'classify_test_terminal'}},
 {'conduction': ['build_test_terminal_inspection',
                 'build_test_terminal_cached',
                 'build_test_terminal_green',
                 'build_test_terminal_red'],
  'id': 'select_test_terminal',
  'when': None}]

def test_every_conduction_edge_is_declared():
    got = {(str(up), nid) for nid, meta in _NODES.items() for up in meta["conduction"]}
    assert got == set(tuple(edge) for edge in _COND_EDGES)

def test_every_when_branch_is_declared():
    got = {(nid, json.dumps(meta["when"], sort_keys=True)) for nid, meta in _NODES.items() if meta["when"]}
    want = {(nid, json.dumps(when, sort_keys=True)) for nid, when in _WHEN_BRANCHES}
    assert got == want

def test_when_upstream_is_a_direct_parent():
    for nid, when in _WHEN_BRANCHES:
        assert when["upstream"] in _NODES[nid]["conduction"]

def test_unconditional_nodes_succeed_without_outputs():
    from support.graph_model import run_model
    status = run_model(_EFFECTORS, {})
    for nid, meta in _NODES.items():
        if meta["when"] is None:
            assert status[nid] == "succeeded"

