"""Independent conduction and when metadata for issue_split."""
from __future__ import annotations
import json

_PATH_ID = 'issue_split'
_NODES = {'apply_issue_manual': {'atom': 'apply_issue_manual',
                        'conduction': ['get_issue', 'plan_issue_split', 'select_park_stop'],
                        'when': {'equals': 'skip', 'path': 'route', 'upstream': 'select_park_stop'}},
 'close_issue_tracker': {'atom': 'close_issue_tracker',
                         'conduction': ['get_issue', 'plan_issue_split', 'comment_issue_tracker'],
                         'when': {'equals': 'children', 'path': 'route', 'upstream': 'plan_issue_split'}},
 'comment_issue_tracker': {'atom': 'comment_issue_tracker',
                           'conduction': ['get_issue',
                                          'plan_issue_split',
                                          'create_issue_split_child_1',
                                          'create_issue_split_child_2',
                                          'create_issue_split_child_3',
                                          'create_issue_split_child_4',
                                          'create_issue_split_child_5',
                                          'mark_issue_tracker'],
                           'when': {'equals': 'children', 'path': 'route', 'upstream': 'plan_issue_split'}},
 'create_issue_split_child_1': {'atom': 'create_issue_split_child_1',
                                'conduction': ['get_issue', 'plan_issue_split'],
                                'when': {'equals': 'present',
                                         'path': 'child_1',
                                         'upstream': 'plan_issue_split'}},
 'create_issue_split_child_2': {'atom': 'create_issue_split_child_2',
                                'conduction': ['get_issue', 'plan_issue_split', 'create_issue_split_child_1'],
                                'when': {'equals': 'present',
                                         'path': 'child_2',
                                         'upstream': 'plan_issue_split'}},
 'create_issue_split_child_3': {'atom': 'create_issue_split_child_3',
                                'conduction': ['get_issue', 'plan_issue_split', 'create_issue_split_child_2'],
                                'when': {'equals': 'present',
                                         'path': 'child_3',
                                         'upstream': 'plan_issue_split'}},
 'create_issue_split_child_4': {'atom': 'create_issue_split_child_4',
                                'conduction': ['get_issue', 'plan_issue_split', 'create_issue_split_child_3'],
                                'when': {'equals': 'present',
                                         'path': 'child_4',
                                         'upstream': 'plan_issue_split'}},
 'create_issue_split_child_5': {'atom': 'create_issue_split_child_5',
                                'conduction': ['get_issue', 'plan_issue_split', 'create_issue_split_child_4'],
                                'when': {'equals': 'present',
                                         'path': 'child_5',
                                         'upstream': 'plan_issue_split'}},
 'get_issue': {'atom': 'get_issue', 'conduction': [], 'when': None},
 'mark_issue_tracker': {'atom': 'mark_issue_tracker',
                        'conduction': ['get_issue',
                                       'plan_issue_split',
                                       'create_issue_split_child_1',
                                       'create_issue_split_child_2',
                                       'create_issue_split_child_3',
                                       'create_issue_split_child_4',
                                       'create_issue_split_child_5'],
                        'when': {'equals': 'children', 'path': 'route', 'upstream': 'plan_issue_split'}},
 'plan_issue_split': {'atom': 'plan_issue_split', 'conduction': ['get_issue'], 'when': None},
 'select_park_stop': {'atom': 'select_park_stop',
                      'conduction': ['plan_issue_split'],
                      'when': {'equals': 'park', 'path': 'route', 'upstream': 'plan_issue_split'}},
 'summarize_issue_split': {'atom': 'summarize_issue_split',
                           'conduction': ['plan_issue_split',
                                          'comment_issue_tracker',
                                          'close_issue_tracker',
                                          'select_park_stop',
                                          'apply_issue_manual'],
                           'when': None}}
_COND_EDGES = [('get_issue', 'plan_issue_split'),
 ('get_issue', 'create_issue_split_child_1'),
 ('plan_issue_split', 'create_issue_split_child_1'),
 ('get_issue', 'create_issue_split_child_2'),
 ('plan_issue_split', 'create_issue_split_child_2'),
 ('create_issue_split_child_1', 'create_issue_split_child_2'),
 ('get_issue', 'create_issue_split_child_3'),
 ('plan_issue_split', 'create_issue_split_child_3'),
 ('create_issue_split_child_2', 'create_issue_split_child_3'),
 ('get_issue', 'create_issue_split_child_4'),
 ('plan_issue_split', 'create_issue_split_child_4'),
 ('create_issue_split_child_3', 'create_issue_split_child_4'),
 ('get_issue', 'create_issue_split_child_5'),
 ('plan_issue_split', 'create_issue_split_child_5'),
 ('create_issue_split_child_4', 'create_issue_split_child_5'),
 ('get_issue', 'mark_issue_tracker'),
 ('plan_issue_split', 'mark_issue_tracker'),
 ('create_issue_split_child_1', 'mark_issue_tracker'),
 ('create_issue_split_child_2', 'mark_issue_tracker'),
 ('create_issue_split_child_3', 'mark_issue_tracker'),
 ('create_issue_split_child_4', 'mark_issue_tracker'),
 ('create_issue_split_child_5', 'mark_issue_tracker'),
 ('get_issue', 'comment_issue_tracker'),
 ('plan_issue_split', 'comment_issue_tracker'),
 ('create_issue_split_child_1', 'comment_issue_tracker'),
 ('create_issue_split_child_2', 'comment_issue_tracker'),
 ('create_issue_split_child_3', 'comment_issue_tracker'),
 ('create_issue_split_child_4', 'comment_issue_tracker'),
 ('create_issue_split_child_5', 'comment_issue_tracker'),
 ('mark_issue_tracker', 'comment_issue_tracker'),
 ('get_issue', 'close_issue_tracker'),
 ('plan_issue_split', 'close_issue_tracker'),
 ('comment_issue_tracker', 'close_issue_tracker'),
 ('plan_issue_split', 'select_park_stop'),
 ('get_issue', 'apply_issue_manual'),
 ('plan_issue_split', 'apply_issue_manual'),
 ('select_park_stop', 'apply_issue_manual'),
 ('plan_issue_split', 'summarize_issue_split'),
 ('comment_issue_tracker', 'summarize_issue_split'),
 ('close_issue_tracker', 'summarize_issue_split'),
 ('select_park_stop', 'summarize_issue_split'),
 ('apply_issue_manual', 'summarize_issue_split')]
_WHEN_BRANCHES = [('create_issue_split_child_1', {'equals': 'present', 'path': 'child_1', 'upstream': 'plan_issue_split'}),
 ('create_issue_split_child_2', {'equals': 'present', 'path': 'child_2', 'upstream': 'plan_issue_split'}),
 ('create_issue_split_child_3', {'equals': 'present', 'path': 'child_3', 'upstream': 'plan_issue_split'}),
 ('create_issue_split_child_4', {'equals': 'present', 'path': 'child_4', 'upstream': 'plan_issue_split'}),
 ('create_issue_split_child_5', {'equals': 'present', 'path': 'child_5', 'upstream': 'plan_issue_split'}),
 ('mark_issue_tracker', {'equals': 'children', 'path': 'route', 'upstream': 'plan_issue_split'}),
 ('comment_issue_tracker', {'equals': 'children', 'path': 'route', 'upstream': 'plan_issue_split'}),
 ('close_issue_tracker', {'equals': 'children', 'path': 'route', 'upstream': 'plan_issue_split'}),
 ('select_park_stop', {'equals': 'park', 'path': 'route', 'upstream': 'plan_issue_split'}),
 ('apply_issue_manual', {'equals': 'skip', 'path': 'route', 'upstream': 'select_park_stop'})]
_EFFECTORS = [{'conduction': [], 'id': 'get_issue', 'when': None},
 {'conduction': ['get_issue'], 'id': 'plan_issue_split', 'when': None},
 {'conduction': ['get_issue', 'plan_issue_split'],
  'id': 'create_issue_split_child_1',
  'when': {'equals': 'present', 'path': 'child_1', 'upstream': 'plan_issue_split'}},
 {'conduction': ['get_issue', 'plan_issue_split', 'create_issue_split_child_1'],
  'id': 'create_issue_split_child_2',
  'when': {'equals': 'present', 'path': 'child_2', 'upstream': 'plan_issue_split'}},
 {'conduction': ['get_issue', 'plan_issue_split', 'create_issue_split_child_2'],
  'id': 'create_issue_split_child_3',
  'when': {'equals': 'present', 'path': 'child_3', 'upstream': 'plan_issue_split'}},
 {'conduction': ['get_issue', 'plan_issue_split', 'create_issue_split_child_3'],
  'id': 'create_issue_split_child_4',
  'when': {'equals': 'present', 'path': 'child_4', 'upstream': 'plan_issue_split'}},
 {'conduction': ['get_issue', 'plan_issue_split', 'create_issue_split_child_4'],
  'id': 'create_issue_split_child_5',
  'when': {'equals': 'present', 'path': 'child_5', 'upstream': 'plan_issue_split'}},
 {'conduction': ['get_issue',
                 'plan_issue_split',
                 'create_issue_split_child_1',
                 'create_issue_split_child_2',
                 'create_issue_split_child_3',
                 'create_issue_split_child_4',
                 'create_issue_split_child_5'],
  'id': 'mark_issue_tracker',
  'when': {'equals': 'children', 'path': 'route', 'upstream': 'plan_issue_split'}},
 {'conduction': ['get_issue',
                 'plan_issue_split',
                 'create_issue_split_child_1',
                 'create_issue_split_child_2',
                 'create_issue_split_child_3',
                 'create_issue_split_child_4',
                 'create_issue_split_child_5',
                 'mark_issue_tracker'],
  'id': 'comment_issue_tracker',
  'when': {'equals': 'children', 'path': 'route', 'upstream': 'plan_issue_split'}},
 {'conduction': ['get_issue', 'plan_issue_split', 'comment_issue_tracker'],
  'id': 'close_issue_tracker',
  'when': {'equals': 'children', 'path': 'route', 'upstream': 'plan_issue_split'}},
 {'conduction': ['plan_issue_split'],
  'id': 'select_park_stop',
  'when': {'equals': 'park', 'path': 'route', 'upstream': 'plan_issue_split'}},
 {'conduction': ['get_issue', 'plan_issue_split', 'select_park_stop'],
  'id': 'apply_issue_manual',
  'when': {'equals': 'skip', 'path': 'route', 'upstream': 'select_park_stop'}},
 {'conduction': ['plan_issue_split',
                 'comment_issue_tracker',
                 'close_issue_tracker',
                 'select_park_stop',
                 'apply_issue_manual'],
  'id': 'summarize_issue_split',
  'when': None}]

def test_every_conduction_edge_is_declared():
    got = {(str(up), nid) for nid, meta in _NODES.items() for up in meta["conduction"]}
    assert got == set(tuple(edge) for edge in _COND_EDGES)

def test_every_when_branch_is_declared():
    got = {(nid, json.dumps(meta["when"], sort_keys=True)) for nid, meta in _NODES.items() if meta["when"]}
    want = {(nid, json.dumps(when, sort_keys=True)) for nid, when in _WHEN_BRANCHES}
    assert got == want

def test_when_upstream_is_a_direct_parent():
    for nid, when in _WHEN_BRANCHES:
        assert when["upstream"] in _NODES[nid]["conduction"]

def test_unconditional_nodes_succeed_without_outputs():
    from support.graph_model import run_model
    status = run_model(_EFFECTORS, {})
    for nid, meta in _NODES.items():
        if meta["when"] is None:
            assert status[nid] == "succeeded"

