"""Independent conduction and when metadata for coding_execution."""
from __future__ import annotations
import json

_PATH_ID = 'coding_execution'
_NODES = {'coding_execution_terminal': {'atom': 'coding_execution_terminal',
                               'conduction': ['finalize_coding_result', 'coding_fail_closed'],
                               'when': None},
 'coding_fail_closed': {'atom': 'coding_fail_closed',
                        'conduction': ['finalize_coding_result'],
                        'when': {'equals': 'fail_closed',
                                 'path': 'route',
                                 'upstream': 'finalize_coding_result'}},
 'coding_retry_agent': {'atom': 'coding_retry_agent',
                        'conduction': ['prepare_coding_request', 'validate_coding_result'],
                        'when': {'equals': 'retry', 'path': 'route', 'upstream': 'validate_coding_result'}},
 'collect_coding_issue_snapshot': {'atom': 'collect_coding_issue_snapshot',
                                   'conduction': ['prepare_coding_request', 'select_coding_result'],
                                   'when': {'equals': 'issue_snapshot',
                                            'path': 'evidence_kind',
                                            'upstream': 'select_coding_result'}},
 'collect_coding_localized_diff': {'atom': 'collect_coding_localized_diff',
                                   'conduction': ['prepare_coding_request', 'select_coding_result'],
                                   'when': {'equals': 'localized_diff',
                                            'path': 'evidence_kind',
                                            'upstream': 'select_coding_result'}},
 'collect_coding_repo_structure': {'atom': 'collect_coding_repo_structure',
                                   'conduction': ['prepare_coding_request', 'select_coding_result'],
                                   'when': {'equals': 'repo_structure',
                                            'path': 'evidence_kind',
                                            'upstream': 'select_coding_result'}},
 'collect_coding_test_contract': {'atom': 'collect_coding_test_contract',
                                  'conduction': ['prepare_coding_request', 'select_coding_result'],
                                  'when': {'equals': 'test_contract',
                                           'path': 'evidence_kind',
                                           'upstream': 'select_coding_result'}},
 'evidence_coding_agent': {'atom': 'evidence_coding_agent',
                           'conduction': ['prepare_coding_request',
                                          'select_coding_result',
                                          'collect_coding_issue_snapshot',
                                          'collect_coding_repo_structure',
                                          'collect_coding_test_contract',
                                          'collect_coding_localized_diff'],
                           'when': {'equals': 'evidence',
                                    'path': 'route',
                                    'upstream': 'select_coding_result'}},
 'finalize_coding_result': {'atom': 'finalize_coding_result',
                            'conduction': ['select_coding_result', 'select_evidence_coding'],
                            'when': None},
 'prepare_coding_request': {'atom': 'prepare_coding_request', 'conduction': [], 'when': None},
 'run_agent': {'atom': 'run_agent', 'conduction': ['prepare_coding_request'], 'when': None},
 'select_coding_result': {'atom': 'select_coding_result',
                          'conduction': ['validate_coding_result', 'validate_coding_retry'],
                          'when': None},
 'select_evidence_coding': {'atom': 'select_evidence_coding',
                            'conduction': ['select_coding_result', 'validate_evidence_coding'],
                            'when': None},
 'validate_coding_result': {'atom': 'validate_coding_result', 'conduction': ['run_agent'], 'when': None},
 'validate_coding_retry': {'atom': 'validate_coding_retry',
                           'conduction': ['validate_coding_result', 'coding_retry_agent'],
                           'when': {'equals': 'retry',
                                    'path': 'route',
                                    'upstream': 'validate_coding_result'}},
 'validate_evidence_coding': {'atom': 'validate_evidence_coding',
                              'conduction': ['select_coding_result', 'evidence_coding_agent'],
                              'when': {'equals': 'evidence',
                                       'path': 'route',
                                       'upstream': 'select_coding_result'}}}
_COND_EDGES = [('prepare_coding_request', 'run_agent'),
 ('run_agent', 'validate_coding_result'),
 ('prepare_coding_request', 'coding_retry_agent'),
 ('validate_coding_result', 'coding_retry_agent'),
 ('validate_coding_result', 'validate_coding_retry'),
 ('coding_retry_agent', 'validate_coding_retry'),
 ('validate_coding_result', 'select_coding_result'),
 ('validate_coding_retry', 'select_coding_result'),
 ('prepare_coding_request', 'collect_coding_issue_snapshot'),
 ('select_coding_result', 'collect_coding_issue_snapshot'),
 ('prepare_coding_request', 'collect_coding_repo_structure'),
 ('select_coding_result', 'collect_coding_repo_structure'),
 ('prepare_coding_request', 'collect_coding_test_contract'),
 ('select_coding_result', 'collect_coding_test_contract'),
 ('prepare_coding_request', 'collect_coding_localized_diff'),
 ('select_coding_result', 'collect_coding_localized_diff'),
 ('prepare_coding_request', 'evidence_coding_agent'),
 ('select_coding_result', 'evidence_coding_agent'),
 ('collect_coding_issue_snapshot', 'evidence_coding_agent'),
 ('collect_coding_repo_structure', 'evidence_coding_agent'),
 ('collect_coding_test_contract', 'evidence_coding_agent'),
 ('collect_coding_localized_diff', 'evidence_coding_agent'),
 ('select_coding_result', 'validate_evidence_coding'),
 ('evidence_coding_agent', 'validate_evidence_coding'),
 ('select_coding_result', 'select_evidence_coding'),
 ('validate_evidence_coding', 'select_evidence_coding'),
 ('select_coding_result', 'finalize_coding_result'),
 ('select_evidence_coding', 'finalize_coding_result'),
 ('finalize_coding_result', 'coding_fail_closed'),
 ('finalize_coding_result', 'coding_execution_terminal'),
 ('coding_fail_closed', 'coding_execution_terminal')]
_WHEN_BRANCHES = [('coding_retry_agent', {'equals': 'retry', 'path': 'route', 'upstream': 'validate_coding_result'}),
 ('validate_coding_retry', {'equals': 'retry', 'path': 'route', 'upstream': 'validate_coding_result'}),
 ('collect_coding_issue_snapshot',
  {'equals': 'issue_snapshot', 'path': 'evidence_kind', 'upstream': 'select_coding_result'}),
 ('collect_coding_repo_structure',
  {'equals': 'repo_structure', 'path': 'evidence_kind', 'upstream': 'select_coding_result'}),
 ('collect_coding_test_contract',
  {'equals': 'test_contract', 'path': 'evidence_kind', 'upstream': 'select_coding_result'}),
 ('collect_coding_localized_diff',
  {'equals': 'localized_diff', 'path': 'evidence_kind', 'upstream': 'select_coding_result'}),
 ('evidence_coding_agent', {'equals': 'evidence', 'path': 'route', 'upstream': 'select_coding_result'}),
 ('validate_evidence_coding', {'equals': 'evidence', 'path': 'route', 'upstream': 'select_coding_result'}),
 ('coding_fail_closed', {'equals': 'fail_closed', 'path': 'route', 'upstream': 'finalize_coding_result'})]
_EFFECTORS = [{'conduction': [], 'id': 'prepare_coding_request', 'when': None},
 {'conduction': ['prepare_coding_request'], 'id': 'run_agent', 'when': None},
 {'conduction': ['run_agent'], 'id': 'validate_coding_result', 'when': None},
 {'conduction': ['prepare_coding_request', 'validate_coding_result'],
  'id': 'coding_retry_agent',
  'when': {'equals': 'retry', 'path': 'route', 'upstream': 'validate_coding_result'}},
 {'conduction': ['validate_coding_result', 'coding_retry_agent'],
  'id': 'validate_coding_retry',
  'when': {'equals': 'retry', 'path': 'route', 'upstream': 'validate_coding_result'}},
 {'conduction': ['validate_coding_result', 'validate_coding_retry'],
  'id': 'select_coding_result',
  'when': None},
 {'conduction': ['prepare_coding_request', 'select_coding_result'],
  'id': 'collect_coding_issue_snapshot',
  'when': {'equals': 'issue_snapshot', 'path': 'evidence_kind', 'upstream': 'select_coding_result'}},
 {'conduction': ['prepare_coding_request', 'select_coding_result'],
  'id': 'collect_coding_repo_structure',
  'when': {'equals': 'repo_structure', 'path': 'evidence_kind', 'upstream': 'select_coding_result'}},
 {'conduction': ['prepare_coding_request', 'select_coding_result'],
  'id': 'collect_coding_test_contract',
  'when': {'equals': 'test_contract', 'path': 'evidence_kind', 'upstream': 'select_coding_result'}},
 {'conduction': ['prepare_coding_request', 'select_coding_result'],
  'id': 'collect_coding_localized_diff',
  'when': {'equals': 'localized_diff', 'path': 'evidence_kind', 'upstream': 'select_coding_result'}},
 {'conduction': ['prepare_coding_request',
                 'select_coding_result',
                 'collect_coding_issue_snapshot',
                 'collect_coding_repo_structure',
                 'collect_coding_test_contract',
                 'collect_coding_localized_diff'],
  'id': 'evidence_coding_agent',
  'when': {'equals': 'evidence', 'path': 'route', 'upstream': 'select_coding_result'}},
 {'conduction': ['select_coding_result', 'evidence_coding_agent'],
  'id': 'validate_evidence_coding',
  'when': {'equals': 'evidence', 'path': 'route', 'upstream': 'select_coding_result'}},
 {'conduction': ['select_coding_result', 'validate_evidence_coding'],
  'id': 'select_evidence_coding',
  'when': None},
 {'conduction': ['select_coding_result', 'select_evidence_coding'],
  'id': 'finalize_coding_result',
  'when': None},
 {'conduction': ['finalize_coding_result'],
  'id': 'coding_fail_closed',
  'when': {'equals': 'fail_closed', 'path': 'route', 'upstream': 'finalize_coding_result'}},
 {'conduction': ['finalize_coding_result', 'coding_fail_closed'],
  'id': 'coding_execution_terminal',
  'when': None}]

def test_every_conduction_edge_is_declared():
    got = {(str(up), nid) for nid, meta in _NODES.items() for up in meta["conduction"]}
    assert got == set(tuple(edge) for edge in _COND_EDGES)

def test_every_when_branch_is_declared():
    got = {(nid, json.dumps(meta["when"], sort_keys=True)) for nid, meta in _NODES.items() if meta["when"]}
    want = {(nid, json.dumps(when, sort_keys=True)) for nid, when in _WHEN_BRANCHES}
    assert got == want

def test_when_upstream_is_a_direct_parent():
    for nid, when in _WHEN_BRANCHES:
        assert when["upstream"] in _NODES[nid]["conduction"]

def test_unconditional_nodes_succeed_without_outputs():
    from support.graph_model import run_model
    status = run_model(_EFFECTORS, {})
    for nid, meta in _NODES.items():
        if meta["when"] is None:
            assert status[nid] == "succeeded"

