"""Independent conduction and when metadata for intake_check_execution."""
from __future__ import annotations
import json

_PATH_ID = 'intake_check_execution'
_NODES = {'classify_intake_check_route': {'atom': 'classify_intake_check_route',
                                 'conduction': ['prepare_intake_check', 'read_intake_check_issue'],
                                 'when': None},
 'intake_check_terminal': {'atom': 'intake_check_terminal',
                           'conduction': ['prepare_intake_check',
                                          'read_intake_check_issue',
                                          'resolve_intake_check_clone',
                                          'select_intake_check_result'],
                           'when': None},
 'parse_intake_covering_prs': {'atom': 'parse_intake_covering_prs',
                               'conduction': ['prepare_intake_check', 'classify_intake_check_route'],
                               'when': {'equals': 'duplicate_ai_pr',
                                        'path': 'route',
                                        'upstream': 'classify_intake_check_route'}},
 'prepare_intake_check': {'atom': 'prepare_intake_check', 'conduction': [], 'when': None},
 'probe_intake_check_shape': {'atom': 'probe_intake_check_shape',
                              'conduction': ['resolve_intake_check_clone', 'classify_intake_check_route'],
                              'when': {'equals': 'shape',
                                       'path': 'route',
                                       'upstream': 'classify_intake_check_route'}},
 'read_intake_check_issue': {'atom': 'read_intake_check_issue',
                             'conduction': ['prepare_intake_check'],
                             'when': None},
 'resolve_intake_check_clone': {'atom': 'resolve_intake_check_clone',
                                'conduction': ['prepare_intake_check', 'read_intake_check_issue'],
                                'when': None},
 'run_intake_ambiguity_check': {'atom': 'run_intake_ambiguity_check',
                                'conduction': ['read_intake_check_issue', 'classify_intake_check_route'],
                                'when': {'equals': 'ambiguity',
                                         'path': 'route',
                                         'upstream': 'classify_intake_check_route'}},
 'run_intake_duplicate_pr_check': {'atom': 'run_intake_duplicate_pr_check',
                                   'conduction': ['read_intake_check_issue',
                                                  'parse_intake_covering_prs',
                                                  'classify_intake_check_route'],
                                   'when': {'equals': 'duplicate_ai_pr',
                                            'path': 'route',
                                            'upstream': 'classify_intake_check_route'}},
 'run_intake_open_check': {'atom': 'run_intake_open_check',
                           'conduction': ['read_intake_check_issue', 'classify_intake_check_route'],
                           'when': {'equals': 'open',
                                    'path': 'route',
                                    'upstream': 'classify_intake_check_route'}},
 'run_intake_satisfied_check': {'atom': 'run_intake_satisfied_check',
                                'conduction': ['read_intake_check_issue',
                                               'resolve_intake_check_clone',
                                               'classify_intake_check_route'],
                                'when': {'equals': 'satisfied',
                                         'path': 'route',
                                         'upstream': 'classify_intake_check_route'}},
 'run_intake_shape_check': {'atom': 'run_intake_shape_check',
                            'conduction': ['read_intake_check_issue',
                                           'probe_intake_check_shape',
                                           'classify_intake_check_route'],
                            'when': {'equals': 'shape',
                                     'path': 'route',
                                     'upstream': 'classify_intake_check_route'}},
 'run_intake_superseded_check': {'atom': 'run_intake_superseded_check',
                                 'conduction': ['prepare_intake_check',
                                                'read_intake_check_issue',
                                                'classify_intake_check_route'],
                                 'when': {'equals': 'superseded',
                                          'path': 'route',
                                          'upstream': 'classify_intake_check_route'}},
 'select_intake_check_result': {'atom': 'select_intake_check_result',
                                'conduction': ['run_intake_open_check',
                                               'run_intake_superseded_check',
                                               'run_intake_shape_check',
                                               'run_intake_satisfied_check',
                                               'run_intake_ambiguity_check',
                                               'run_intake_duplicate_pr_check',
                                               'parse_intake_covering_prs'],
                                'when': None}}
_COND_EDGES = [('prepare_intake_check', 'read_intake_check_issue'),
 ('prepare_intake_check', 'resolve_intake_check_clone'),
 ('read_intake_check_issue', 'resolve_intake_check_clone'),
 ('prepare_intake_check', 'classify_intake_check_route'),
 ('read_intake_check_issue', 'classify_intake_check_route'),
 ('read_intake_check_issue', 'run_intake_open_check'),
 ('classify_intake_check_route', 'run_intake_open_check'),
 ('prepare_intake_check', 'run_intake_superseded_check'),
 ('read_intake_check_issue', 'run_intake_superseded_check'),
 ('classify_intake_check_route', 'run_intake_superseded_check'),
 ('resolve_intake_check_clone', 'probe_intake_check_shape'),
 ('classify_intake_check_route', 'probe_intake_check_shape'),
 ('read_intake_check_issue', 'run_intake_shape_check'),
 ('probe_intake_check_shape', 'run_intake_shape_check'),
 ('classify_intake_check_route', 'run_intake_shape_check'),
 ('read_intake_check_issue', 'run_intake_satisfied_check'),
 ('resolve_intake_check_clone', 'run_intake_satisfied_check'),
 ('classify_intake_check_route', 'run_intake_satisfied_check'),
 ('read_intake_check_issue', 'run_intake_ambiguity_check'),
 ('classify_intake_check_route', 'run_intake_ambiguity_check'),
 ('prepare_intake_check', 'parse_intake_covering_prs'),
 ('classify_intake_check_route', 'parse_intake_covering_prs'),
 ('read_intake_check_issue', 'run_intake_duplicate_pr_check'),
 ('parse_intake_covering_prs', 'run_intake_duplicate_pr_check'),
 ('classify_intake_check_route', 'run_intake_duplicate_pr_check'),
 ('run_intake_open_check', 'select_intake_check_result'),
 ('run_intake_superseded_check', 'select_intake_check_result'),
 ('run_intake_shape_check', 'select_intake_check_result'),
 ('run_intake_satisfied_check', 'select_intake_check_result'),
 ('run_intake_ambiguity_check', 'select_intake_check_result'),
 ('run_intake_duplicate_pr_check', 'select_intake_check_result'),
 ('parse_intake_covering_prs', 'select_intake_check_result'),
 ('prepare_intake_check', 'intake_check_terminal'),
 ('read_intake_check_issue', 'intake_check_terminal'),
 ('resolve_intake_check_clone', 'intake_check_terminal'),
 ('select_intake_check_result', 'intake_check_terminal')]
_WHEN_BRANCHES = [('run_intake_open_check', {'equals': 'open', 'path': 'route', 'upstream': 'classify_intake_check_route'}),
 ('run_intake_superseded_check',
  {'equals': 'superseded', 'path': 'route', 'upstream': 'classify_intake_check_route'}),
 ('probe_intake_check_shape',
  {'equals': 'shape', 'path': 'route', 'upstream': 'classify_intake_check_route'}),
 ('run_intake_shape_check', {'equals': 'shape', 'path': 'route', 'upstream': 'classify_intake_check_route'}),
 ('run_intake_satisfied_check',
  {'equals': 'satisfied', 'path': 'route', 'upstream': 'classify_intake_check_route'}),
 ('run_intake_ambiguity_check',
  {'equals': 'ambiguity', 'path': 'route', 'upstream': 'classify_intake_check_route'}),
 ('parse_intake_covering_prs',
  {'equals': 'duplicate_ai_pr', 'path': 'route', 'upstream': 'classify_intake_check_route'}),
 ('run_intake_duplicate_pr_check',
  {'equals': 'duplicate_ai_pr', 'path': 'route', 'upstream': 'classify_intake_check_route'})]
_EFFECTORS = [{'conduction': [], 'id': 'prepare_intake_check', 'when': None},
 {'conduction': ['prepare_intake_check'], 'id': 'read_intake_check_issue', 'when': None},
 {'conduction': ['prepare_intake_check', 'read_intake_check_issue'],
  'id': 'resolve_intake_check_clone',
  'when': None},
 {'conduction': ['prepare_intake_check', 'read_intake_check_issue'],
  'id': 'classify_intake_check_route',
  'when': None},
 {'conduction': ['read_intake_check_issue', 'classify_intake_check_route'],
  'id': 'run_intake_open_check',
  'when': {'equals': 'open', 'path': 'route', 'upstream': 'classify_intake_check_route'}},
 {'conduction': ['prepare_intake_check', 'read_intake_check_issue', 'classify_intake_check_route'],
  'id': 'run_intake_superseded_check',
  'when': {'equals': 'superseded', 'path': 'route', 'upstream': 'classify_intake_check_route'}},
 {'conduction': ['resolve_intake_check_clone', 'classify_intake_check_route'],
  'id': 'probe_intake_check_shape',
  'when': {'equals': 'shape', 'path': 'route', 'upstream': 'classify_intake_check_route'}},
 {'conduction': ['read_intake_check_issue', 'probe_intake_check_shape', 'classify_intake_check_route'],
  'id': 'run_intake_shape_check',
  'when': {'equals': 'shape', 'path': 'route', 'upstream': 'classify_intake_check_route'}},
 {'conduction': ['read_intake_check_issue', 'resolve_intake_check_clone', 'classify_intake_check_route'],
  'id': 'run_intake_satisfied_check',
  'when': {'equals': 'satisfied', 'path': 'route', 'upstream': 'classify_intake_check_route'}},
 {'conduction': ['read_intake_check_issue', 'classify_intake_check_route'],
  'id': 'run_intake_ambiguity_check',
  'when': {'equals': 'ambiguity', 'path': 'route', 'upstream': 'classify_intake_check_route'}},
 {'conduction': ['prepare_intake_check', 'classify_intake_check_route'],
  'id': 'parse_intake_covering_prs',
  'when': {'equals': 'duplicate_ai_pr', 'path': 'route', 'upstream': 'classify_intake_check_route'}},
 {'conduction': ['read_intake_check_issue', 'parse_intake_covering_prs', 'classify_intake_check_route'],
  'id': 'run_intake_duplicate_pr_check',
  'when': {'equals': 'duplicate_ai_pr', 'path': 'route', 'upstream': 'classify_intake_check_route'}},
 {'conduction': ['run_intake_open_check',
                 'run_intake_superseded_check',
                 'run_intake_shape_check',
                 'run_intake_satisfied_check',
                 'run_intake_ambiguity_check',
                 'run_intake_duplicate_pr_check',
                 'parse_intake_covering_prs'],
  'id': 'select_intake_check_result',
  'when': None},
 {'conduction': ['prepare_intake_check',
                 'read_intake_check_issue',
                 'resolve_intake_check_clone',
                 'select_intake_check_result'],
  'id': 'intake_check_terminal',
  'when': None}]

def test_every_conduction_edge_is_declared():
    got = {(str(up), nid) for nid, meta in _NODES.items() for up in meta["conduction"]}
    assert got == set(tuple(edge) for edge in _COND_EDGES)

def test_every_when_branch_is_declared():
    got = {(nid, json.dumps(meta["when"], sort_keys=True)) for nid, meta in _NODES.items() if meta["when"]}
    want = {(nid, json.dumps(when, sort_keys=True)) for nid, when in _WHEN_BRANCHES}
    assert got == want

def test_when_upstream_is_a_direct_parent():
    for nid, when in _WHEN_BRANCHES:
        assert when["upstream"] in _NODES[nid]["conduction"]

def test_unconditional_nodes_succeed_without_outputs():
    from support.graph_model import run_model
    status = run_model(_EFFECTORS, {})
    for nid, meta in _NODES.items():
        if meta["when"] is None:
            assert status[nid] == "succeeded"

